# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_81 as module_0


def test_case_0():
    none_type_0 = None
    omapi_startup_message_0 = module_0.OmapiStartupMessage(none_type_0)
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    var_0 = omapi_startup_message_0.dump_oneline()
    assert var_0 == "protocol_version=100 header_size=24"
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    var_1 = omapi_startup_message_0.dump_oneline()
    assert var_1 == "protocol_version=100 header_size=24"
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -2013
    omapi_startup_message_0 = module_0.OmapiStartupMessage(int_0, int_0)
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == -2013
    assert omapi_startup_message_0.header_size == -2013
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_0.validate()


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    float_0 = -429.39
    omapi_startup_message_0 = module_0.OmapiStartupMessage(none_type_0, float_0)
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == pytest.approx(
        -429.39, abs=0.01, rel=0.01
    )
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_0.validate()


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = 'S8Kk~~VA*Wi*.:"Hq'
    omapi_startup_message_0 = module_0.OmapiStartupMessage(str_0)
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 'S8Kk~~VA*Wi*.:"Hq'
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_0.as_string()


@pytest.mark.xfail(strict=True)
def test_case_4():
    omapi_startup_message_0 = module_0.OmapiStartupMessage()
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_0.serialize(omapi_startup_message_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    omapi_startup_message_0 = module_0.OmapiStartupMessage()
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    var_0 = omapi_startup_message_0.validate()
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    var_1 = omapi_startup_message_0.validate()
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    set_0 = {none_type_0, none_type_0}
    var_2 = omapi_startup_message_0.validate()
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_1 = module_0.OmapiStartupMessage(set_0)
    assert (
        f"{type(omapi_startup_message_0).__module__}.{type(omapi_startup_message_0).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_0.protocol_version == 100
    assert omapi_startup_message_0.header_size == 24
    assert (
        f"{type(omapi_startup_message_1).__module__}.{type(omapi_startup_message_1).__qualname__}"
        == "snippet_81.OmapiStartupMessage"
    )
    assert omapi_startup_message_1.protocol_version == {None}
    assert omapi_startup_message_1.header_size == 24
    assert module_0.OmapiStartupMessage.implemented_protocol_version == 100
    assert module_0.OmapiStartupMessage.implemented_header_size == 24
    omapi_startup_message_1.dump_oneline()
