# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_593 as module_0


def test_case_0():
    bool_0 = True
    none_type_0 = None
    disable_signalling_0 = module_0.DisableSignalling(bool_0, none_type_0)
    assert (
        f"{type(disable_signalling_0).__module__}.{type(disable_signalling_0).__qualname__}"
        == "snippet_593.DisableSignalling"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    disable_signalling_0 = module_0.DisableSignalling(none_type_0, none_type_0)
    assert (
        f"{type(disable_signalling_0).__module__}.{type(disable_signalling_0).__qualname__}"
        == "snippet_593.DisableSignalling"
    )
    disable_signalling_0.__enter__()


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    disable_signalling_0 = module_0.DisableSignalling(set_0, set_0)
    assert (
        f"{type(disable_signalling_0).__module__}.{type(disable_signalling_0).__qualname__}"
        == "snippet_593.DisableSignalling"
    )
    none_type_0 = None
    disable_signalling_1 = module_0.DisableSignalling(set_0, none_type_0)
    assert (
        f"{type(disable_signalling_0).__module__}.{type(disable_signalling_0).__qualname__}"
        == "snippet_593.DisableSignalling"
    )
    assert (
        f"{type(disable_signalling_1).__module__}.{type(disable_signalling_1).__qualname__}"
        == "snippet_593.DisableSignalling"
    )
    disable_signalling_0.__exit__(
        disable_signalling_0, disable_signalling_1, disable_signalling_0
    )
