# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_333 as module_0


def test_case_0():
    none_type_0 = None
    component_result_0 = module_0.ComponentResult(
        none_type_0, none_type_0, none_type_0, none_type_0
    )
    assert (
        f"{type(component_result_0).__module__}.{type(component_result_0).__qualname__}"
        == "snippet_333.ComponentResult"
    )
    assert component_result_0.component_name is None
    assert component_result_0.json_data is None
    assert component_result_0.api_code is None
    assert component_result_0.api_code_description is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "u\n"
    none_type_0 = None
    component_result_0 = module_0.ComponentResult(
        str_0, none_type_0, none_type_0, str_0
    )
    assert (
        f"{type(component_result_0).__module__}.{type(component_result_0).__qualname__}"
        == "snippet_333.ComponentResult"
    )
    assert component_result_0.component_name == "u\n"
    assert component_result_0.json_data is None
    assert component_result_0.api_code is None
    assert component_result_0.api_code_description == "u\n"
    component_result_0.has_error()


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    component_result_0 = module_0.ComponentResult(
        none_type_0, none_type_0, none_type_0, none_type_0
    )
    assert (
        f"{type(component_result_0).__module__}.{type(component_result_0).__qualname__}"
        == "snippet_333.ComponentResult"
    )
    assert component_result_0.component_name is None
    assert component_result_0.json_data is None
    assert component_result_0.api_code is None
    assert component_result_0.api_code_description is None
    var_0 = component_result_0.get_error()
    assert (
        f"{type(component_result_0).__module__}.{type(component_result_0).__qualname__}"
        == "snippet_333.ComponentResult"
    )
    assert component_result_0.component_name is None
    assert component_result_0.json_data is None
    assert component_result_0.api_code is None
    assert component_result_0.api_code_description is None
    var_0.has_error()
