# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_703 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 3356
    module_0.FieldPerm(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    none_type_1 = None
    field_perm_0 = module_0.FieldPerm(none_type_1)
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert module_0.FieldPerm.permissions is None
    field_perm_0.available(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    field_perm_0 = module_0.FieldPerm()
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert module_0.FieldPerm.permissions is None
    field_perm_0.check(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    float_0 = -1113.98962
    bool_1 = False
    dict_0 = {bool_1: bool_1}
    field_perm_0 = module_0.FieldPerm(dict_0)
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert field_perm_0.permissions == {False}
    assert module_0.FieldPerm.permissions is None
    var_0 = field_perm_0.check(float_0)
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert field_perm_0.permissions == {False}
    assert module_0.FieldPerm.permissions is None
    var_0.available(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    tuple_0 = ()
    field_perm_0 = module_0.FieldPerm()
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert module_0.FieldPerm.permissions is None
    field_perm_0.get_perms(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    field_perm_0 = module_0.FieldPerm()
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert module_0.FieldPerm.permissions is None
    var_0 = field_perm_0.__repr__()
    assert var_0 == "FieldPerm(None)"
    assert (
        f"{type(field_perm_0).__module__}.{type(field_perm_0).__qualname__}"
        == "snippet_703.FieldPerm"
    )
    assert module_0.FieldPerm.permissions is None
    field_perm_0.available(var_0)
