# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_500 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    p_d_u_client_listener_0 = module_0.PDUClientListener()
    assert (
        f"{type(p_d_u_client_listener_0).__module__}.{type(p_d_u_client_listener_0).__qualname__}"
        == "snippet_500.PDUClientListener"
    )
    p_d_u_client_listener_0.onSessionReady()


@pytest.mark.xfail(strict=True)
def test_case_1():
    p_d_u_client_listener_0 = module_0.PDUClientListener()
    assert (
        f"{type(p_d_u_client_listener_0).__module__}.{type(p_d_u_client_listener_0).__qualname__}"
        == "snippet_500.PDUClientListener"
    )
    p_d_u_client_listener_0.onReady()


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -2738
    p_d_u_client_listener_0 = module_0.PDUClientListener()
    assert (
        f"{type(p_d_u_client_listener_0).__module__}.{type(p_d_u_client_listener_0).__qualname__}"
        == "snippet_500.PDUClientListener"
    )
    p_d_u_client_listener_0.onUpdate(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\x17\xdc"
    p_d_u_client_listener_0 = module_0.PDUClientListener()
    assert (
        f"{type(p_d_u_client_listener_0).__module__}.{type(p_d_u_client_listener_0).__qualname__}"
        == "snippet_500.PDUClientListener"
    )
    var_0 = p_d_u_client_listener_0.recvDstBltOrder(bytes_0)
    assert (
        f"{type(p_d_u_client_listener_0).__module__}.{type(p_d_u_client_listener_0).__qualname__}"
        == "snippet_500.PDUClientListener"
    )
    var_0.onReady()
