# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_404 as module_0


def test_case_0():
    collection_mixin_0 = module_0.CollectionMixin()
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    collection_mixin_0 = module_0.CollectionMixin()
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
    var_0 = collection_mixin_0.Contains(none_type_0)
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
    var_0.Clear()


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    none_type_0 = None
    collection_mixin_0 = module_0.CollectionMixin()
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
    var_0 = collection_mixin_0.Clear()
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
    var_0.CopyTo(bool_0, none_type_0)


def test_case_3():
    collection_mixin_0 = module_0.CollectionMixin()
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
    none_type_0 = None
    var_0 = collection_mixin_0.CopyTo(collection_mixin_0, none_type_0)
    assert (
        f"{type(collection_mixin_0).__module__}.{type(collection_mixin_0).__qualname__}"
        == "snippet_404.CollectionMixin"
    )
    assert collection_mixin_0.IsSynchronized is False
    assert collection_mixin_0.SyncRoot is None
    assert (
        f"{type(module_0.CollectionMixin.Count).__module__}.{type(module_0.CollectionMixin.Count).__qualname__}"
        == "builtins.property"
    )
