# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_87 as module_0


def test_case_0():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    base_query_0 = module_0.BaseQuery()
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    var_0 = base_query_0.normalize_wait(list_0)
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    base_query_0 = module_0.BaseQuery()
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    base_query_0.normalize_wait(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    base_query_0 = module_0.BaseQuery(*list_0)
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    var_0 = base_query_0.normalize_wait(list_0)
    assert var_0 == 0
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    base_query_1 = module_0.BaseQuery()
    assert (
        f"{type(base_query_0).__module__}.{type(base_query_0).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    assert (
        f"{type(base_query_1).__module__}.{type(base_query_1).__qualname__}"
        == "snippet_87.BaseQuery"
    )
    var_0.normalize_wait(var_0)
