# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_765 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = 'Oz_\x0c:JXo>9"'
    module_0.classproperty(str_0)
