# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_515 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    set_0 = {bool_0, bool_0}
    a_t_f_converter_0 = module_0.ATFConverter()
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True
    a_t_f_converter_0.process(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    list_0 = []
    a_t_f_converter_0 = module_0.ATFConverter()
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True
    list_1 = a_t_f_converter_0.process(list_0)
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True
    a_t_f_converter_1 = module_0.ATFConverter(bool_0)
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True
    assert (
        f"{type(a_t_f_converter_1).__module__}.{type(a_t_f_converter_1).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_1.two_three is False
    a_t_f_converter_1.process(bool_0)


def test_case_2():
    a_t_f_converter_0 = module_0.ATFConverter()
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    a_t_f_converter_0 = module_0.ATFConverter()
    assert (
        f"{type(a_t_f_converter_0).__module__}.{type(a_t_f_converter_0).__qualname__}"
        == "snippet_515.ATFConverter"
    )
    assert a_t_f_converter_0.two_three is True
    a_t_f_converter_0.process(bool_0)
