# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_493 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    graph_0 = module_0.Graph()
    assert (
        f"{type(graph_0).__module__}.{type(graph_0).__qualname__}"
        == "snippet_493.Graph"
    )
    assert graph_0.vertices == []
    assert graph_0.edges == []
    assert graph_0.vertex_map == {}
    graph_0.get_vertex(graph_0)


def test_case_1():
    graph_0 = module_0.Graph()
    assert (
        f"{type(graph_0).__module__}.{type(graph_0).__qualname__}"
        == "snippet_493.Graph"
    )
    assert graph_0.vertices == []
    assert graph_0.edges == []
    assert graph_0.vertex_map == {}
    var_0 = graph_0.to_dict()
    assert (
        f"{type(graph_0).__module__}.{type(graph_0).__qualname__}"
        == "snippet_493.Graph"
    )
    assert graph_0.vertices == []
    assert graph_0.edges == []
    assert graph_0.vertex_map == {}


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    graph_0 = module_0.Graph()
    assert (
        f"{type(graph_0).__module__}.{type(graph_0).__qualname__}"
        == "snippet_493.Graph"
    )
    assert graph_0.vertices == []
    assert graph_0.edges == []
    assert graph_0.vertex_map == {}
    graph_0.add_edge(none_type_0, none_type_0)
