# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_512 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    int_0 = 702
    template_query_generator_0 = module_0.TemplateQueryGenerator(int_0)
    assert (
        f"{type(template_query_generator_0).__module__}.{type(template_query_generator_0).__qualname__}"
        == "snippet_512.TemplateQueryGenerator"
    )
    assert template_query_generator_0.template_finder == 702
    template_query_generator_0.__call__(none_type_0, none_type_0, none_type_0)
