# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_519 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.Cproperties()


def test_case_1():
    bytes_0 = b'"7\xc6^\xcd\x93\xaa\xba[\x8f_\xa5\xfa\x8c$>'
    cproperties_0 = module_0.Cproperties(bytes_0)
    assert (
        f"{type(cproperties_0).__module__}.{type(cproperties_0).__qualname__}"
        == "snippet_519.Cproperties"
    )
    assert cproperties_0.type == "NAF"
    assert cproperties_0.node == b'"7\xc6^\xcd\x93\xaa\xba[\x8f_\xa5\xfa\x8c$>'


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"LD,&w\x9f\xb5\xe0\xff{!A+"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0}
    bool_0 = True
    cproperties_0 = module_0.Cproperties(bool_0)
    assert (
        f"{type(cproperties_0).__module__}.{type(cproperties_0).__qualname__}"
        == "snippet_519.Cproperties"
    )
    assert cproperties_0.type == "NAF"
    assert cproperties_0.node is True
    var_0 = cproperties_0.get_node()
    assert var_0 is True
    assert (
        f"{type(cproperties_0).__module__}.{type(cproperties_0).__qualname__}"
        == "snippet_519.Cproperties"
    )
    assert cproperties_0.type == "NAF"
    assert cproperties_0.node is True
    var_0.add_property(dict_0, bytes_0, dict_0)
