# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_286 as module_0


def test_case_0():
    b_0 = module_0.B()
    assert f"{type(b_0).__module__}.{type(b_0).__qualname__}" == "snippet_286.B"
    assert b_0.bed is True


def test_case_1():
    b_0 = module_0.B()
    assert f"{type(b_0).__module__}.{type(b_0).__qualname__}" == "snippet_286.B"
    assert b_0.bed is True
    var_0 = b_0.bar()
    assert f"{type(b_0).__module__}.{type(b_0).__qualname__}" == "snippet_286.B"
    assert b_0.bed is True
    assert b_0.barred is True
