# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_661 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0}
    none_type_0 = None
    text_wrapper_0 = module_0.TextWrapper(none_type_0, none_type_0)
    assert (
        f"{type(text_wrapper_0).__module__}.{type(text_wrapper_0).__qualname__}"
        == "snippet_661.TextWrapper"
    )
    text_wrapper_0.write(dict_0)
