# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_445 as module_0


def test_case_0():
    float_0 = -759.1940678662788
    abbreviated_step_0 = module_0.abbreviated_step(float_0)
    assert (
        f"{type(abbreviated_step_0).__module__}.{type(abbreviated_step_0).__qualname__}"
        == "snippet_445.abbreviated_step"
    )
    assert abbreviated_step_0.abbr == pytest.approx(
        -759.1940678662788, abs=0.01, rel=0.01
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    abbreviated_step_0 = module_0.abbreviated_step(none_type_0)
    assert (
        f"{type(abbreviated_step_0).__module__}.{type(abbreviated_step_0).__qualname__}"
        == "snippet_445.abbreviated_step"
    )
    assert abbreviated_step_0.abbr is None
    abbreviated_step_0.__repr__()
