# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_67 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    module_0.CaseGroupHandler(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    case_group_handler_0 = module_0.CaseGroupHandler()
    assert (
        f"{type(case_group_handler_0).__module__}.{type(case_group_handler_0).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    bytes_0 = b"1u\xff\x0c'\x19\x12Lcm}\x80\x1b\x0b"
    case_group_handler_1 = module_0.CaseGroupHandler()
    assert (
        f"{type(case_group_handler_0).__module__}.{type(case_group_handler_0).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    assert (
        f"{type(case_group_handler_1).__module__}.{type(case_group_handler_1).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    case_group_handler_1.init_case_group(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    case_group_handler_0 = module_0.CaseGroupHandler()
    assert (
        f"{type(case_group_handler_0).__module__}.{type(case_group_handler_0).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    case_group_handler_0.remove_case_group(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\r\xd4\xf2N\x89\x11X\xe4dF"
    case_group_handler_0 = module_0.CaseGroupHandler()
    assert (
        f"{type(case_group_handler_0).__module__}.{type(case_group_handler_0).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    case_group_handler_0.case_group_label(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "EUj"
    case_group_handler_0 = module_0.CaseGroupHandler()
    assert (
        f"{type(case_group_handler_0).__module__}.{type(case_group_handler_0).__qualname__}"
        == "snippet_67.CaseGroupHandler"
    )
    case_group_handler_0.case_group_update_label(str_0, str_0)
