# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_528 as module_0


def test_case_0():
    pass


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    none_type_0 = None
    json_rpc_endpoint_proxy_0 = module_0._JsonRpcEndpointProxy(
        list_0, none_type_0, list_0, list_0
    )
    assert (
        f"{type(json_rpc_endpoint_proxy_0).__module__}.{type(json_rpc_endpoint_proxy_0).__qualname__}"
        == "snippet_528._JsonRpcEndpointProxy"
    )
    json_rpc_endpoint_proxy_1 = module_0._JsonRpcEndpointProxy(
        list_0, list_0, bool_0, bool_0
    )
    assert (
        f"{type(json_rpc_endpoint_proxy_0).__module__}.{type(json_rpc_endpoint_proxy_0).__qualname__}"
        == "snippet_528._JsonRpcEndpointProxy"
    )
    assert (
        f"{type(json_rpc_endpoint_proxy_1).__module__}.{type(json_rpc_endpoint_proxy_1).__qualname__}"
        == "snippet_528._JsonRpcEndpointProxy"
    )
    json_rpc_endpoint_proxy_1.__getattr__(list_0)
