# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_606 as module_0
import builtins as module_1


def test_case_0():
    set_0 = set()
    spawning_proxy_0 = module_0.SpawningProxy(set_0)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    spawning_proxy_0 = module_0.SpawningProxy(none_type_0)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False
    module_1.object(**spawning_proxy_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "VsR]vWWoX"
    bytes_0 = b"\xf9\x86\xf2\x9b\xdbU"
    dict_0 = {bytes_0: bytes_0}
    none_type_0 = None
    spawning_proxy_0 = module_0.SpawningProxy(none_type_0)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False
    var_0 = spawning_proxy_0.__getattr__(dict_0)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False
    int_0 = -681
    dict_1 = {var_0: int_0, str_0: str_0, bytes_0: none_type_0}
    spawning_proxy_1 = module_0.SpawningProxy(dict_1)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False
    assert (
        f"{type(spawning_proxy_1).__module__}.{type(spawning_proxy_1).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_1.abort_on_error is False
    spawning_proxy_2 = module_0.SpawningProxy(spawning_proxy_1)
    assert (
        f"{type(spawning_proxy_0).__module__}.{type(spawning_proxy_0).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_0.abort_on_error is False
    assert (
        f"{type(spawning_proxy_1).__module__}.{type(spawning_proxy_1).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_1.abort_on_error is False
    assert (
        f"{type(spawning_proxy_2).__module__}.{type(spawning_proxy_2).__qualname__}"
        == "snippet_606.SpawningProxy"
    )
    assert spawning_proxy_2.abort_on_error is False
    module_1.object(**spawning_proxy_2)
