# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_745 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    fastq_entry_0 = module_0.FastqEntry()
    assert (
        f"{type(fastq_entry_0).__module__}.{type(fastq_entry_0).__qualname__}"
        == "snippet_745.FastqEntry"
    )
    assert fastq_entry_0.id is None
    assert fastq_entry_0.description is None
    assert fastq_entry_0.sequence is None
    assert fastq_entry_0.quality is None
    fastq_entry_0.write()


def test_case_1():
    fastq_entry_0 = module_0.FastqEntry()
    assert (
        f"{type(fastq_entry_0).__module__}.{type(fastq_entry_0).__qualname__}"
        == "snippet_745.FastqEntry"
    )
    assert fastq_entry_0.id is None
    assert fastq_entry_0.description is None
    assert fastq_entry_0.sequence is None
    assert fastq_entry_0.quality is None
