# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_221 as module_0


def test_case_0():
    klass_0 = module_0.Klass()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )
    var_0 = klass_0.meth2()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )


def test_case_1():
    klass_0 = module_0.Klass()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )
    var_0 = klass_0.meth1()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )
    var_1 = klass_0.meth2()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )
    var_2 = klass_0.meth1()
    assert (
        f"{type(klass_0).__module__}.{type(klass_0).__qualname__}"
        == "snippet_221.Klass"
    )
