# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_174 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    function_registry_0 = module_0.FunctionRegistry()
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
    var_0 = function_registry_0.register(function_registry_0)
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
    function_registry_0.run()


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    list_0 = [none_type_0]
    function_registry_0 = module_0.FunctionRegistry()
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
    var_0 = function_registry_0.run()
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
    var_0.register(none_type_0, *list_0)


def test_case_2():
    str_0 = ""
    function_registry_0 = module_0.FunctionRegistry()
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
    var_0 = function_registry_0.register(str_0)
    assert (
        f"{type(function_registry_0).__module__}.{type(function_registry_0).__qualname__}"
        == "snippet_174.FunctionRegistry"
    )
