# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_407 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    bit_stream_0 = module_0.BitStream(none_type_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data is None
    assert bit_stream_0.pos == 0
    dict_0 = {bit_stream_0: none_type_0}
    bit_stream_0.readBytes(dict_0)


def test_case_1():
    bytes_0 = b"\x8f\xa32#\xd1\xcd"
    bit_stream_0 = module_0.BitStream(bytes_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\x8f\xa32#\xd1\xcd"
    assert bit_stream_0.pos == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    bit_stream_0 = module_0.BitStream(none_type_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data is None
    assert bit_stream_0.pos == 0
    dict_0 = {bit_stream_0: none_type_0}
    var_0 = bit_stream_0.__repr__()
    assert var_0 == "BitStream(pos=0:0)"
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data is None
    assert bit_stream_0.pos == 0
    bit_stream_0.readBytes(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = '"* _IbJ'
    bit_stream_0 = module_0.BitStream(str_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == '"* _IbJ'
    assert bit_stream_0.pos == 0
    bit_stream_0.peek(str_0)


def test_case_4():
    complex_0 = 221.5 - 1388.6441j
    bytes_0 = b"\xb4F\xc9'"
    bool_0 = True
    bit_stream_0 = module_0.BitStream(bytes_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xb4F\xc9'"
    assert bit_stream_0.pos == 0
    var_0 = bit_stream_0.read(bool_0)
    assert var_0 == 0
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xb4F\xc9'"
    assert bit_stream_0.pos == 1
    bit_stream_1 = module_0.BitStream(var_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xb4F\xc9'"
    assert bit_stream_0.pos == 1
    assert (
        f"{type(bit_stream_1).__module__}.{type(bit_stream_1).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_1.data == 0
    assert bit_stream_1.pos == 0
    var_1 = var_0.__repr__()
    assert var_1 == "0"
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xb4F\xc9'"
    assert bit_stream_0.pos == 1
    assert (
        f"{type(bit_stream_1).__module__}.{type(bit_stream_1).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_1.data == 0
    assert bit_stream_1.pos == 0
    bit_stream_2 = module_0.BitStream(complex_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xb4F\xc9'"
    assert bit_stream_0.pos == 1
    assert (
        f"{type(bit_stream_1).__module__}.{type(bit_stream_1).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_1.data == 0
    assert bit_stream_1.pos == 0
    assert (
        f"{type(bit_stream_2).__module__}.{type(bit_stream_2).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_2.data == (221.5 - 1388.6441j)
    assert bit_stream_2.pos == 0
    with pytest.raises(ValueError):
        bit_stream_0.readBytes(bool_0)


def test_case_5():
    bytes_0 = b"\xe2\x18"
    bool_0 = False
    bit_stream_0 = module_0.BitStream(bytes_0)
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xe2\x18"
    assert bit_stream_0.pos == 0
    int_0 = 137
    var_0 = bit_stream_0.readBytes(int_0)
    assert var_0 == b"\xe2\x18"
    assert (
        f"{type(bit_stream_0).__module__}.{type(bit_stream_0).__qualname__}"
        == "snippet_407.BitStream"
    )
    assert bit_stream_0.data == b"\xe2\x18"
    assert bit_stream_0.pos == 1096
    with pytest.raises(ValueError):
        bit_stream_0.read(bool_0)
