# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_346 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "7ua"
    module_0.InfobloxHost(str_0, password=str_0)
