# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_144 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    none_type_1 = None
    str_0 = "Vof"
    dict_0 = {str_0: none_type_1}
    pipe_0 = module_0.Pipe(none_type_1, **dict_0)
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    pipe_0.__ror__(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "F\x0c8kI3\x0b}:Ky_o~h!"
    dict_0 = {str_0: str_0, str_0: str_0}
    none_type_0 = None
    pipe_0 = module_0.Pipe(none_type_0)
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = pipe_0.__repr__()
    assert var_0 == "Pipe(None)"
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0.__call__(**dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    list_0 = [bool_0]
    tuple_0 = (bool_0, dict_0, list_0)
    none_type_0 = None
    list_1 = [none_type_0, none_type_0]
    pipe_0 = module_0.Pipe(none_type_0, *list_1)
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = pipe_0.__repr__()
    assert var_0 == "Pipe(None, None, None)"
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0.__ror__(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    set_0 = {bool_0, bool_0}
    str_0 = '?J)@dy"I"]'
    dict_0 = {str_0: set_0, str_0: set_0}
    pipe_0 = module_0.Pipe(bool_0, **dict_0)
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = pipe_0.__call__()
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "snippet_144.Pipe"
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    pipe_1 = module_0.Pipe(set_0)
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "snippet_144.Pipe"
    assert (
        f"{type(pipe_1).__module__}.{type(pipe_1).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_1 = pipe_0.__repr__()
    assert var_1 == 'Pipe(True, ?J)@dy"I"]={True})'
    assert (
        f"{type(pipe_0).__module__}.{type(pipe_0).__qualname__}" == "snippet_144.Pipe"
    )
    assert f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "snippet_144.Pipe"
    assert (
        f"{type(pipe_1).__module__}.{type(pipe_1).__qualname__}" == "snippet_144.Pipe"
    )
    assert (
        f"{type(module_0.Pipe.args).__module__}.{type(module_0.Pipe.args).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.callable).__module__}.{type(module_0.Pipe.callable).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.Pipe.kwargs).__module__}.{type(module_0.Pipe.kwargs).__qualname__}"
        == "builtins.member_descriptor"
    )
    pipe_1.__ror__(pipe_1)


def test_case_4():
    pass
