# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_180 as module_0


def test_case_0():
    int_0 = 3095
    blob_argument_wrapper_0 = module_0._BlobArgumentWrapper(int_0)
    assert (
        f"{type(blob_argument_wrapper_0).__module__}.{type(blob_argument_wrapper_0).__qualname__}"
        == "snippet_180._BlobArgumentWrapper"
    )
    assert (
        f"{type(module_0._BlobArgumentWrapper.encoded).__module__}.{type(module_0._BlobArgumentWrapper.encoded).__qualname__}"
        == "builtins.property"
    )
