# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_140 as module_0


def test_case_0():
    none_type_0 = None
    faq_entry_wrapper_0 = module_0.FaqEntryWrapper(none_type_0, none_type_0)
    assert (
        f"{type(faq_entry_wrapper_0).__module__}.{type(faq_entry_wrapper_0).__qualname__}"
        == "snippet_140.FaqEntryWrapper"
    )
    assert faq_entry_wrapper_0.gs is None
    assert faq_entry_wrapper_0.entry is None
    assert (
        f"{type(module_0.FaqEntryWrapper.url).__module__}.{type(module_0.FaqEntryWrapper.url).__qualname__}"
        == "builtins.property"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    dict_0 = {}
    faq_entry_wrapper_0 = module_0.FaqEntryWrapper(dict_0, list_0)
    assert (
        f"{type(faq_entry_wrapper_0).__module__}.{type(faq_entry_wrapper_0).__qualname__}"
        == "snippet_140.FaqEntryWrapper"
    )
    assert faq_entry_wrapper_0.gs == {}
    assert faq_entry_wrapper_0.entry == []
    assert (
        f"{type(module_0.FaqEntryWrapper.url).__module__}.{type(module_0.FaqEntryWrapper.url).__qualname__}"
        == "builtins.property"
    )
    faq_entry_wrapper_0.render()
