# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_126 as module_0


def test_case_0():
    base_entry_channel_0 = module_0.BaseEntryChannel()
    assert (
        f"{type(base_entry_channel_0).__module__}.{type(base_entry_channel_0).__qualname__}"
        == "snippet_126.BaseEntryChannel"
    )
    assert module_0.BaseEntryChannel.query == ""


@pytest.mark.xfail(strict=True)
def test_case_1():
    base_entry_channel_0 = module_0.BaseEntryChannel()
    assert (
        f"{type(base_entry_channel_0).__module__}.{type(base_entry_channel_0).__qualname__}"
        == "snippet_126.BaseEntryChannel"
    )
    assert module_0.BaseEntryChannel.query == ""
    base_entry_channel_0.get_queryset()


@pytest.mark.xfail(strict=True)
def test_case_2():
    base_entry_channel_0 = module_0.BaseEntryChannel()
    assert (
        f"{type(base_entry_channel_0).__module__}.{type(base_entry_channel_0).__qualname__}"
        == "snippet_126.BaseEntryChannel"
    )
    assert module_0.BaseEntryChannel.query == ""
    base_entry_channel_0.get_context_data()
