# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_196 as module_0


def test_case_0():
    bytes_0 = b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    float_0 = -759.193
    seq_pos_0 = module_0.SeqPos(bytes_0, start=bytes_0, stop=float_0)
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    none_type_0 = None
    set_0 = {none_type_0, none_type_0}
    seq_pos_1 = module_0.SeqPos(none_type_0, start=set_0, stop=none_type_0)
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_1).__module__}.{type(seq_pos_1).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_1.line == ""
    assert seq_pos_1.lineno == 1
    assert (
        f"{type(seq_pos_1.col).__module__}.{type(seq_pos_1.col).__qualname__}"
        == "builtins.slice"
    )
    var_0 = seq_pos_1.__str__()
    assert var_0 == "1:0:"
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_1).__module__}.{type(seq_pos_1).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_1.line == ""
    assert seq_pos_1.lineno == 1
    assert (
        f"{type(seq_pos_1.col).__module__}.{type(seq_pos_1.col).__qualname__}"
        == "builtins.slice"
    )
    var_1 = var_0.__str__()
    assert var_1 == "1:0:"
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_1).__module__}.{type(seq_pos_1).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_1.line == ""
    assert seq_pos_1.lineno == 1
    assert (
        f"{type(seq_pos_1.col).__module__}.{type(seq_pos_1.col).__qualname__}"
        == "builtins.slice"
    )
    seq_pos_2 = module_0.SeqPos(var_1, stop=var_1)
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_1).__module__}.{type(seq_pos_1).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_1.line == ""
    assert seq_pos_1.lineno == 1
    assert (
        f"{type(seq_pos_1.col).__module__}.{type(seq_pos_1.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_2).__module__}.{type(seq_pos_2).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_2.line == "1:0:"
    assert seq_pos_2.lineno == 1
    assert (
        f"{type(seq_pos_2.col).__module__}.{type(seq_pos_2.col).__qualname__}"
        == "builtins.slice"
    )
    seq_pos_3 = module_0.SeqPos(lineno=var_0, start=var_0, stop=none_type_0)
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == b"*x,\x9b<\xc3\x81\x05\xb9\xe27"
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_1).__module__}.{type(seq_pos_1).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_1.line == ""
    assert seq_pos_1.lineno == 1
    assert (
        f"{type(seq_pos_1.col).__module__}.{type(seq_pos_1.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_2).__module__}.{type(seq_pos_2).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_2.line == "1:0:"
    assert seq_pos_2.lineno == 1
    assert (
        f"{type(seq_pos_2.col).__module__}.{type(seq_pos_2.col).__qualname__}"
        == "builtins.slice"
    )
    assert (
        f"{type(seq_pos_3).__module__}.{type(seq_pos_3).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_3.line == ""
    assert seq_pos_3.lineno == "1:0:"
    assert (
        f"{type(seq_pos_3.col).__module__}.{type(seq_pos_3.col).__qualname__}"
        == "builtins.slice"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.SeqPos(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    seq_pos_0 = module_0.SeqPos()
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == ""
    assert seq_pos_0.lineno == 1
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    module_0.SeqPos(seq_pos_0)


def test_case_3():
    dict_0 = {}
    seq_pos_0 = module_0.SeqPos(lineno=dict_0)
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == ""
    assert seq_pos_0.lineno == {}
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    var_0 = seq_pos_0.__str__()
    assert var_0 == "{}:0:"
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == ""
    assert seq_pos_0.lineno == {}
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
    var_1 = var_0.__str__()
    assert var_1 == "{}:0:"
    assert (
        f"{type(seq_pos_0).__module__}.{type(seq_pos_0).__qualname__}"
        == "snippet_196.SeqPos"
    )
    assert seq_pos_0.line == ""
    assert seq_pos_0.lineno == {}
    assert (
        f"{type(seq_pos_0.col).__module__}.{type(seq_pos_0.col).__qualname__}"
        == "builtins.slice"
    )
