# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_236 as module_0


def test_case_0():
    complex_0 = -1939.70426 + 1467.189j
    maximal_matches_0 = module_0.MaximalMatches(complex_0)
    assert (
        f"{type(maximal_matches_0).__module__}.{type(maximal_matches_0).__qualname__}"
        == "snippet_236.MaximalMatches"
    )
    assert maximal_matches_0.template_matches == (-1939.70426 + 1467.189j)
    assert maximal_matches_0.max_match_list == []
