# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_428 as module_0


def test_case_0():
    item_getter_0 = module_0.ItemGetter()
    assert (
        f"{type(item_getter_0).__module__}.{type(item_getter_0).__qualname__}"
        == "snippet_428.ItemGetter"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    item_getter_0 = module_0.ItemGetter()
    assert (
        f"{type(item_getter_0).__module__}.{type(item_getter_0).__qualname__}"
        == "snippet_428.ItemGetter"
    )
    item_getter_0.get(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    item_getter_0 = module_0.ItemGetter()
    assert (
        f"{type(item_getter_0).__module__}.{type(item_getter_0).__qualname__}"
        == "snippet_428.ItemGetter"
    )
    var_0 = item_getter_0.to_dict(tuple_0)
    assert (
        f"{type(item_getter_0).__module__}.{type(item_getter_0).__qualname__}"
        == "snippet_428.ItemGetter"
    )
    bool_0 = True
    module_0.ItemGetter(*bool_0)
