# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_108 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    none_type_0 = None
    c_o_r_s_middleware_0 = module_0.CORSMiddleware(none_type_0)
    assert (
        f"{type(c_o_r_s_middleware_0).__module__}.{type(c_o_r_s_middleware_0).__qualname__}"
        == "snippet_108.CORSMiddleware"
    )
    assert c_o_r_s_middleware_0.cors is None
    assert c_o_r_s_middleware_0.default_enabled is True
    c_o_r_s_middleware_0.process_resource(bool_0, bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    c_o_r_s_middleware_0 = module_0.CORSMiddleware(none_type_0, none_type_0)
    assert (
        f"{type(c_o_r_s_middleware_0).__module__}.{type(c_o_r_s_middleware_0).__qualname__}"
        == "snippet_108.CORSMiddleware"
    )
    assert c_o_r_s_middleware_0.cors is None
    assert c_o_r_s_middleware_0.default_enabled is None
    var_0 = c_o_r_s_middleware_0.process_resource(
        none_type_0, c_o_r_s_middleware_0, c_o_r_s_middleware_0
    )
    assert (
        f"{type(c_o_r_s_middleware_0).__module__}.{type(c_o_r_s_middleware_0).__qualname__}"
        == "snippet_108.CORSMiddleware"
    )
    assert c_o_r_s_middleware_0.cors is None
    assert c_o_r_s_middleware_0.default_enabled is None
    var_0.process_resource(none_type_0, none_type_0, c_o_r_s_middleware_0)


def test_case_2():
    complex_0 = -1368.68 + 19.0651j
    c_o_r_s_middleware_0 = module_0.CORSMiddleware(complex_0, complex_0)
    assert (
        f"{type(c_o_r_s_middleware_0).__module__}.{type(c_o_r_s_middleware_0).__qualname__}"
        == "snippet_108.CORSMiddleware"
    )
    assert c_o_r_s_middleware_0.cors == (-1368.68 + 19.0651j)
    assert c_o_r_s_middleware_0.default_enabled == (-1368.68 + 19.0651j)
