# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_622 as module_0


def test_case_0():
    set_0 = set()
    with pytest.raises(AssertionError):
        module_0.GaussianMap(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    gaussian_map_0 = module_0.GaussianMap(list_0)
    assert (
        f"{type(gaussian_map_0).__module__}.{type(gaussian_map_0).__qualname__}"
        == "snippet_622.GaussianMap"
    )
    assert gaussian_map_0.shape == [False, False]
    assert gaussian_map_0.sigma == pytest.approx(0.5, abs=0.01, rel=0.01)
    gaussian_map_0.get_gaussian_weight(list_0)
