# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_483 as module_0


def test_case_0():
    bool_0 = False
    results_0 = module_0.Results(bool_0, bool_0)
    assert (
        f"{type(results_0).__module__}.{type(results_0).__qualname__}"
        == "snippet_483.Results"
    )
    assert results_0.params is False
    assert results_0.model is False
