# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_481 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    set_0 = set()
    format_specification_0 = module_0.FormatSpecification(set_0)
    assert (
        f"{type(format_specification_0).__module__}.{type(format_specification_0).__qualname__}"
        == "snippet_481.FormatSpecification"
    )
    assert format_specification_0.identifier == {*()}
    assert format_specification_0.signatures == []
    format_specification_0.AddNewSignature(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bool_0 = False
    format_specification_0 = module_0.FormatSpecification(bool_0)
    assert (
        f"{type(format_specification_0).__module__}.{type(format_specification_0).__qualname__}"
        == "snippet_481.FormatSpecification"
    )
    assert format_specification_0.identifier is False
    assert format_specification_0.signatures == []
    var_0 = format_specification_0.IsTextFormat()
    assert var_0 is False
    assert (
        f"{type(format_specification_0).__module__}.{type(format_specification_0).__qualname__}"
        == "snippet_481.FormatSpecification"
    )
    assert format_specification_0.identifier is False
    assert format_specification_0.signatures == []
    var_0.AddNewSignature(none_type_0)
