# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import snippet_703 as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    object_0 = module_0.object()
    safe_parser_0 = module_1.SafeParser(object_0)
    assert (
        f"{type(safe_parser_0).__module__}.{type(safe_parser_0).__qualname__}"
        == "snippet_703.SafeParser"
    )
    safe_parser_0.base_classes()


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    safe_parser_0 = module_1.SafeParser(none_type_0)
    assert (
        f"{type(safe_parser_0).__module__}.{type(safe_parser_0).__qualname__}"
        == "snippet_703.SafeParser"
    )
    safe_parser_0.parse()
