# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_603 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    complex_0 = 8025.442 - 285.4j
    module_0.FIOAlerts(complex_0)
