# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_641 as module_0


def test_case_0():
    bool_0 = True
    set_0 = {bool_0, bool_0}
    time_since_last_transaction_0 = module_0.TimeSinceLastTransaction(set_0)
    assert (
        f"{type(time_since_last_transaction_0).__module__}.{type(time_since_last_transaction_0).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(module_0.TimeSinceLastTransaction.seconds).__module__}.{type(module_0.TimeSinceLastTransaction.seconds).__qualname__}"
        == "builtins.property"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    time_since_last_transaction_0 = module_0.TimeSinceLastTransaction(bool_0)
    assert (
        f"{type(time_since_last_transaction_0).__module__}.{type(time_since_last_transaction_0).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(module_0.TimeSinceLastTransaction.seconds).__module__}.{type(module_0.TimeSinceLastTransaction.seconds).__qualname__}"
        == "builtins.property"
    )
    time_since_last_transaction_1 = module_0.TimeSinceLastTransaction(
        time_since_last_transaction_0
    )
    assert (
        f"{type(time_since_last_transaction_0).__module__}.{type(time_since_last_transaction_0).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(time_since_last_transaction_1).__module__}.{type(time_since_last_transaction_1).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(module_0.TimeSinceLastTransaction.seconds).__module__}.{type(module_0.TimeSinceLastTransaction.seconds).__qualname__}"
        == "builtins.property"
    )
    var_0 = time_since_last_transaction_0.__repr__()
    assert var_0 == "TimeSinceLastTransaction(seconds=False)"
    assert (
        f"{type(time_since_last_transaction_0).__module__}.{type(time_since_last_transaction_0).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(time_since_last_transaction_1).__module__}.{type(time_since_last_transaction_1).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(module_0.TimeSinceLastTransaction.seconds).__module__}.{type(module_0.TimeSinceLastTransaction.seconds).__qualname__}"
        == "builtins.property"
    )
    time_since_last_transaction_0.__eq__(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    none_type_1 = None
    time_since_last_transaction_0 = module_0.TimeSinceLastTransaction(none_type_1)
    assert (
        f"{type(time_since_last_transaction_0).__module__}.{type(time_since_last_transaction_0).__qualname__}"
        == "snippet_641.TimeSinceLastTransaction"
    )
    assert (
        f"{type(module_0.TimeSinceLastTransaction.seconds).__module__}.{type(module_0.TimeSinceLastTransaction.seconds).__qualname__}"
        == "builtins.property"
    )
    time_since_last_transaction_0.__eq__(none_type_0)
