# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_737 as module_0


def test_case_0():
    w_i_c_1_t_0 = module_0.WIC_1T()
    assert (
        f"{type(w_i_c_1_t_0).__module__}.{type(w_i_c_1_t_0).__qualname__}"
        == "snippet_737.WIC_1T"
    )
    assert (
        f"{type(module_0.WIC_1T.interfaces).__module__}.{type(module_0.WIC_1T.interfaces).__qualname__}"
        == "builtins.property"
    )


def test_case_1():
    w_i_c_1_t_0 = module_0.WIC_1T()
    assert (
        f"{type(w_i_c_1_t_0).__module__}.{type(w_i_c_1_t_0).__qualname__}"
        == "snippet_737.WIC_1T"
    )
    assert (
        f"{type(module_0.WIC_1T.interfaces).__module__}.{type(module_0.WIC_1T.interfaces).__qualname__}"
        == "builtins.property"
    )
    var_0 = w_i_c_1_t_0.__str__()
    assert var_0 == "WIC-1T"
    assert (
        f"{type(w_i_c_1_t_0).__module__}.{type(w_i_c_1_t_0).__qualname__}"
        == "snippet_737.WIC_1T"
    )
    assert (
        f"{type(module_0.WIC_1T.interfaces).__module__}.{type(module_0.WIC_1T.interfaces).__qualname__}"
        == "builtins.property"
    )
