# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_52 as module_0


def test_case_0():
    none_type_0 = None
    default_string_type_0 = module_0.DefaultStringType(none_type_0, none_type_0)
    assert (
        f"{type(default_string_type_0).__module__}.{type(default_string_type_0).__qualname__}"
        == "snippet_52.DefaultStringType"
    )
    assert default_string_type_0.fn_ansi is None
    assert default_string_type_0.fn_unicode is None
