# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_271 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    panel_metrics_helper_0.special_back_to_front(panel_metrics_helper_0)


def test_case_1():
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    none_type_0 = None
    panel_metrics_helper_1 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_1.special_back_to_front(none_type_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_1 = panel_metrics_helper_1.front_to_back(panel_metrics_helper_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }


@pytest.mark.xfail(strict=True)
def test_case_2():
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    none_type_0 = None
    var_0 = panel_metrics_helper_0.back_to_front(none_type_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    panel_metrics_helper_0.special_back_to_front(panel_metrics_helper_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_0.special_back_to_front(none_type_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    none_type_1 = None
    panel_metrics_helper_1 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_1 = panel_metrics_helper_1.special_front_to_back(none_type_1)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_1.back_to_front(var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    dict_0 = {}
    panel_metrics_helper_1 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    panel_metrics_helper_1.special_front_to_back(dict_0)


def test_case_5():
    str_0 = ""
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_0.special_front_to_back(str_0)
    assert var_0 == "summary:"
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = ":D<gk*<!xfIfl0:\\"
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_0.special_back_to_front(str_0)
    assert var_0 == ":D<gk*<!xfIfl0:\\"
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    panel_metrics_helper_1 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0.front_to_back(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = -1460
    str_0 = "+BG%C./3&P9\r,5SZ"
    panel_metrics_helper_0 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_0.special_front_to_back(str_0)
    assert var_0 == "summary:+BG%C./3&P9\r,5SZ"
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    tuple_0 = (str_0, str_0, int_0, var_0)
    panel_metrics_helper_0.special_front_to_back(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    none_type_0 = None
    dict_0 = {}
    panel_metrics_helper_0 = module_0.PanelMetricsHelper(**dict_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_0 = panel_metrics_helper_0.special_back_to_front(none_type_0)
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    str_0 = "oy_'t`ou*pfHNlIU\"xv"
    dict_1 = {str_0: str_0, str_0: str_0, str_0: str_0}
    panel_metrics_helper_1 = module_0.PanelMetricsHelper()
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_1 = panel_metrics_helper_1.special_front_to_back(str_0)
    assert var_1 == "summary:oy_'t`ou*pfHNlIU\"xv"
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    var_2 = panel_metrics_helper_0.special_back_to_front(var_1)
    assert var_2 == "s::oy_'t`ou*pfHNlIU\"xv"
    assert (
        f"{type(panel_metrics_helper_0).__module__}.{type(panel_metrics_helper_0).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert (
        f"{type(panel_metrics_helper_1).__module__}.{type(panel_metrics_helper_1).__qualname__}"
        == "snippet_271.PanelMetricsHelper"
    )
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING == {
        "Step": "_step",
        "Relative Time (Wall)": "_absolute_runtime",
        "Relative Time (Process)": "_runtime",
        "Wall Time": "_timestamp",
    }
    assert module_0.PanelMetricsHelper.FRONTEND_NAME_MAPPING_REVERSED == {
        "_step": "Step",
        "_absolute_runtime": "Relative Time (Wall)",
        "_runtime": "Relative Time (Process)",
        "_timestamp": "Wall Time",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING == {
        "Created Timestamp": "createdAt",
        "Latest Timestamp": "heartbeatAt",
    }
    assert module_0.PanelMetricsHelper.RUN_MAPPING_REVERSED == {
        "createdAt": "Created Timestamp",
        "heartbeatAt": "Latest Timestamp",
    }
    panel_metrics_helper_1.special_back_to_front(dict_1)
