# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_272 as module_0


def test_case_0():
    none_type_0 = None
    enum_0 = module_0.Enum()
    assert (
        f"{type(enum_0).__module__}.{type(enum_0).__qualname__}" == "snippet_272.Enum"
    )
    assert enum_0.val_map == {}
    var_0 = enum_0.__call__(none_type_0)
    assert var_0 == "Unknown (None)"
    assert (
        f"{type(enum_0).__module__}.{type(enum_0).__qualname__}" == "snippet_272.Enum"
    )
    assert enum_0.val_map == {}
