# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_70 as module_0


def test_case_0():
    complex_0 = -340.109 - 362.07989j
    writer_0 = module_0.Writer(complex_0, complex_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path == (-340.109 - 362.07989j)
    assert writer_0.name == (-340.109 - 362.07989j)
    assert writer_0.rules_section == ["Rules"]


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    writer_0 = module_0.Writer(bool_0, bool_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    writer_1 = module_0.Writer(bool_0, bool_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    assert (
        f"{type(writer_1).__module__}.{type(writer_1).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_1.tool_file_path is False
    assert writer_1.name is False
    assert writer_1.rules_section == ["Rules"]
    int_0 = 1264
    writer_2 = module_0.Writer(int_0, int_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    assert (
        f"{type(writer_1).__module__}.{type(writer_1).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_1.tool_file_path is False
    assert writer_1.name is False
    assert writer_1.rules_section == ["Rules"]
    assert (
        f"{type(writer_2).__module__}.{type(writer_2).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_2.tool_file_path == 1264
    assert writer_2.name == 1264
    assert writer_2.rules_section == ["Rules"]
    none_type_0 = None
    writer_3 = module_0.Writer(none_type_0, none_type_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    assert (
        f"{type(writer_1).__module__}.{type(writer_1).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_1.tool_file_path is False
    assert writer_1.name is False
    assert writer_1.rules_section == ["Rules"]
    assert (
        f"{type(writer_2).__module__}.{type(writer_2).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_2.tool_file_path == 1264
    assert writer_2.name == 1264
    assert writer_2.rules_section == ["Rules"]
    assert (
        f"{type(writer_3).__module__}.{type(writer_3).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_3.tool_file_path is None
    assert writer_3.name is None
    assert writer_3.rules_section == ["Rules"]
    writer_4 = module_0.Writer(none_type_0, none_type_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    assert (
        f"{type(writer_1).__module__}.{type(writer_1).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_1.tool_file_path is False
    assert writer_1.name is False
    assert writer_1.rules_section == ["Rules"]
    assert (
        f"{type(writer_2).__module__}.{type(writer_2).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_2.tool_file_path == 1264
    assert writer_2.name == 1264
    assert writer_2.rules_section == ["Rules"]
    assert (
        f"{type(writer_3).__module__}.{type(writer_3).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_3.tool_file_path is None
    assert writer_3.name is None
    assert writer_3.rules_section == ["Rules"]
    assert (
        f"{type(writer_4).__module__}.{type(writer_4).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_4.tool_file_path is None
    assert writer_4.name is None
    assert writer_4.rules_section == ["Rules"]
    writer_0.AddCustomBuildRule(
        writer_4, bool_0, writer_0, none_type_0, writer_3, writer_2
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    writer_0 = module_0.Writer(bool_0, bool_0)
    assert (
        f"{type(writer_0).__module__}.{type(writer_0).__qualname__}"
        == "snippet_70.Writer"
    )
    assert writer_0.tool_file_path is False
    assert writer_0.name is False
    assert writer_0.rules_section == ["Rules"]
    writer_0.WriteIfChanged()
