# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_537 as module_0


def test_case_0():
    str_0 = ""
    list_0 = [str_0, str_0, str_0]
    interactive_query_0 = module_0.InteractiveQuery(str_0, *list_0)
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == [("", True), ("", True)]
    interactive_query_1 = module_0.InteractiveQuery()
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == [("", True), ("", True)]
    assert (
        f"{type(interactive_query_1).__module__}.{type(interactive_query_1).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_1.name == ""
    assert interactive_query_1.instructions == ""
    assert interactive_query_1.prompts == []
    var_0 = interactive_query_1.add_prompt(interactive_query_1)
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == [("", True), ("", True)]
    assert (
        f"{type(interactive_query_1).__module__}.{type(interactive_query_1).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_1.name == ""
    assert interactive_query_1.instructions == ""
    assert (
        f"{type(interactive_query_1.prompts).__module__}.{type(interactive_query_1.prompts).__qualname__}"
        == "builtins.list"
    )
    assert len(interactive_query_1.prompts) == 1
    list_1 = []
    interactive_query_2 = module_0.InteractiveQuery(*list_1)
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == [("", True), ("", True)]
    assert (
        f"{type(interactive_query_1).__module__}.{type(interactive_query_1).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_1.name == ""
    assert interactive_query_1.instructions == ""
    assert (
        f"{type(interactive_query_1.prompts).__module__}.{type(interactive_query_1.prompts).__qualname__}"
        == "builtins.list"
    )
    assert len(interactive_query_1.prompts) == 1
    assert (
        f"{type(interactive_query_2).__module__}.{type(interactive_query_2).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_2.name == ""
    assert interactive_query_2.instructions == ""
    assert interactive_query_2.prompts == []


def test_case_1():
    interactive_query_0 = module_0.InteractiveQuery()
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == []


@pytest.mark.xfail(strict=True)
def test_case_2():
    interactive_query_0 = module_0.InteractiveQuery()
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert interactive_query_0.prompts == []
    var_0 = interactive_query_0.add_prompt(interactive_query_0)
    assert (
        f"{type(interactive_query_0).__module__}.{type(interactive_query_0).__qualname__}"
        == "snippet_537.InteractiveQuery"
    )
    assert interactive_query_0.name == ""
    assert interactive_query_0.instructions == ""
    assert (
        f"{type(interactive_query_0.prompts).__module__}.{type(interactive_query_0.prompts).__qualname__}"
        == "builtins.list"
    )
    assert len(interactive_query_0.prompts) == 1
    var_0.add_prompt(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"+\xa0|x\x16"
    module_0.InteractiveQuery(*bytes_0)
