# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_474 as module_0


def test_case_0():
    complex_0 = -1939.70426 + 1467.189j
    fruit_0 = module_0.Fruit(complex_0)
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_474.Fruit"
    )
    assert fruit_0.vitamins == (-1939.70426 + 1467.189j)


def test_case_1():
    str_0 = "!p3<CXiPOXn"
    fruit_0 = module_0.Fruit(str_0)
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_474.Fruit"
    )
    assert fruit_0.vitamins == "!p3<CXiPOXn"
    var_0 = fruit_0.antioxidants()
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_474.Fruit"
    )
    assert fruit_0.vitamins == "!p3<CXiPOXn"
