# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_312 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0}
    fixerio_0 = module_0.Fixerio(set_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_0.access_key == {False}
    assert fixerio_0.symbols is None
    none_type_0 = None
    fixerio_1 = module_0.Fixerio(none_type_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_0.access_key == {False}
    assert fixerio_0.symbols is None
    assert (
        f"{type(fixerio_1).__module__}.{type(fixerio_1).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_1.access_key is None
    assert fixerio_1.symbols is None
    fixerio_2 = module_0.Fixerio(none_type_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_0.access_key == {False}
    assert fixerio_0.symbols is None
    assert (
        f"{type(fixerio_1).__module__}.{type(fixerio_1).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_1.access_key is None
    assert fixerio_1.symbols is None
    assert (
        f"{type(fixerio_2).__module__}.{type(fixerio_2).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_2.access_key is None
    assert fixerio_2.symbols is None
    fixerio_3 = module_0.Fixerio(none_type_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_0.access_key == {False}
    assert fixerio_0.symbols is None
    assert (
        f"{type(fixerio_1).__module__}.{type(fixerio_1).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_1.access_key is None
    assert fixerio_1.symbols is None
    assert (
        f"{type(fixerio_2).__module__}.{type(fixerio_2).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_2.access_key is None
    assert fixerio_2.symbols is None
    assert (
        f"{type(fixerio_3).__module__}.{type(fixerio_3).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_3.access_key is None
    assert fixerio_3.symbols is None
    fixerio_3.latest(fixerio_3)


@pytest.mark.xfail(strict=True)
def test_case_1():
    object_0 = module_1.object()
    fixerio_0 = module_0.Fixerio(object_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert (
        f"{type(fixerio_0.access_key).__module__}.{type(fixerio_0.access_key).__qualname__}"
        == "builtins.object"
    )
    assert fixerio_0.symbols is None
    fixerio_0.latest()


def test_case_2():
    bytes_0 = b'D"J\x05\x8b\x19\xdf\xe8'
    fixerio_0 = module_0.Fixerio(bytes_0)
    assert (
        f"{type(fixerio_0).__module__}.{type(fixerio_0).__qualname__}"
        == "snippet_312.Fixerio"
    )
    assert fixerio_0.access_key == b'D"J\x05\x8b\x19\xdf\xe8'
    assert fixerio_0.symbols is None
