# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_518 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "* _IbJ"
    a_c_c_e_s_s__m_a_s_k_0 = module_0.ACCESS_MASK(str_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask == "* _IbJ"
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8
    a_c_c_e_s_s__m_a_s_k_0.__repr__()


def test_case_1():
    bytes_0 = b"\x8f\xa32#\xd1\xcd"
    a_c_c_e_s_s__m_a_s_k_0 = module_0.ACCESS_MASK(bytes_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask == b"\x8f\xa32#\xd1\xcd"
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = '"* _IbJ'
    a_c_c_e_s_s__m_a_s_k_0 = module_0.ACCESS_MASK(str_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask == '"* _IbJ'
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8
    a_c_c_e_s_s__m_a_s_k_0.has_priv(str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -1162
    a_c_c_e_s_s__m_a_s_k_0 = module_0.ACCESS_MASK(int_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask == -1162
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8
    var_0 = a_c_c_e_s_s__m_a_s_k_0.set_priv(int_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask == -1162
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8
    var_0.remove_priv(int_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    a_c_c_e_s_s__m_a_s_k_0 = module_0.ACCESS_MASK(none_type_0)
    assert (
        f"{type(a_c_c_e_s_s__m_a_s_k_0).__module__}.{type(a_c_c_e_s_s__m_a_s_k_0).__qualname__}"
        == "snippet_518.ACCESS_MASK"
    )
    assert a_c_c_e_s_s__m_a_s_k_0.mask is None
    assert module_0.ACCESS_MASK.SET_GENERIC_READ == 2147483648
    assert module_0.ACCESS_MASK.SET_GENERIC_WRITE == 67108864
    assert module_0.ACCESS_MASK.SET_GENERIC_EXECUTE == 536870912
    assert module_0.ACCESS_MASK.SET_GENERIC_ALL == 268435456
    assert module_0.ACCESS_MASK.GENERIC_READ == 131220
    assert module_0.ACCESS_MASK.GENERIC_WRITE == 131112
    assert module_0.ACCESS_MASK.GENERIC_EXECUTE == 131076
    assert module_0.ACCESS_MASK.GENERIC_ALL == 983551
    assert module_0.ACCESS_MASK.MAXIMUM_ALLOWED == 33554432
    assert module_0.ACCESS_MASK.ACCESS_SYSTEM_SECURITY == 16777216
    assert module_0.ACCESS_MASK.SYNCHRONIZE == 1048576
    assert module_0.ACCESS_MASK.WRITE_OWNER == 524288
    assert module_0.ACCESS_MASK.WRITE_DACL == 262144
    assert module_0.ACCESS_MASK.READ_CONTROL == 131072
    assert module_0.ACCESS_MASK.DELETE == 65536
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CONTROL_ACCESS == 256
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_CREATE_CHILD == 1
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_DELETE_CHILD == 2
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_READ_PROP == 16
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_WRITE_PROP == 32
    assert module_0.ACCESS_MASK.ADS_RIGHT_DS_SELF == 8
    a_c_c_e_s_s__m_a_s_k_0.remove_priv(none_type_0)
