# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_119 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "(A<G*Gr%{?(;,|yd'"
    module_0.FileDownloader(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    module_0.FileDownloader(str_0)
