# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_663 as module_0


def test_case_0():
    numerical_0 = module_0.Numerical()
    assert (
        f"{type(numerical_0).__module__}.{type(numerical_0).__qualname__}"
        == "snippet_663.Numerical"
    )
    assert (
        f"{type(module_0.Numerical.log).__module__}.{type(module_0.Numerical.log).__qualname__}"
        == "builtins.property"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    numerical_0 = module_0.Numerical()
    assert (
        f"{type(numerical_0).__module__}.{type(numerical_0).__qualname__}"
        == "snippet_663.Numerical"
    )
    assert (
        f"{type(module_0.Numerical.log).__module__}.{type(module_0.Numerical.log).__qualname__}"
        == "builtins.property"
    )
    numerical_0.slice_naive(numerical_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    numerical_0 = module_0.Numerical()
    assert (
        f"{type(numerical_0).__module__}.{type(numerical_0).__qualname__}"
        == "snippet_663.Numerical"
    )
    assert (
        f"{type(module_0.Numerical.log).__module__}.{type(module_0.Numerical.log).__qualname__}"
        == "builtins.property"
    )
    numerical_0.__str__()
