# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_152 as module_0


def test_case_0():
    validation_error_builder_0 = module_0.ValidationErrorBuilder()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None
    var_0 = validation_error_builder_0.raise_errors()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None


def test_case_1():
    validation_error_builder_0 = module_0.ValidationErrorBuilder()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None


@pytest.mark.xfail(strict=True)
def test_case_2():
    validation_error_builder_0 = module_0.ValidationErrorBuilder()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None
    var_0 = validation_error_builder_0.raise_errors()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None
    validation_error_builder_1 = module_0.ValidationErrorBuilder()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None
    assert (
        f"{type(validation_error_builder_1).__module__}.{type(validation_error_builder_1).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_1.errors is None
    validation_error_builder_1.add_error(
        validation_error_builder_0, validation_error_builder_0
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    validation_error_builder_0 = module_0.ValidationErrorBuilder()
    assert (
        f"{type(validation_error_builder_0).__module__}.{type(validation_error_builder_0).__qualname__}"
        == "snippet_152.ValidationErrorBuilder"
    )
    assert validation_error_builder_0.errors is None
    validation_error_builder_0.add_errors(validation_error_builder_0)
