# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_426 as module_0


def test_case_0():
    fruit_0 = module_0.Fruit()
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_426.Fruit"
    )
    assert module_0.Fruit.FRUITS == {"apple": "red", "orange": "orange"}
    var_0 = fruit_0.print()
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_426.Fruit"
    )
    assert module_0.Fruit.FRUITS == {"apple": "red", "orange": "orange"}


def test_case_1():
    fruit_0 = module_0.Fruit()
    assert (
        f"{type(fruit_0).__module__}.{type(fruit_0).__qualname__}"
        == "snippet_426.Fruit"
    )
    assert module_0.Fruit.FRUITS == {"apple": "red", "orange": "orange"}
