# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_616 as module_0
import builtins as module_1


def test_case_0():
    with pytest.raises(AttributeError):
        module_0.BlacklistEntry()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.BlacklistEntry(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    none_type_0 = None
    module_0.BlacklistEntry(version=bool_0, operator=none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    object_0 = module_1.object()
    module_0.BlacklistEntry(object_0, object_0, object_0)
