# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_623 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    enum_value_generator_0 = module_0.EnumValueGenerator()
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_0 = enum_value_generator_0.reset(enum_value_generator_0)
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_1 = enum_value_generator_0.reset()
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_1.next()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    set_0 = {bool_0, bool_0, bool_0}
    tuple_0 = (set_0,)
    enum_value_generator_0 = module_0.EnumValueGenerator()
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_0 = enum_value_generator_0.__repr__()
    assert var_0 == "EnumValueGenerator(1)"
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_1 = enum_value_generator_0.__call__()
    assert var_1 == 1
    assert (
        f"{type(enum_value_generator_0).__module__}.{type(enum_value_generator_0).__qualname__}"
        == "snippet_623.EnumValueGenerator"
    )
    var_1.reset(tuple_0)
