# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_405 as module_0


def test_case_0():
    event_0 = module_0.Event()
    assert (
        f"{type(event_0).__module__}.{type(event_0).__qualname__}"
        == "snippet_405.Event"
    )
    assert event_0.start_mark is None
    assert event_0.end_mark is None
    var_0 = event_0.__repr__()
    assert var_0 == "Event()"
    assert (
        f"{type(event_0).__module__}.{type(event_0).__qualname__}"
        == "snippet_405.Event"
    )
    assert event_0.start_mark is None
    assert event_0.end_mark is None
