# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_288 as module_0


def test_case_0():
    broadcast_mixin_0 = module_0.BroadcastMixin()
    assert (
        f"{type(broadcast_mixin_0).__module__}.{type(broadcast_mixin_0).__qualname__}"
        == "snippet_288.BroadcastMixin"
    )
