# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_103 as module_0


def test_case_0():
    coin_0 = module_0.Coin()
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ""
    var_0 = coin_0.__str__()
    assert var_0 == "Coin: [/] - "
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ""
    var_1 = var_0.__repr__()
    assert var_1 == "'Coin: [/] - '"
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ""


def test_case_1():
    tuple_0 = ()
    coin_0 = module_0.Coin(volume_btc=tuple_0)
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    var_0 = coin_0.__repr__()
    assert var_0 == "Coin"
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    var_1 = var_0.__str__()
    assert var_1 == "Coin"
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    var_2 = var_1.__repr__()
    assert var_2 == "'Coin'"
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    coin_1 = module_0.Coin()
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    assert (
        f"{type(coin_1).__module__}.{type(coin_1).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_1.id == ""
    assert coin_1.name == ""
    assert coin_1.website == ""
    assert coin_1.price_btc == ""
    assert coin_1.volume_btc == ""
    var_3 = coin_1.__str__()
    assert var_3 == "Coin: [/] - "
    assert (
        f"{type(coin_0).__module__}.{type(coin_0).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_0.id == ""
    assert coin_0.name == ""
    assert coin_0.website == ""
    assert coin_0.price_btc == ""
    assert coin_0.volume_btc == ()
    assert (
        f"{type(coin_1).__module__}.{type(coin_1).__qualname__}" == "snippet_103.Coin"
    )
    assert coin_1.id == ""
    assert coin_1.name == ""
    assert coin_1.website == ""
    assert coin_1.price_btc == ""
    assert coin_1.volume_btc == ""
