# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_593 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xa0\xb5d1\x92\xbf1]r)\xb3\x95\xbb\x9eN.\xb5\x97\xa2"
    set_0 = {bytes_0, bytes_0, bytes_0}
    list_0 = [set_0, bytes_0]
    client_0 = module_0.Client(list_0)
    assert (
        f"{type(client_0).__module__}.{type(client_0).__qualname__}"
        == "snippet_593.Client"
    )
    assert client_0.endpoint == [
        {b"\xa0\xb5d1\x92\xbf1]r)\xb3\x95\xbb\x9eN.\xb5\x97\xa2"},
        b"\xa0\xb5d1\x92\xbf1]r)\xb3\x95\xbb\x9eN.\xb5\x97\xa2",
    ]
    module_0.Client()


@pytest.mark.xfail(strict=True)
def test_case_1():
    module_0.Client()
