# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_672 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 3695
    bytes_0 = b"\x15\t\x93\xeb\x0c\x0f\x8c\x93+\x0f\xee\xbe\x12\xbb\xb0\x0b\x00J"
    set_0 = {int_0, bytes_0}
    association_rules_iterator_0 = module_0.AssociationRulesIterator(set_0)
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {
        b"\x15\t\x93\xeb\x0c\x0f\x8c\x93+\x0f\xee\xbe\x12\xbb\xb0\x0b\x00J",
        3695,
    }
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 2
    association_rules_iterator_0.__next__()


def test_case_1():
    dict_0 = {}
    association_rules_iterator_0 = module_0.AssociationRulesIterator(dict_0)
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    var_0 = association_rules_iterator_0.__iter__()
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {}
    assert var_0.index == 0
    assert var_0.length == 0
    association_rules_iterator_1 = module_0.AssociationRulesIterator(dict_0)
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {}
    assert var_0.index == 0
    assert var_0.length == 0
    assert (
        f"{type(association_rules_iterator_1).__module__}.{type(association_rules_iterator_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_1.rules == {}
    assert association_rules_iterator_1.index == 0
    assert association_rules_iterator_1.length == 0
    association_rules_iterator_2 = module_0.AssociationRulesIterator(dict_0)
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {}
    assert var_0.index == 0
    assert var_0.length == 0
    assert (
        f"{type(association_rules_iterator_1).__module__}.{type(association_rules_iterator_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_1.rules == {}
    assert association_rules_iterator_1.index == 0
    assert association_rules_iterator_1.length == 0
    assert (
        f"{type(association_rules_iterator_2).__module__}.{type(association_rules_iterator_2).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_2.rules == {}
    assert association_rules_iterator_2.index == 0
    assert association_rules_iterator_2.length == 0
    var_1 = var_0.__iter__()
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {}
    assert var_0.index == 0
    assert var_0.length == 0
    assert (
        f"{type(association_rules_iterator_1).__module__}.{type(association_rules_iterator_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_1.rules == {}
    assert association_rules_iterator_1.index == 0
    assert association_rules_iterator_1.length == 0
    assert (
        f"{type(association_rules_iterator_2).__module__}.{type(association_rules_iterator_2).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_2.rules == {}
    assert association_rules_iterator_2.index == 0
    assert association_rules_iterator_2.length == 0
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_1.rules == {}
    assert var_1.index == 0
    assert var_1.length == 0
    var_2 = association_rules_iterator_1.__iter__()
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 0
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {}
    assert var_0.index == 0
    assert var_0.length == 0
    assert (
        f"{type(association_rules_iterator_1).__module__}.{type(association_rules_iterator_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_1.rules == {}
    assert association_rules_iterator_1.index == 0
    assert association_rules_iterator_1.length == 0
    assert (
        f"{type(association_rules_iterator_2).__module__}.{type(association_rules_iterator_2).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_2.rules == {}
    assert association_rules_iterator_2.index == 0
    assert association_rules_iterator_2.length == 0
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_1.rules == {}
    assert var_1.index == 0
    assert var_1.length == 0
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_2.rules == {}
    assert var_2.index == 0
    assert var_2.length == 0
    with pytest.raises(StopIteration):
        association_rules_iterator_1.__next__()


@pytest.mark.xfail(strict=True)
def test_case_2():
    object_0 = module_1.object()
    module_0.AssociationRulesIterator(object_0)


def test_case_3():
    bool_0 = False
    set_0 = {bool_0, bool_0}
    association_rules_iterator_0 = module_0.AssociationRulesIterator(set_0)
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {False}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 1
    var_0 = association_rules_iterator_0.__iter__()
    assert (
        f"{type(association_rules_iterator_0).__module__}.{type(association_rules_iterator_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert association_rules_iterator_0.rules == {False}
    assert association_rules_iterator_0.index == 0
    assert association_rules_iterator_0.length == 1
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_672.AssociationRulesIterator"
    )
    assert var_0.rules == {False}
    assert var_0.index == 0
    assert var_0.length == 1
