# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_611 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    clock_0 = module_0._Clock(**dict_0)
    assert (
        f"{type(clock_0).__module__}.{type(clock_0).__qualname__}"
        == "snippet_611._Clock"
    )
    clock_0.now()


@pytest.mark.xfail(strict=True)
def test_case_1():
    clock_0 = module_0._Clock()
    assert (
        f"{type(clock_0).__module__}.{type(clock_0).__qualname__}"
        == "snippet_611._Clock"
    )
    none_type_0 = None
    clock_0.sleep(none_type_0)
