# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_278 as module_0


def test_case_0():
    int_0 = 3095
    base_api_0 = module_0.BaseApi(int_0)
    assert (
        f"{type(base_api_0).__module__}.{type(base_api_0).__qualname__}"
        == "snippet_278.BaseApi"
    )
    assert base_api_0.endpoint == ""
