# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_483 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    none_type_0 = None
    linter_output_0 = module_0.LinterOutput(none_type_0, none_type_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_0 = linter_output_0.__lt__(bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_1 = var_0.__str__()
    assert var_1 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_2 = var_1.__lt__(bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_3 = var_2.__lt__(bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_4 = linter_output_0.__lt__(var_1)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_5 = var_3.__lt__(bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    var_6 = var_5.__lt__(bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    module_0.LinterOutput(bool_0, bool_0, var_6, col=var_5)


def test_case_1():
    object_0 = module_1.object()
    var_0 = object_0.__str__()
    bool_0 = False
    var_1 = var_0.__lt__(object_0)
    linter_output_0 = module_0.LinterOutput(bool_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is False
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is False
    assert linter_output_0.col is None
    var_2 = linter_output_0.__lt__(object_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is False
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is False
    assert linter_output_0.col is None


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 2331
    linter_output_0 = module_0.LinterOutput(int_0, int_0, int_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path == 2331
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg == 2331
    assert linter_output_0.col is None
    var_0 = linter_output_0.__lt__(linter_output_0)
    assert var_0 is False
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path == 2331
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg == 2331
    assert linter_output_0.col is None
    var_1 = linter_output_0.__lt__(int_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path == 2331
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg == 2331
    assert linter_output_0.col is None
    module_0.LinterOutput(int_0, int_0, int_0, var_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    module_1.object(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    none_type_1 = None
    str_0 = "B:mE$]E"
    linter_output_0 = module_0.LinterOutput(str_0, none_type_0, none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    var_0 = linter_output_0.__str__()
    assert var_0 == "None|None:None|None [B:mE$]E]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    var_1 = linter_output_0.__lt__(linter_output_0)
    assert var_1 is False
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is None
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    bytes_0 = b"\x03\xf9\xf3\xc6J5'\x02\xfa_g\x8d\x1a\xb2\xe2\xa2\xee0"
    module_0.LinterOutput(var_0, none_type_0, none_type_1, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    bool_0 = True
    linter_output_0 = module_0.LinterOutput(
        none_type_0, bool_0, none_type_0, col=none_type_0
    )
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    linter_output_1 = module_0.LinterOutput(none_type_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    var_0 = linter_output_1.__str__()
    assert var_0 == "True|None:None|True [None]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    var_1 = linter_output_1.__lt__(none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    list_0 = []
    int_0 = 452
    var_2 = linter_output_1.__lt__(none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    linter_output_2 = module_0.LinterOutput(bool_0, list_0, int_0, col=bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    linter_output_3 = module_0.LinterOutput(bool_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    linter_output_4 = module_0.LinterOutput(none_type_0, int_0, var_0, col=none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    var_3 = linter_output_3.__str__()
    assert var_3 == "True|None:None|True [True]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    var_4 = var_1.__str__()
    assert var_4 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    var_5 = var_1.__str__()
    assert var_5 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    linter_output_5 = module_0.LinterOutput(
        linter_output_2, linter_output_2, list_0, col=int_0
    )
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_6 = linter_output_5.__str__()
    assert var_6 == "[]|None:1|452 [True]|None:452|[] [[]|None:1|452 [True]]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_7 = linter_output_2.__str__()
    assert var_7 == "[]|None:1|452 [True]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_8 = linter_output_0.__str__()
    assert var_8 == "True|None:None|None [None]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_9 = linter_output_4.__lt__(linter_output_4)
    assert var_9 is False
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_10 = var_6.__lt__(linter_output_5)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_11 = linter_output_1.__str__()
    assert var_11 == "True|None:None|True [None]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    var_12 = var_4.__str__()
    assert var_12 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    linter_output_6 = module_0.LinterOutput(var_2, var_12, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr is None
    assert linter_output_0.msg is None
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is True
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path == []
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg == 452
    assert linter_output_2.col == 1
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path is True
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col is None
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path == 452
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg == "True|None:None|True [None]"
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == []
    assert linter_output_5.col == 452
    assert (
        f"{type(linter_output_6).__module__}.{type(linter_output_6).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_6.path == "NotImplemented"
    assert linter_output_6.line_nr is None
    assert linter_output_6.msg is True
    assert linter_output_6.col is None
    linter_output_5.__lt__(linter_output_1)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    bool_0 = True
    linter_output_0 = module_0.LinterOutput(bool_0, bool_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    linter_output_1 = module_0.LinterOutput(
        none_type_0, bool_0, none_type_0, col=none_type_0
    )
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    linter_output_2 = module_0.LinterOutput(none_type_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    var_0 = linter_output_0.__lt__(linter_output_1)
    assert var_0 is False
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    var_1 = linter_output_2.__str__()
    assert var_1 == "True|None:None|True [None]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    var_2 = linter_output_2.__lt__(none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    list_0 = []
    var_3 = linter_output_2.__lt__(none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    linter_output_3 = module_0.LinterOutput(bool_0, list_0, bool_0, col=bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    linter_output_4 = module_0.LinterOutput(bool_0, bool_0, bool_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path is True
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg is True
    assert linter_output_4.col is None
    linter_output_5 = module_0.LinterOutput(none_type_0, var_3, var_1, col=none_type_0)
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path is True
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg is True
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "builtins.NotImplementedType"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == "True|None:None|True [None]"
    assert linter_output_5.col is None
    var_4 = linter_output_4.__str__()
    assert var_4 == "True|None:None|True [True]"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path is True
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg is True
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "builtins.NotImplementedType"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == "True|None:None|True [None]"
    assert linter_output_5.col is None
    var_5 = var_2.__str__()
    assert var_5 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path is True
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg is True
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "builtins.NotImplementedType"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == "True|None:None|True [None]"
    assert linter_output_5.col is None
    var_6 = var_2.__str__()
    assert var_6 == "NotImplemented"
    assert (
        f"{type(linter_output_0).__module__}.{type(linter_output_0).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_0.path is True
    assert linter_output_0.line_nr == 1
    assert linter_output_0.msg is True
    assert linter_output_0.col is None
    assert (
        f"{type(linter_output_1).__module__}.{type(linter_output_1).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_1.path is True
    assert linter_output_1.line_nr is None
    assert linter_output_1.msg is None
    assert linter_output_1.col is None
    assert (
        f"{type(linter_output_2).__module__}.{type(linter_output_2).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_2.path is True
    assert linter_output_2.line_nr is None
    assert linter_output_2.msg is True
    assert linter_output_2.col is None
    assert (
        f"{type(linter_output_3).__module__}.{type(linter_output_3).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_3.path == []
    assert linter_output_3.line_nr is None
    assert linter_output_3.msg is True
    assert linter_output_3.col == 1
    assert (
        f"{type(linter_output_4).__module__}.{type(linter_output_4).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert linter_output_4.path is True
    assert linter_output_4.line_nr is None
    assert linter_output_4.msg is True
    assert linter_output_4.col is None
    assert (
        f"{type(linter_output_5).__module__}.{type(linter_output_5).__qualname__}"
        == "snippet_483.LinterOutput"
    )
    assert (
        f"{type(linter_output_5.path).__module__}.{type(linter_output_5.path).__qualname__}"
        == "builtins.NotImplementedType"
    )
    assert linter_output_5.line_nr is None
    assert linter_output_5.msg == "True|None:None|True [None]"
    assert linter_output_5.col is None
    module_0.LinterOutput(linter_output_3, linter_output_3, list_0, col=var_6)
