# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_428 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    group_by_setup_0 = module_0.GroupBySetup()
    assert (
        f"{type(group_by_setup_0).__module__}.{type(group_by_setup_0).__qualname__}"
        == "snippet_428.GroupBySetup"
    )
    assert module_0.GroupBySetup.pretty_name == "Groupby benchmarks - H2O inspired"
    assert module_0.GroupBySetup.version == "1"
    assert module_0.GroupBySetup.params == ([10000000, 50000000, 100000000],)
    assert module_0.GroupBySetup.param_names == ["N"]
    group_by_setup_0.setup_cache()


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    group_by_setup_0 = module_0.GroupBySetup()
    assert (
        f"{type(group_by_setup_0).__module__}.{type(group_by_setup_0).__qualname__}"
        == "snippet_428.GroupBySetup"
    )
    assert module_0.GroupBySetup.pretty_name == "Groupby benchmarks - H2O inspired"
    assert module_0.GroupBySetup.version == "1"
    assert module_0.GroupBySetup.params == ([10000000, 50000000, 100000000],)
    assert module_0.GroupBySetup.param_names == ["N"]
    group_by_setup_0.setup(dict_0)
