# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_523 as module_0


def test_case_0():
    connection_conditions_0 = module_0.ConnectionConditions()
    assert (
        f"{type(connection_conditions_0).__module__}.{type(connection_conditions_0).__qualname__}"
        == "snippet_523.ConnectionConditions"
    )
    assert connection_conditions_0.fields == ()
    assert connection_conditions_0.wait is False
    assert connection_conditions_0.fail_code == "503"
    assert connection_conditions_0.fail_info is None
    assert module_0.ConnectionConditions.user_required == (
        "user",
        "no user (use USER firstly)",
    )
    assert module_0.ConnectionConditions.login_required == ("logged", "not logged in")
    assert module_0.ConnectionConditions.passive_server_started == (
        "passive_server",
        "no listen socket created (use PASV firstly)",
    )
    assert module_0.ConnectionConditions.data_connection_made == (
        "data_connection",
        "no data connection made",
    )
    assert module_0.ConnectionConditions.rename_from_required == (
        "rename_from",
        "no filename (use RNFR firstly)",
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    connection_conditions_0 = module_0.ConnectionConditions(wait=bool_0)
    assert (
        f"{type(connection_conditions_0).__module__}.{type(connection_conditions_0).__qualname__}"
        == "snippet_523.ConnectionConditions"
    )
    assert connection_conditions_0.fields == ()
    assert connection_conditions_0.wait is True
    assert connection_conditions_0.fail_code == "503"
    assert connection_conditions_0.fail_info is None
    assert module_0.ConnectionConditions.user_required == (
        "user",
        "no user (use USER firstly)",
    )
    assert module_0.ConnectionConditions.login_required == ("logged", "not logged in")
    assert module_0.ConnectionConditions.passive_server_started == (
        "passive_server",
        "no listen socket created (use PASV firstly)",
    )
    assert module_0.ConnectionConditions.data_connection_made == (
        "data_connection",
        "no data connection made",
    )
    assert module_0.ConnectionConditions.rename_from_required == (
        "rename_from",
        "no filename (use RNFR firstly)",
    )
    connection_conditions_0.__call__(bool_0)
