# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_368 as module_0


def test_case_0():
    none_type_0 = None
    g_g_data_0 = module_0.GGData(none_type_0)
    assert (
        f"{type(g_g_data_0).__module__}.{type(g_g_data_0).__qualname__}"
        == "snippet_368.GGData"
    )
    assert g_g_data_0.r_commands is None
    assert g_g_data_0.fname is None


def test_case_1():
    none_type_0 = None
    g_g_data_0 = module_0.GGData(none_type_0, none_type_0)
    assert (
        f"{type(g_g_data_0).__module__}.{type(g_g_data_0).__qualname__}"
        == "snippet_368.GGData"
    )
    assert g_g_data_0.r_commands is None
    assert g_g_data_0.fname is None
    var_0 = g_g_data_0.__str__()
    assert (
        f"{type(g_g_data_0).__module__}.{type(g_g_data_0).__qualname__}"
        == "snippet_368.GGData"
    )
    assert g_g_data_0.r_commands is None
    assert g_g_data_0.fname is None
