# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_239 as module_0


def test_case_0():
    bool_0 = True
    toggled_prefetching_0 = module_0.toggled_prefetching(bool_0)
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled is True


def test_case_1():
    bytes_0 = b"cD"
    toggled_prefetching_0 = module_0.toggled_prefetching(bytes_0)
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled == b"cD"
    var_0 = toggled_prefetching_0.__enter__()
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled == b"cD"


def test_case_2():
    bool_0 = True
    none_type_0 = None
    toggled_prefetching_0 = module_0.toggled_prefetching(none_type_0)
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled is None
    int_0 = -1568
    toggled_prefetching_1 = module_0.toggled_prefetching(int_0)
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled is None
    assert (
        f"{type(toggled_prefetching_1).__module__}.{type(toggled_prefetching_1).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_1.enabled == -1568
    var_0 = toggled_prefetching_1.__enter__()
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled is None
    assert (
        f"{type(toggled_prefetching_1).__module__}.{type(toggled_prefetching_1).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_1.enabled == -1568
    var_1 = toggled_prefetching_1.__exit__(bool_0, none_type_0, none_type_0)
    assert (
        f"{type(toggled_prefetching_0).__module__}.{type(toggled_prefetching_0).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_0.enabled is None
    assert (
        f"{type(toggled_prefetching_1).__module__}.{type(toggled_prefetching_1).__qualname__}"
        == "snippet_239.toggled_prefetching"
    )
    assert toggled_prefetching_1.enabled == -1568
