# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_170 as module_0


def test_case_0():
    none_type_0 = None
    plane_0 = module_0.Plane(none_type_0, none_type_0)
    assert (
        f"{type(plane_0).__module__}.{type(plane_0).__qualname__}"
        == "snippet_170.Plane"
    )
    assert plane_0.normal is None
    assert plane_0.p is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    plane_0 = module_0.Plane(bool_0, bool_0)
    assert (
        f"{type(plane_0).__module__}.{type(plane_0).__qualname__}"
        == "snippet_170.Plane"
    )
    assert plane_0.normal is False
    assert plane_0.p is False
    plane_0.__str__()


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "\n%1vjn.c5\n[|"
    bool_0 = True
    set_0 = {str_0, bool_0, str_0, str_0}
    plane_0 = module_0.Plane(set_0, set_0)
    assert (
        f"{type(plane_0).__module__}.{type(plane_0).__qualname__}"
        == "snippet_170.Plane"
    )
    assert plane_0.normal == {True, "\n%1vjn.c5\n[|"}
    assert plane_0.p == {True, "\n%1vjn.c5\n[|"}
    plane_0.perpendicular_distance_to_point(set_0)
