# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_352 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -3880
    dbscan_model_0 = module_0.DbscanModel(int_0)
    assert (
        f"{type(dbscan_model_0).__module__}.{type(dbscan_model_0).__qualname__}"
        == "snippet_352.DbscanModel"
    )
    dbscan_model_0.predict(int_0)
