# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_244 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    visitor_0 = module_0.Visitor()
    assert (
        f"{type(visitor_0).__module__}.{type(visitor_0).__qualname__}"
        == "snippet_244.Visitor"
    )
    none_type_0 = None
    visitor_0.visit(none_type_0)


def test_case_1():
    visitor_0 = module_0.Visitor()
    assert (
        f"{type(visitor_0).__module__}.{type(visitor_0).__qualname__}"
        == "snippet_244.Visitor"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    visitor_0 = module_0.Visitor()
    assert (
        f"{type(visitor_0).__module__}.{type(visitor_0).__qualname__}"
        == "snippet_244.Visitor"
    )
    var_0 = visitor_0.visit(list_0)
    assert (
        f"{type(visitor_0).__module__}.{type(visitor_0).__qualname__}"
        == "snippet_244.Visitor"
    )
    var_0.visit(list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    list_0 = [none_type_0]
    visitor_0 = module_0.Visitor()
    assert (
        f"{type(visitor_0).__module__}.{type(visitor_0).__qualname__}"
        == "snippet_244.Visitor"
    )
    visitor_0.visit(list_0)
