# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_345 as module_0


def test_case_0():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0}
    none_type_0 = None
    null_joiner_0 = module_0._NullJoiner(none_type_0, none_type_0)
    assert (
        f"{type(null_joiner_0).__module__}.{type(null_joiner_0).__qualname__}"
        == "snippet_345._NullJoiner"
    )
    var_0 = null_joiner_0.join(dict_0)
    assert var_0 is False
    assert (
        f"{type(null_joiner_0).__module__}.{type(null_joiner_0).__qualname__}"
        == "snippet_345._NullJoiner"
    )


def test_case_1():
    none_type_0 = None
    float_0 = 78.01518
    null_joiner_0 = module_0._NullJoiner(none_type_0, float_0)
    assert (
        f"{type(null_joiner_0).__module__}.{type(null_joiner_0).__qualname__}"
        == "snippet_345._NullJoiner"
    )
    list_0 = []
    null_joiner_1 = module_0._NullJoiner(list_0, list_0)
    assert (
        f"{type(null_joiner_0).__module__}.{type(null_joiner_0).__qualname__}"
        == "snippet_345._NullJoiner"
    )
    assert (
        f"{type(null_joiner_1).__module__}.{type(null_joiner_1).__qualname__}"
        == "snippet_345._NullJoiner"
    )
    with pytest.raises(Exception):
        null_joiner_1.join(list_0)
