# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_602 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xa6\x12\x99"
    simple_time_series_extractor_0 = module_0.SimpleTimeSeriesExtractor(bytes_0)
    assert (
        f"{type(simple_time_series_extractor_0).__module__}.{type(simple_time_series_extractor_0).__qualname__}"
        == "snippet_602.SimpleTimeSeriesExtractor"
    )
    assert simple_time_series_extractor_0.csv_file_path == b"\xa6\x12\x99"
    simple_time_series_extractor_0.process()
