# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_558 as module_0


def test_case_0():
    author_0 = module_0.Author()
    assert (
        f"{type(author_0).__module__}.{type(author_0).__qualname__}"
        == "snippet_558.Author"
    )
    assert author_0.name == ""
    assert author_0.email == ""
    assert (
        f"{type(module_0.Author.gravatar_id).__module__}.{type(module_0.Author.gravatar_id).__qualname__}"
        == "builtins.property"
    )
