# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_117 as module_0


def test_case_0():
    r_r_e_l_base_0 = module_0.RRELBase()
    assert (
        f"{type(r_r_e_l_base_0).__module__}.{type(r_r_e_l_base_0).__qualname__}"
        == "snippet_117.RRELBase"
    )
