# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_669 as module_0


def test_case_0():
    field_meta_special_0 = module_0.FieldMetaSpecial()
    assert (
        f"{type(field_meta_special_0).__module__}.{type(field_meta_special_0).__qualname__}"
        == "snippet_669.FieldMetaSpecial"
    )
    assert module_0.FieldMetaSpecial.none == ""
    assert module_0.FieldMetaSpecial.reset == "R"
    assert module_0.FieldMetaSpecial.sequence == "S"
    assert module_0.FieldMetaSpecial.timestamp == "T"
    assert module_0.FieldMetaSpecial.category == "C"
    assert module_0.FieldMetaSpecial.learning == "L"
    assert (
        f"{type(module_0.FieldMetaSpecial.isValid).__module__}.{type(module_0.FieldMetaSpecial.isValid).__qualname__}"
        == "builtins.method"
    )
