# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_772 as module_0


def test_case_0():
    user_view_mixin_0 = module_0.UserViewMixin()
    assert (
        f"{type(user_view_mixin_0).__module__}.{type(user_view_mixin_0).__qualname__}"
        == "snippet_772.UserViewMixin"
    )
    assert module_0.UserViewMixin.user_field == ["created_by"]
