# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_636 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    x509extlist_0 = module_0._X509extlist(none_type_0)
    assert (
        f"{type(x509extlist_0).__module__}.{type(x509extlist_0).__qualname__}"
        == "snippet_636._X509extlist"
    )
    assert x509extlist_0.cert is None
    x509extlist_0.find_critical()


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    x509extlist_0 = module_0._X509extlist(none_type_0)
    assert (
        f"{type(x509extlist_0).__module__}.{type(x509extlist_0).__qualname__}"
        == "snippet_636._X509extlist"
    )
    assert x509extlist_0.cert is None
    x509extlist_0.find_critical(none_type_0)


def test_case_2():
    str_0 = "%\x0b)$qarb:N!Rv.{!6t]"
    x509extlist_0 = module_0._X509extlist(str_0)
    assert (
        f"{type(x509extlist_0).__module__}.{type(x509extlist_0).__qualname__}"
        == "snippet_636._X509extlist"
    )
    assert x509extlist_0.cert == "%\x0b)$qarb:N!Rv.{!6t]"
