# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_713 as module_0


def test_case_0():
    none_type_0 = None
    completer_describer_0 = module_0.CompleterDescriber(none_type_0)
    assert (
        f"{type(completer_describer_0).__module__}.{type(completer_describer_0).__qualname__}"
        == "snippet_713.CompleterDescriber"
    )
