# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_57 as module_0


def test_case_0():
    v_c_r_fake_socket_0 = module_0.VCRFakeSocket()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    var_0 = v_c_r_fake_socket_0.close()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    v_c_r_fake_socket_0 = module_0.VCRFakeSocket()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    v_c_r_fake_socket_1 = module_0.VCRFakeSocket()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    assert (
        f"{type(v_c_r_fake_socket_1).__module__}.{type(v_c_r_fake_socket_1).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    var_0 = v_c_r_fake_socket_0.settimeout()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    assert (
        f"{type(v_c_r_fake_socket_1).__module__}.{type(v_c_r_fake_socket_1).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    var_0.settimeout()


@pytest.mark.xfail(strict=True)
def test_case_2():
    v_c_r_fake_socket_0 = module_0.VCRFakeSocket()
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    var_0 = v_c_r_fake_socket_0.fileno()
    assert var_0 == 0
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    var_1 = v_c_r_fake_socket_0.fileno()
    assert var_1 == 0
    assert (
        f"{type(v_c_r_fake_socket_0).__module__}.{type(v_c_r_fake_socket_0).__qualname__}"
        == "snippet_57.VCRFakeSocket"
    )
    module_0.VCRFakeSocket(**var_1)
