# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_556 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -3880
    named_keyspace_0 = module_0.NamedKeyspace(int_0)
    assert (
        f"{type(named_keyspace_0).__module__}.{type(named_keyspace_0).__qualname__}"
        == "snippet_556.NamedKeyspace"
    )
    assert named_keyspace_0.name == -3880
    named_keyspace_0.table(int_0)
