# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_183 as module_0


def test_case_0():
    suspend_hooks_0 = module_0.suspend_hooks()
    assert (
        f"{type(suspend_hooks_0).__module__}.{type(suspend_hooks_0).__qualname__}"
        == "snippet_183.suspend_hooks"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    suspend_hooks_0 = module_0.suspend_hooks()
    assert (
        f"{type(suspend_hooks_0).__module__}.{type(suspend_hooks_0).__qualname__}"
        == "snippet_183.suspend_hooks"
    )
    suspend_hooks_0.__enter__()
