# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_38 as module_0


def test_case_0():
    list_0 = []
    bool_0 = False
    list_1 = [list_0, list_0, bool_0, bool_0]
    image_0 = module_0.Image(list_1, list_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )


def test_case_1():
    bool_0 = True
    image_0 = module_0.Image(bool_0, bool_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    var_0 = image_0.__repr__()
    assert var_0 == "snippet_38.Image(True, True)"
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    var_1 = image_0.__repr__()
    assert var_1 == "snippet_38.Image(True, True)"
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    image_0 = module_0.Image(none_type_0, none_type_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    var_0 = image_0.available(none_type_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    var_0.insert(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    complex_0 = -3085.31532 + 873.338934j
    str_0 = "L^yPR"
    image_0 = module_0.Image(str_0, str_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    image_0.insert(complex_0)


def test_case_4():
    bool_0 = True
    none_type_0 = None
    none_type_1 = None
    image_0 = module_0.Image(bool_0, none_type_1)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    var_0 = image_0.available(none_type_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    bytes_0 = b"\x10\xf1\xcb\x0f\xc38A\xb8/\xac\xdbi\xe1\xf8\x05\xcd|\xea\x80"
    image_1 = module_0.Image(bytes_0, bytes_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    assert (
        f"{type(image_1).__module__}.{type(image_1).__qualname__}" == "snippet_38.Image"
    )
    var_1 = image_1.delete(bool_0)
    assert (
        f"{type(image_0).__module__}.{type(image_0).__qualname__}" == "snippet_38.Image"
    )
    assert (
        f"{type(image_1).__module__}.{type(image_1).__qualname__}" == "snippet_38.Image"
    )
