# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_227 as module_0


def test_case_0():
    complex_0 = -1939.70426 + 1467.189j
    installation_result_0 = module_0.InstallationResult(complex_0)
    assert (
        f"{type(installation_result_0).__module__}.{type(installation_result_0).__qualname__}"
        == "snippet_227.InstallationResult"
    )
    assert installation_result_0.name == (-1939.70426 + 1467.189j)


def test_case_1():
    str_0 = "!p3<CXiPOXn"
    installation_result_0 = module_0.InstallationResult(str_0)
    assert (
        f"{type(installation_result_0).__module__}.{type(installation_result_0).__qualname__}"
        == "snippet_227.InstallationResult"
    )
    assert installation_result_0.name == "!p3<CXiPOXn"
    var_0 = installation_result_0.__repr__()
    assert var_0 == "InstallationResult(name='!p3<CXiPOXn')"
    assert (
        f"{type(installation_result_0).__module__}.{type(installation_result_0).__qualname__}"
        == "snippet_227.InstallationResult"
    )
    assert installation_result_0.name == "!p3<CXiPOXn"
