# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_73 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    term_str_0 = module_0.TermStr(*list_0)
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 0
    var_0 = term_str_0.__len__()
    assert var_0 == 0
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 0
    var_0.__len__()


def test_case_1():
    term_str_0 = module_0.TermStr()
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 0
    var_0 = term_str_0.__len__()
    assert var_0 == 0
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 0


def test_case_2():
    term_str_0 = module_0.TermStr()
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 0


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 2522
    bool_0 = True
    list_0 = [int_0, bool_0]
    str_0 = "|PJ"
    list_1 = [str_0, str_0, str_0]
    term_str_0 = module_0.TermStr(*list_1)
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 9
    var_0 = term_str_0.__len__()
    assert var_0 == 9
    assert (
        f"{type(term_str_0).__module__}.{type(term_str_0).__qualname__}"
        == "snippet_73.TermStr"
    )
    assert len(term_str_0) == 9
    var_0.addstr(list_0)
