# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_255 as module_0


def test_case_0():
    list_0 = []
    config_module_0 = module_0.ConfigModule(list_0)
    assert (
        f"{type(config_module_0).__module__}.{type(config_module_0).__qualname__}"
        == "snippet_255.ConfigModule"
    )
    assert (
        f"{type(module_0.ConfigModule.load).__module__}.{type(module_0.ConfigModule.load).__qualname__}"
        == "builtins.method"
    )


def test_case_1():
    list_0 = []
    config_module_0 = module_0.ConfigModule(list_0, list_0)
    assert (
        f"{type(config_module_0).__module__}.{type(config_module_0).__qualname__}"
        == "snippet_255.ConfigModule"
    )
    assert (
        f"{type(module_0.ConfigModule.load).__module__}.{type(module_0.ConfigModule.load).__qualname__}"
        == "builtins.method"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.ConfigModule(none_type_0, none_type_0)
