# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_214 as module_0


def test_case_0():
    none_type_0 = None
    revlink_multiplexer_0 = module_0.RevlinkMultiplexer()
    assert (
        f"{type(revlink_multiplexer_0).__module__}.{type(revlink_multiplexer_0).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert revlink_multiplexer_0.revlinks == ()
    set_0 = {revlink_multiplexer_0, revlink_multiplexer_0}
    revlink_multiplexer_1 = module_0.RevlinkMultiplexer(*set_0)
    assert (
        f"{type(revlink_multiplexer_0).__module__}.{type(revlink_multiplexer_0).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert revlink_multiplexer_0.revlinks == ()
    assert (
        f"{type(revlink_multiplexer_1).__module__}.{type(revlink_multiplexer_1).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert (
        f"{type(revlink_multiplexer_1.revlinks).__module__}.{type(revlink_multiplexer_1.revlinks).__qualname__}"
        == "builtins.tuple"
    )
    assert len(revlink_multiplexer_1.revlinks) == 1
    var_0 = revlink_multiplexer_1.__call__(none_type_0, none_type_0)
    assert (
        f"{type(revlink_multiplexer_0).__module__}.{type(revlink_multiplexer_0).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert revlink_multiplexer_0.revlinks == ()
    assert (
        f"{type(revlink_multiplexer_1).__module__}.{type(revlink_multiplexer_1).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert (
        f"{type(revlink_multiplexer_1.revlinks).__module__}.{type(revlink_multiplexer_1.revlinks).__qualname__}"
        == "builtins.tuple"
    )
    assert len(revlink_multiplexer_1.revlinks) == 1


def test_case_1():
    none_type_0 = None
    revlink_multiplexer_0 = module_0.RevlinkMultiplexer()
    assert (
        f"{type(revlink_multiplexer_0).__module__}.{type(revlink_multiplexer_0).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert revlink_multiplexer_0.revlinks == ()
    var_0 = revlink_multiplexer_0.__call__(none_type_0, none_type_0)
    assert (
        f"{type(revlink_multiplexer_0).__module__}.{type(revlink_multiplexer_0).__qualname__}"
        == "snippet_214.RevlinkMultiplexer"
    )
    assert revlink_multiplexer_0.revlinks == ()
