# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_360 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"I\xd6C\xa9\xa8\xf5\x8bm\xf6\xd9F\x0e\x01\x84\xd5\x8c"
    ini_parser_0 = module_0.IniParser(bytes_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    none_type_0 = None
    ini_parser_0.get(bytes_0, none_type_0)


def test_case_1():
    none_type_0 = None
    ini_parser_0 = module_0.IniParser(none_type_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_0 = ini_parser_0.get(none_type_0, none_type_0)
    assert var_0 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_1 = ini_parser_0.get(none_type_0, ini_parser_0, ini_parser_0)
    assert var_1 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )


def test_case_2():
    bool_0 = True
    str_0 = "\x0c.m#CW:LD|~rjJ"
    none_type_0 = None
    ini_parser_0 = module_0.IniParser(none_type_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_0 = ini_parser_0.get(str_0, str_0)
    assert var_0 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_1 = module_0.IniParser(var_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_1 = ini_parser_1.get(bool_0, bool_0, bool_0)
    assert var_1 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    none_type_1 = None
    ini_parser_2 = module_0.IniParser(ini_parser_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    none_type_2 = None
    ini_parser_3 = module_0.IniParser(none_type_2)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_2 = ini_parser_3.get(none_type_1, none_type_1)
    assert var_2 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )


def test_case_3():
    int_0 = -3384
    ini_parser_0 = module_0.IniParser(int_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )


def test_case_4():
    bool_0 = False
    ini_parser_0 = module_0.IniParser(bool_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_0 = ini_parser_0.get(bool_0, ini_parser_0)
    assert var_0 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_1 = ini_parser_0.get(bool_0, var_0, var_0)
    assert var_1 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_2 = ini_parser_0.get(ini_parser_0, ini_parser_0)
    assert var_2 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    ini_parser_0 = module_0.IniParser(bool_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_0 = ini_parser_0.get(bool_0, bool_0, bool_0)
    assert var_0 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    none_type_0 = None
    var_1 = ini_parser_0.get(bool_0, var_0)
    assert var_1 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    str_0 = "A:mL^yPRxW}|{)7PtW{="
    ini_parser_1 = module_0.IniParser(bool_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_2 = module_0.IniParser(ini_parser_1)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_2 = module_1.object()
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_3 = module_0.IniParser(ini_parser_1)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    bytes_0 = b"j0"
    ini_parser_3 = module_0.IniParser(var_2)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_4 = ini_parser_0.get(none_type_0, ini_parser_3, str_0)
    assert var_4 == "False"
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    int_0 = -2171
    dict_0 = {bytes_0: ini_parser_0, none_type_0: bytes_0, bytes_0: int_0}
    var_5 = var_3.get(var_2, dict_0)
    assert var_5 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_4 = module_0.IniParser(var_2)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_4).__module__}.{type(ini_parser_4).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_3.get(ini_parser_3, none_type_0)


def test_case_6():
    bool_0 = False
    ini_parser_0 = module_0.IniParser(bool_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    bytes_0 = b"\x86\x95 \x82\xa5\x96\xc3\r\x9d\xef6\xf7"
    ini_parser_1 = module_0.IniParser(bool_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    float_0 = -499.0
    var_0 = ini_parser_0.get(bytes_0, float_0)
    assert var_0 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_2 = module_0.IniParser(var_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    none_type_0 = None
    ini_parser_3 = module_0.IniParser(none_type_0)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    var_1 = ini_parser_3.get(bytes_0, var_0, none_type_0)
    assert var_1 is False
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    dict_0 = {}
    int_0 = -319
    var_2 = ini_parser_0.get(none_type_0, dict_0, int_0)
    assert var_2 == 0
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    ini_parser_4 = module_0.IniParser(var_2)
    assert (
        f"{type(ini_parser_0).__module__}.{type(ini_parser_0).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_1).__module__}.{type(ini_parser_1).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_2).__module__}.{type(ini_parser_2).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_3).__module__}.{type(ini_parser_3).__qualname__}"
        == "snippet_360.IniParser"
    )
    assert (
        f"{type(ini_parser_4).__module__}.{type(ini_parser_4).__qualname__}"
        == "snippet_360.IniParser"
    )
