# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_451 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bundle_options_mixin_0 = module_0.BundleOptionsMixin()
    assert (
        f"{type(bundle_options_mixin_0).__module__}.{type(bundle_options_mixin_0).__qualname__}"
        == "snippet_451.BundleOptionsMixin"
    )
    none_type_0 = None
    bundle_options_mixin_0.get_system_opts(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bundle_options_mixin_0 = module_0.BundleOptionsMixin()
    assert (
        f"{type(bundle_options_mixin_0).__module__}.{type(bundle_options_mixin_0).__qualname__}"
        == "snippet_451.BundleOptionsMixin"
    )
    bundle_options_mixin_0.add_arguments(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "AF^\n+Lo,ac)1M"
    bool_0 = True
    dict_0 = {str_0: bool_0}
    bundle_options_mixin_0 = module_0.BundleOptionsMixin()
    assert (
        f"{type(bundle_options_mixin_0).__module__}.{type(bundle_options_mixin_0).__qualname__}"
        == "snippet_451.BundleOptionsMixin"
    )
    var_0 = bundle_options_mixin_0.get_system_opts(dict_0)
    assert (
        f"{type(bundle_options_mixin_0).__module__}.{type(bundle_options_mixin_0).__qualname__}"
        == "snippet_451.BundleOptionsMixin"
    )
    list_0 = [var_0, var_0, bundle_options_mixin_0, dict_0]
    module_0.BundleOptionsMixin(*list_0)
