# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_187 as module_0


def test_case_0():
    none_type_0 = None
    query__field_0 = module_0.Query_Field(none_type_0)
    assert (
        f"{type(query__field_0).__module__}.{type(query__field_0).__qualname__}"
        == "snippet_187.Query_Field"
    )
    assert query__field_0.name is None
    assert query__field_0.is_neg is False


def test_case_1():
    none_type_0 = None
    query__field_0 = module_0.Query_Field(none_type_0, none_type_0)
    assert (
        f"{type(query__field_0).__module__}.{type(query__field_0).__qualname__}"
        == "snippet_187.Query_Field"
    )
    assert query__field_0.name is None
    assert query__field_0.is_neg is None
    var_0 = query__field_0.__neg__()
    assert (
        f"{type(query__field_0).__module__}.{type(query__field_0).__qualname__}"
        == "snippet_187.Query_Field"
    )
    assert query__field_0.name is None
    assert query__field_0.is_neg is None
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_187.Query_Field"
    )
    assert var_0.name is None
    assert var_0.is_neg is True
