# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_482 as module_0


def test_case_0():
    incrementer_0 = module_0.Incrementer()
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    var_0 = incrementer_0.__next__()
    assert var_0 == "Incrementer initialized"
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    var_1 = var_0.__iter__()
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    incrementer_0 = module_0.Incrementer()
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    incrementer_0.send(incrementer_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    incrementer_0 = module_0.Incrementer()
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    var_0 = incrementer_0.__iter__()
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    var_1 = var_0.__next__()
    assert var_1 == "Incrementer initialized"
    assert (
        f"{type(incrementer_0).__module__}.{type(incrementer_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_482.Incrementer"
    )
    var_1.__next__()
