# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_167 as module_0


def test_case_0():
    temp_dir_0 = module_0.TempDir()
    assert (
        f"{type(temp_dir_0).__module__}.{type(temp_dir_0).__qualname__}"
        == "snippet_167.TempDir"
    )
    assert temp_dir_0.path is None
    var_0 = temp_dir_0.close()
    assert (
        f"{type(temp_dir_0).__module__}.{type(temp_dir_0).__qualname__}"
        == "snippet_167.TempDir"
    )
    assert temp_dir_0.path is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    temp_dir_0 = module_0.TempDir()
    assert (
        f"{type(temp_dir_0).__module__}.{type(temp_dir_0).__qualname__}"
        == "snippet_167.TempDir"
    )
    assert temp_dir_0.path is None
    temp_dir_0.open()
