# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_99 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b'U"S\xac~\x84\xbaX\xce\xedW(\x1e\x83\xee['
    none_type_0 = None
    vm_details_command_0 = module_0.VmDetailsCommand(bytes_0, none_type_0)
    assert (
        f"{type(vm_details_command_0).__module__}.{type(vm_details_command_0).__qualname__}"
        == "snippet_99.VmDetailsCommand"
    )
    assert (
        vm_details_command_0.pyvmomi_service
        == b'U"S\xac~\x84\xbaX\xce\xedW(\x1e\x83\xee['
    )
    assert vm_details_command_0.vm_details_provider is None
    assert vm_details_command_0.timeout == 30
    assert vm_details_command_0.delay == 1
    vm_details_command_0.get_vm_details(
        none_type_0, vm_details_command_0, none_type_0, bytes_0, bytes_0
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1833
    vm_details_command_0 = module_0.VmDetailsCommand(int_0, int_0)
    assert (
        f"{type(vm_details_command_0).__module__}.{type(vm_details_command_0).__qualname__}"
        == "snippet_99.VmDetailsCommand"
    )
    assert vm_details_command_0.pyvmomi_service == 1833
    assert vm_details_command_0.vm_details_provider == 1833
    assert vm_details_command_0.timeout == 30
    assert vm_details_command_0.delay == 1
    dict_0 = {}
    var_0 = vm_details_command_0.get_vm_details(
        vm_details_command_0,
        vm_details_command_0,
        vm_details_command_0,
        dict_0,
        vm_details_command_0,
    )
    assert (
        f"{type(vm_details_command_0).__module__}.{type(vm_details_command_0).__qualname__}"
        == "snippet_99.VmDetailsCommand"
    )
    assert vm_details_command_0.pyvmomi_service == 1833
    assert vm_details_command_0.vm_details_provider == 1833
    assert vm_details_command_0.timeout == 30
    assert vm_details_command_0.delay == 1
    bytes_0 = b"\x16\x971\x1a\x95KV\n\xe2\x82\xd7N<\xffj\x89"
    vm_details_command_0.get_vm_details(
        var_0, vm_details_command_0, vm_details_command_0, bytes_0, vm_details_command_0
    )


def test_case_2():
    int_0 = 1820
    vm_details_command_0 = module_0.VmDetailsCommand(int_0, int_0)
    assert (
        f"{type(vm_details_command_0).__module__}.{type(vm_details_command_0).__qualname__}"
        == "snippet_99.VmDetailsCommand"
    )
    assert vm_details_command_0.pyvmomi_service == 1820
    assert vm_details_command_0.vm_details_provider == 1820
    assert vm_details_command_0.timeout == 30
    assert vm_details_command_0.delay == 1
