# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_690 as module_0


def test_case_0():
    bytes_0 = b"\x15"
    dataset_loop_0 = module_0.DatasetLoop(bytes_0, bytes_0)
    assert (
        f"{type(dataset_loop_0).__module__}.{type(dataset_loop_0).__qualname__}"
        == "snippet_690.DatasetLoop"
    )
    assert dataset_loop_0.datasets == b"\x15"
    assert dataset_loop_0.reader == b"\x15"
    var_0 = dataset_loop_0.__repr__()
    assert var_0 == "DatasetLoop(datasets=b'\\x15', reader=b'\\x15')"
    assert (
        f"{type(dataset_loop_0).__module__}.{type(dataset_loop_0).__qualname__}"
        == "snippet_690.DatasetLoop"
    )
    assert dataset_loop_0.datasets == b"\x15"
    assert dataset_loop_0.reader == b"\x15"


def test_case_1():
    bytes_0 = b"\xde\xab \xe9\xa3\x9d\x8e@''\x87*H\x1e\xd6"
    dataset_loop_0 = module_0.DatasetLoop(bytes_0, bytes_0)
    assert (
        f"{type(dataset_loop_0).__module__}.{type(dataset_loop_0).__qualname__}"
        == "snippet_690.DatasetLoop"
    )
    assert dataset_loop_0.datasets == b"\xde\xab \xe9\xa3\x9d\x8e@''\x87*H\x1e\xd6"
    assert dataset_loop_0.reader == b"\xde\xab \xe9\xa3\x9d\x8e@''\x87*H\x1e\xd6"
