# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_731 as module_0


def test_case_0():
    bytes_0 = b"k\x93\xe6\xd7\xb2\x8c\xb4H"
    tuple_0 = (bytes_0,)
    dict_0 = {tuple_0: bytes_0, tuple_0: tuple_0}
    missing_ctypes_0 = module_0._missing_ctypes()
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    var_0 = missing_ctypes_0.c_void_p(dict_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )


def test_case_1():
    missing_ctypes_0 = module_0._missing_ctypes()
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    var_0 = missing_ctypes_0.c_void_p(missing_ctypes_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    var_1 = missing_ctypes_0.c_void_p(var_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    var_2 = var_1.cast(var_0, var_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    var_3 = missing_ctypes_0.c_void_p(missing_ctypes_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    str_0 = "}b#)(h#QPXg"
    var_4 = var_0.cast(var_3, str_0)
    assert (
        f"{type(missing_ctypes_0).__module__}.{type(missing_ctypes_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_3).__module__}.{type(var_3).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "snippet_731._missing_ctypes"
    )
