# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_251 as module_0


def test_case_0():
    uuid_set_values_mixin_0 = module_0._UuidSetValuesMixin()
    assert (
        f"{type(uuid_set_values_mixin_0).__module__}.{type(uuid_set_values_mixin_0).__qualname__}"
        == "snippet_251._UuidSetValuesMixin"
    )
