# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_677 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -913
    bytes_0 = b"\x1d\x1e\xe7\xba\xcf5l\xeb\t\xff\xc9\xd9<\x84\xc7\xc5\x00v\xc3"
    progress_0 = module_0.Progress(bytes_0, bytes_0)
    assert (
        f"{type(progress_0).__module__}.{type(progress_0).__qualname__}"
        == "snippet_677.Progress"
    )
    assert (
        progress_0.length
        == b"\x1d\x1e\xe7\xba\xcf5l\xeb\t\xff\xc9\xd9<\x84\xc7\xc5\x00v\xc3"
    )
    assert (
        progress_0.output
        == b"\x1d\x1e\xe7\xba\xcf5l\xeb\t\xff\xc9\xd9<\x84\xc7\xc5\x00v\xc3"
    )
    progress_0.update(int_0)
