# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_10 as module_0


def test_case_0():
    base_case_0 = module_0.base_case()
    assert (
        f"{type(base_case_0).__module__}.{type(base_case_0).__qualname__}"
        == "snippet_10.base_case"
    )
