# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_175 as module_0


def test_case_0():
    none_type_0 = None
    generic_column_0 = module_0.GenericColumn(none_type_0)
    assert (
        f"{type(generic_column_0).__module__}.{type(generic_column_0).__qualname__}"
        == "snippet_175.GenericColumn"
    )
    assert generic_column_0.col_type is None
    assert generic_column_0.primary_key is False
    assert generic_column_0.unique is False
    assert generic_column_0.nullable is False
    assert module_0.GenericColumn.col_type is None
    assert module_0.GenericColumn.primary_key is None
    assert module_0.GenericColumn.unique is None
    assert module_0.GenericColumn.nullable is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    str_0 = "stsUcA3Z7(|B^~R|K4{p"
    generic_column_0 = module_0.GenericColumn(str_0)
    assert (
        f"{type(generic_column_0).__module__}.{type(generic_column_0).__qualname__}"
        == "snippet_175.GenericColumn"
    )
    assert generic_column_0.col_type == "stsUcA3Z7(|B^~R|K4{p"
    assert generic_column_0.primary_key is False
    assert generic_column_0.unique is False
    assert generic_column_0.nullable is False
    assert module_0.GenericColumn.col_type is None
    assert module_0.GenericColumn.primary_key is None
    assert module_0.GenericColumn.unique is None
    assert module_0.GenericColumn.nullable is None
    generic_column_0.check_type(none_type_0)
