# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_221 as module_0


def test_case_0():
    result_0 = module_0.Result()
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []


@pytest.mark.xfail(strict=True)
def test_case_1():
    result_0 = module_0.Result()
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    result_0.__hash__()


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -1731
    result_0 = module_0.Result()
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    result_0.__eq__(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    result_0 = module_0.Result()
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    var_0 = result_0.__repr__()
    assert var_0 == "{'attempt': 1, 'read_length': -1, 'redirects': []}"
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    var_1 = var_0.__eq__(bool_0)
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    result_1 = module_0.Result()
    assert (
        f"{type(result_0).__module__}.{type(result_0).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_0.attempt == 1
    assert result_0.read_length == -1
    assert result_0.redirects == []
    assert (
        f"{type(result_1).__module__}.{type(result_1).__qualname__}"
        == "snippet_221.Result"
    )
    assert result_1.attempt == 1
    assert result_1.read_length == -1
    assert result_1.redirects == []
    result_1.__copy__()
