# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_519 as module_0


def test_case_0():
    bool_0 = False
    project_dependencies_0 = module_0.ProjectDependencies(bool_0, bool_0)
    assert (
        f"{type(project_dependencies_0).__module__}.{type(project_dependencies_0).__qualname__}"
        == "snippet_519.ProjectDependencies"
    )
