# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_317 as module_0


def test_case_0():
    none_type_0 = None
    semi_minor_radius_0 = module_0.SemiMinorRadius(none_type_0)
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value is None
    assert module_0.SemiMinorRadius.proj4 == "+b"


def test_case_1():
    int_0 = 1015
    semi_minor_radius_0 = module_0.SemiMinorRadius(int_0)
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value == 1015
    assert module_0.SemiMinorRadius.proj4 == "+b"
    var_0 = semi_minor_radius_0.to_proj4()
    assert var_0 == "+b=1015"
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value == 1015
    assert module_0.SemiMinorRadius.proj4 == "+b"


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 2287
    semi_minor_radius_0 = module_0.SemiMinorRadius(int_0)
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value == 2287
    assert module_0.SemiMinorRadius.proj4 == "+b"
    var_0 = semi_minor_radius_0.to_esri_wkt()
    assert var_0 == "2287"
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value == 2287
    assert module_0.SemiMinorRadius.proj4 == "+b"
    var_0.to_proj4()


def test_case_3():
    none_type_0 = None
    semi_minor_radius_0 = module_0.SemiMinorRadius(none_type_0)
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value is None
    assert module_0.SemiMinorRadius.proj4 == "+b"
    var_0 = semi_minor_radius_0.to_ogc_wkt()
    assert var_0 == "None"
    assert (
        f"{type(semi_minor_radius_0).__module__}.{type(semi_minor_radius_0).__qualname__}"
        == "snippet_317.SemiMinorRadius"
    )
    assert semi_minor_radius_0.value is None
    assert module_0.SemiMinorRadius.proj4 == "+b"
