# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_81 as module_0


def test_case_0():
    str_0 = 'Oz_\x0c:JXo>9"'
    e_c_p_response_0 = module_0.ECP_response(str_0)
    assert (
        f"{type(e_c_p_response_0).__module__}.{type(e_c_p_response_0).__qualname__}"
        == "snippet_81.ECP_response"
    )
    assert e_c_p_response_0.content == 'Oz_\x0c:JXo>9"'
    assert module_0.ECP_response.code == 200
    assert module_0.ECP_response.title == "OK"


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    none_type_0 = None
    e_c_p_response_0 = module_0.ECP_response(none_type_0)
    assert (
        f"{type(e_c_p_response_0).__module__}.{type(e_c_p_response_0).__qualname__}"
        == "snippet_81.ECP_response"
    )
    assert e_c_p_response_0.content is None
    assert module_0.ECP_response.code == 200
    assert module_0.ECP_response.title == "OK"
    e_c_p_response_0.__call__(bool_0, bool_0)
