# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_309 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -677
    module_0.Backend(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    float_0 = -1067.576
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.close()


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -1013.8568307043719
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.connect()


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = -1013.8568307043719
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.do_createdb()


@pytest.mark.xfail(strict=True)
def test_case_4():
    float_0 = -1013.8568307043719
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.do_dropdb()


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = -1013.8568307043719
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.createdb()


@pytest.mark.xfail(strict=True)
def test_case_6():
    float_0 = -1013.8568
    dict_0 = {float_0: float_0, float_0: float_0}
    backend_0 = module_0.Backend(dict_0)
    assert (
        f"{type(backend_0).__module__}.{type(backend_0).__qualname__}"
        == "snippet_309.Backend"
    )
    assert backend_0.host is None
    assert backend_0.port is None
    assert backend_0.password is None
    assert backend_0.name is None
    assert backend_0.user is None
    assert backend_0.engine is None
    assert (
        f"{type(backend_0.options).__module__}.{type(backend_0.options).__qualname__}"
        == "builtins.dict"
    )
    assert len(backend_0.options) == 1
    backend_0.dropdb()
