# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_688 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x91\x9cD\x0b\xd7\xb4\xaf{\xff3X\x86\x9b\x9auv"
    attr_list_0 = module_0.AttrList(bytes_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == b"\x91\x9cD\x0b\xd7\xb4\xaf{\xff3X\x86\x9b\x9auv"
    attr_list_0.rlen()


def test_case_1():
    bytes_0 = b""
    attr_list_0 = module_0.AttrList(bytes_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == b""
    var_0 = attr_list_0.rlen()
    assert var_0 == 0
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == b""


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    attr_list_0 = module_0.AttrList(set_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    bool_0 = True
    tuple_0 = (bool_0,)
    var_0 = attr_list_0.real()
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    var_1 = attr_list_0.lang()
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    attr_list_1 = module_0.AttrList(var_1)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    assert (
        f"{type(attr_list_1).__module__}.{type(attr_list_1).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_1.raw is None
    attr_list_2 = module_0.AttrList(tuple_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    assert (
        f"{type(attr_list_1).__module__}.{type(attr_list_1).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_1.raw is None
    assert (
        f"{type(attr_list_2).__module__}.{type(attr_list_2).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_2.raw == (True,)
    attr_list_2.lang()


def test_case_3():
    bool_0 = True
    attr_list_0 = module_0.AttrList(bool_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw is True


@pytest.mark.xfail(strict=True)
def test_case_4():
    set_0 = set()
    attr_list_0 = module_0.AttrList(set_0)
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    var_0 = attr_list_0.rlen()
    assert var_0 == 0
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    dict_0 = attr_list_0.lang()
    assert (
        f"{type(attr_list_0).__module__}.{type(attr_list_0).__qualname__}"
        == "snippet_688.AttrList"
    )
    assert attr_list_0.raw == {*()}
    var_0.lang()
