# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_600 as module_0


def test_case_0():
    none_type_0 = None
    progress_bar_stream_0 = module_0.ProgressBarStream(none_type_0)
    assert (
        f"{type(progress_bar_stream_0).__module__}.{type(progress_bar_stream_0).__qualname__}"
        == "snippet_600.ProgressBarStream"
    )
    assert progress_bar_stream_0.stream is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "^G!"
    list_0 = [str_0, str_0]
    progress_bar_stream_0 = module_0.ProgressBarStream(str_0)
    assert (
        f"{type(progress_bar_stream_0).__module__}.{type(progress_bar_stream_0).__qualname__}"
        == "snippet_600.ProgressBarStream"
    )
    assert progress_bar_stream_0.stream == "^G!"
    progress_bar_stream_0.write(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    progress_bar_stream_0 = module_0.ProgressBarStream(none_type_0)
    assert (
        f"{type(progress_bar_stream_0).__module__}.{type(progress_bar_stream_0).__qualname__}"
        == "snippet_600.ProgressBarStream"
    )
    assert progress_bar_stream_0.stream is None
    progress_bar_stream_0.flush()
