# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_690 as module_0


def test_case_0():
    import_export_certificate_0 = module_0.ImportExportCertificate()
    assert (
        f"{type(import_export_certificate_0).__module__}.{type(import_export_certificate_0).__qualname__}"
        == "snippet_690.ImportExportCertificate"
    )
