# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_79 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    module_0.DirectFormat(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    none_type_1 = None
    direct_format_0 = module_0.DirectFormat()
    assert (
        f"{type(direct_format_0).__module__}.{type(direct_format_0).__qualname__}"
        == "snippet_79.DirectFormat"
    )
    var_0 = direct_format_0.getCount(none_type_1)
    assert var_0 == 1
    assert (
        f"{type(direct_format_0).__module__}.{type(direct_format_0).__qualname__}"
        == "snippet_79.DirectFormat"
    )
    var_0.getValue(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "AF^\n+Lo,ac)1M"
    bool_0 = True
    dict_0 = {str_0: bool_0}
    direct_format_0 = module_0.DirectFormat()
    assert (
        f"{type(direct_format_0).__module__}.{type(direct_format_0).__qualname__}"
        == "snippet_79.DirectFormat"
    )
    var_0 = direct_format_0.getValue(str_0)
    assert var_0 == "AF^\n+Lo,ac)1M"
    assert (
        f"{type(direct_format_0).__module__}.{type(direct_format_0).__qualname__}"
        == "snippet_79.DirectFormat"
    )
    module_0.DirectFormat(**dict_0)
