# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_25 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    command_dispatcher_0 = module_0.CommandDispatcher()
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    command_dispatcher_1 = module_0.CommandDispatcher()
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    assert (
        f"{type(command_dispatcher_1).__module__}.{type(command_dispatcher_1).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_1.commands == {}
    command_dispatcher_1.execute_command(command_dispatcher_1)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"d\x1f?T\xe9UL&\n\x9f0\xba\xb4B\xdd\xcaZ"
    command_dispatcher_0 = module_0.CommandDispatcher()
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    command_dispatcher_0.execute_command(command_dispatcher_0, bytes_0)


def test_case_2():
    command_dispatcher_0 = module_0.CommandDispatcher()
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    command_dispatcher_1 = command_dispatcher_0.bound(command_dispatcher_0)
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    assert (
        f"{type(command_dispatcher_1).__module__}.{type(command_dispatcher_1).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_1.commands == {}


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    command_dispatcher_0 = module_0.CommandDispatcher()
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    var_0 = command_dispatcher_0.bound(dict_0)
    assert (
        f"{type(command_dispatcher_0).__module__}.{type(command_dispatcher_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert command_dispatcher_0.commands == {}
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_25.CommandDispatcher"
    )
    assert var_0.commands == {}
    var_0.command(var_0)
