# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_494 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"J\x18\xf8\xcf\x1f+\x05{\xe1Y\x18"
    none_type_0 = None
    dict_0 = {}
    ngram_0 = module_0.Ngram(**dict_0)
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    var_0 = ngram_0.generate_ngram_data_set(bytes_0)
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    var_0.generate_tuple_zip(none_type_0)


def test_case_1():
    tuple_0 = ()
    ngram_0 = module_0.Ngram()
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    var_0 = ngram_0.generate_skip_gram_data_set(tuple_0)
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    ngram_0 = module_0.Ngram()
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    ngram_0.generate_ngram_data_set(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "V[9#\x0cM&\rxk;Km'&r6SZV"
    bool_0 = True
    ngram_0 = module_0.Ngram()
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    var_0 = ngram_0.generate_skip_gram_data_set(str_0)
    assert (
        f"{type(ngram_0).__module__}.{type(ngram_0).__qualname__}"
        == "snippet_494.Ngram"
    )
    var_0.generate_ngram_data_set(bool_0)
