# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_295 as module_0
import builtins as module_1


def test_case_0():
    none_type_0 = None
    tsv_reader_0 = module_0.TsvReader(none_type_0)
    assert (
        f"{type(tsv_reader_0).__module__}.{type(tsv_reader_0).__qualname__}"
        == "snippet_295.TsvReader"
    )
    assert tsv_reader_0.stream is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    tsv_reader_0 = module_0.TsvReader(none_type_0)
    assert (
        f"{type(tsv_reader_0).__module__}.{type(tsv_reader_0).__qualname__}"
        == "snippet_295.TsvReader"
    )
    assert tsv_reader_0.stream is None
    tsv_reader_0.close()


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = 'RT!"zH\x0b\nSzW3ITOt~'
    tsv_reader_0 = module_0.TsvReader(str_0)
    assert (
        f"{type(tsv_reader_0).__module__}.{type(tsv_reader_0).__qualname__}"
        == "snippet_295.TsvReader"
    )
    assert tsv_reader_0.stream == 'RT!"zH\x0b\nSzW3ITOt~'
    module_1.object(*tsv_reader_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = 'R\r#aT!"zH\x0b\nSzW3ITOt~'
    tsv_reader_0 = module_0.TsvReader(str_0)
    assert (
        f"{type(tsv_reader_0).__module__}.{type(tsv_reader_0).__qualname__}"
        == "snippet_295.TsvReader"
    )
    assert tsv_reader_0.stream == 'R\r#aT!"zH\x0b\nSzW3ITOt~'
    var_0 = tsv_reader_0.__iter__()
    assert (
        f"{type(tsv_reader_0).__module__}.{type(tsv_reader_0).__qualname__}"
        == "snippet_295.TsvReader"
    )
    assert tsv_reader_0.stream == 'R\r#aT!"zH\x0b\nSzW3ITOt~'
    module_1.object(*var_0)
