# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_640 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    regenerator_0 = module_0.Regenerator(bool_0)
    assert (
        f"{type(regenerator_0).__module__}.{type(regenerator_0).__qualname__}"
        == "snippet_640.Regenerator"
    )
    regenerator_0.next()


def test_case_1():
    bool_0 = True
    regenerator_0 = module_0.Regenerator(bool_0)
    assert (
        f"{type(regenerator_0).__module__}.{type(regenerator_0).__qualname__}"
        == "snippet_640.Regenerator"
    )


def test_case_2():
    bool_0 = True
    regenerator_0 = module_0.Regenerator(bool_0)
    assert (
        f"{type(regenerator_0).__module__}.{type(regenerator_0).__qualname__}"
        == "snippet_640.Regenerator"
    )
    var_0 = regenerator_0.__iter__()
    assert (
        f"{type(regenerator_0).__module__}.{type(regenerator_0).__qualname__}"
        == "snippet_640.Regenerator"
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "snippet_640.Regenerator"
    )
