# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_178 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    str_0 = "?sQEWLT`Z,R\\cE;-\x0cr"
    set_0 = {str_0, str_0}
    error_checking_chain_0 = module_0.ErrorCheckingChain(list_0, list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert error_checking_chain_0.excludes == []
    error_checking_chain_0.__call__(set_0, list_0, set_0)


def test_case_1():
    list_0 = []
    error_checking_chain_0 = module_0.ErrorCheckingChain(list_0, list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert error_checking_chain_0.excludes == []


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    list_0 = [bool_0]
    none_type_0 = None
    error_checking_chain_0 = module_0.ErrorCheckingChain(list_0, none_type_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert error_checking_chain_0.strategy is None
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 2
    assert error_checking_chain_0.excludes == []
    var_0 = error_checking_chain_0.next()
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert error_checking_chain_0.strategy is None
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 2
    assert error_checking_chain_0.excludes == []
    var_0.end()


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    error_checking_chain_0 = module_0.ErrorCheckingChain(list_0, list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert error_checking_chain_0.excludes == []
    bool_0 = False
    list_1 = [bool_0]
    none_type_0 = None
    error_checking_chain_1 = module_0.ErrorCheckingChain(list_1, none_type_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert error_checking_chain_0.excludes == []
    assert (
        f"{type(error_checking_chain_1).__module__}.{type(error_checking_chain_1).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert error_checking_chain_1.strategy is None
    assert (
        f"{type(error_checking_chain_1.chain).__module__}.{type(error_checking_chain_1.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.chain) == 2
    assert error_checking_chain_1.excludes == []
    var_0 = error_checking_chain_0.addFilterException(list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert (
        f"{type(error_checking_chain_0.excludes).__module__}.{type(error_checking_chain_0.excludes).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.excludes) == 1
    assert (
        f"{type(error_checking_chain_1).__module__}.{type(error_checking_chain_1).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert error_checking_chain_1.strategy is None
    assert (
        f"{type(error_checking_chain_1.chain).__module__}.{type(error_checking_chain_1.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.chain) == 2
    assert error_checking_chain_1.excludes == []
    list_0.end()


@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    error_checking_chain_0 = module_0.ErrorCheckingChain(list_0, list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 1
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 1
    assert error_checking_chain_0.excludes == []
    bool_0 = False
    error_checking_chain_1 = module_0.ErrorCheckingChain(list_0, list_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 2
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 2
    assert error_checking_chain_0.excludes == []
    assert (
        f"{type(error_checking_chain_1).__module__}.{type(error_checking_chain_1).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_1.strategy).__module__}.{type(error_checking_chain_1.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.strategy) == 2
    assert (
        f"{type(error_checking_chain_1.chain).__module__}.{type(error_checking_chain_1.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.chain) == 2
    assert error_checking_chain_1.excludes == []
    list_1 = [bool_0]
    none_type_0 = None
    var_0 = error_checking_chain_0.addFilterException(none_type_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 2
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 2
    assert error_checking_chain_0.excludes == [None]
    assert (
        f"{type(error_checking_chain_1).__module__}.{type(error_checking_chain_1).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_1.strategy).__module__}.{type(error_checking_chain_1.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.strategy) == 2
    assert (
        f"{type(error_checking_chain_1.chain).__module__}.{type(error_checking_chain_1.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.chain) == 2
    assert error_checking_chain_1.excludes == [None]
    error_checking_chain_2 = module_0.ErrorCheckingChain(list_1, bool_0)
    assert (
        f"{type(error_checking_chain_0).__module__}.{type(error_checking_chain_0).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_0.strategy).__module__}.{type(error_checking_chain_0.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.strategy) == 2
    assert (
        f"{type(error_checking_chain_0.chain).__module__}.{type(error_checking_chain_0.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_0.chain) == 2
    assert error_checking_chain_0.excludes == [None]
    assert (
        f"{type(error_checking_chain_1).__module__}.{type(error_checking_chain_1).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert (
        f"{type(error_checking_chain_1.strategy).__module__}.{type(error_checking_chain_1.strategy).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.strategy) == 2
    assert (
        f"{type(error_checking_chain_1.chain).__module__}.{type(error_checking_chain_1.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_1.chain) == 2
    assert error_checking_chain_1.excludes == [None]
    assert (
        f"{type(error_checking_chain_2).__module__}.{type(error_checking_chain_2).__qualname__}"
        == "snippet_178.ErrorCheckingChain"
    )
    assert error_checking_chain_2.strategy is False
    assert (
        f"{type(error_checking_chain_2.chain).__module__}.{type(error_checking_chain_2.chain).__qualname__}"
        == "builtins.list"
    )
    assert len(error_checking_chain_2.chain) == 2
    assert error_checking_chain_2.excludes == []
    var_0.__call__(list_0, none_type_0, list_1)
