# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_137 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    complex_0 = 595 - 2621.685j
    script_executor_0 = module_0.ScriptExecutor(complex_0, complex_0, complex_0)
    assert (
        f"{type(script_executor_0).__module__}.{type(script_executor_0).__qualname__}"
        == "snippet_137.ScriptExecutor"
    )
    assert script_executor_0.logger == (595 - 2621.685j)
    assert script_executor_0.script_type == (595 - 2621.685j)
    assert script_executor_0.default_shell == (595 - 2621.685j)
    script_executor_0.RunScripts(complex_0)


def test_case_1():
    bool_0 = False
    script_executor_0 = module_0.ScriptExecutor(bool_0, bool_0)
    assert (
        f"{type(script_executor_0).__module__}.{type(script_executor_0).__qualname__}"
        == "snippet_137.ScriptExecutor"
    )
    assert script_executor_0.logger is False
    assert script_executor_0.script_type is False
    assert script_executor_0.default_shell == "/bin/bash"


@pytest.mark.xfail(strict=True)
def test_case_2():
    dict_0 = {}
    script_executor_0 = module_0.ScriptExecutor(dict_0, dict_0, dict_0)
    assert (
        f"{type(script_executor_0).__module__}.{type(script_executor_0).__qualname__}"
        == "snippet_137.ScriptExecutor"
    )
    assert script_executor_0.logger == {}
    assert script_executor_0.script_type == {}
    assert script_executor_0.default_shell == "/bin/bash"
    script_executor_0.RunScripts(dict_0)
