# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_222 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    some_class_0 = module_0.SomeClass()
    assert (
        f"{type(some_class_0).__module__}.{type(some_class_0).__qualname__}"
        == "snippet_222.SomeClass"
    )
    assert module_0.SomeClass.doc == "cds"
    var_0 = some_class_0.besilent()
    assert (
        f"{type(some_class_0).__module__}.{type(some_class_0).__qualname__}"
        == "snippet_222.SomeClass"
    )
    assert module_0.SomeClass.doc == "cds"
    var_0.besilent()


@pytest.mark.xfail(strict=True)
def test_case_1():
    some_class_0 = module_0.SomeClass()
    assert (
        f"{type(some_class_0).__module__}.{type(some_class_0).__qualname__}"
        == "snippet_222.SomeClass"
    )
    assert module_0.SomeClass.doc == "cds"
    var_0 = some_class_0.please()
    assert (
        f"{type(some_class_0).__module__}.{type(some_class_0).__qualname__}"
        == "snippet_222.SomeClass"
    )
    assert module_0.SomeClass.doc == "cds"
    var_0.besilent()
