# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_451 as module_0


def test_case_0():
    float_0 = 823.43357
    stream_request_mixin_0 = module_0.StreamRequestMixin()
    assert (
        f"{type(stream_request_mixin_0).__module__}.{type(stream_request_mixin_0).__qualname__}"
        == "snippet_451.StreamRequestMixin"
    )
    with pytest.raises(ValueError):
        stream_request_mixin_0.proxy_protocol(float_0, authenticate=float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    stream_request_mixin_0 = module_0.StreamRequestMixin()
    assert (
        f"{type(stream_request_mixin_0).__module__}.{type(stream_request_mixin_0).__qualname__}"
        == "snippet_451.StreamRequestMixin"
    )
    stream_request_mixin_0.proxy_protocol()


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    list_0 = []
    stream_request_mixin_0 = module_0.StreamRequestMixin(*list_0)
    assert (
        f"{type(stream_request_mixin_0).__module__}.{type(stream_request_mixin_0).__qualname__}"
        == "snippet_451.StreamRequestMixin"
    )
    list_1 = [stream_request_mixin_0, none_type_0, none_type_0, list_0]
    stream_request_mixin_0.proxy_authenticate(list_1)
