# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_526 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -2955
    bundle_activator_0 = module_0._BundleActivator()
    assert (
        f"{type(bundle_activator_0).__module__}.{type(bundle_activator_0).__qualname__}"
        == "snippet_526._BundleActivator"
    )
    bundle_activator_0.start(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bundle_activator_0 = module_0._BundleActivator()
    assert (
        f"{type(bundle_activator_0).__module__}.{type(bundle_activator_0).__qualname__}"
        == "snippet_526._BundleActivator"
    )
    bundle_activator_1 = module_0._BundleActivator()
    assert (
        f"{type(bundle_activator_0).__module__}.{type(bundle_activator_0).__qualname__}"
        == "snippet_526._BundleActivator"
    )
    assert (
        f"{type(bundle_activator_1).__module__}.{type(bundle_activator_1).__qualname__}"
        == "snippet_526._BundleActivator"
    )
    bundle_activator_0.stop(bundle_activator_0)
