# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_592 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 2373
    compiler_0 = module_0.Compiler(int_0, int_0)
    assert (
        f"{type(compiler_0).__module__}.{type(compiler_0).__qualname__}"
        == "snippet_592.Compiler"
    )
    compiler_0.compile(int_0)


def test_case_1():
    int_0 = 2385
    compiler_0 = module_0.Compiler(int_0, int_0)
    assert (
        f"{type(compiler_0).__module__}.{type(compiler_0).__qualname__}"
        == "snippet_592.Compiler"
    )
