# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_499 as module_0


def test_case_0():
    bytes_0 = b"\xf6\x926\r\xa5"
    license_manager_0 = module_0.LicenseManager(bytes_0)
    assert (
        f"{type(license_manager_0).__module__}.{type(license_manager_0).__qualname__}"
        == "snippet_499.LicenseManager"
    )
