# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_235 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    matching_scenarios_list_0 = module_0.MatchingScenariosList()
    assert (
        f"{type(matching_scenarios_list_0).__module__}.{type(matching_scenarios_list_0).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_0.matching_scenarios_list == []
    matching_scenarios_list_0.pop_scenario()


@pytest.mark.xfail(strict=True)
def test_case_1():
    matching_scenarios_list_0 = module_0.MatchingScenariosList()
    assert (
        f"{type(matching_scenarios_list_0).__module__}.{type(matching_scenarios_list_0).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_0.matching_scenarios_list == []
    matching_scenarios_list_1 = module_0.MatchingScenariosList()
    assert (
        f"{type(matching_scenarios_list_0).__module__}.{type(matching_scenarios_list_0).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_0.matching_scenarios_list == []
    assert (
        f"{type(matching_scenarios_list_1).__module__}.{type(matching_scenarios_list_1).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_1.matching_scenarios_list == []
    none_type_0 = None
    matching_scenarios_list_2 = module_0.MatchingScenariosList()
    assert (
        f"{type(matching_scenarios_list_0).__module__}.{type(matching_scenarios_list_0).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_0.matching_scenarios_list == []
    assert (
        f"{type(matching_scenarios_list_1).__module__}.{type(matching_scenarios_list_1).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_1.matching_scenarios_list == []
    assert (
        f"{type(matching_scenarios_list_2).__module__}.{type(matching_scenarios_list_2).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_2.matching_scenarios_list == []
    var_0 = matching_scenarios_list_2.append_scenario(none_type_0)
    assert (
        f"{type(matching_scenarios_list_0).__module__}.{type(matching_scenarios_list_0).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_0.matching_scenarios_list == []
    assert (
        f"{type(matching_scenarios_list_1).__module__}.{type(matching_scenarios_list_1).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_1.matching_scenarios_list == []
    assert (
        f"{type(matching_scenarios_list_2).__module__}.{type(matching_scenarios_list_2).__qualname__}"
        == "snippet_235.MatchingScenariosList"
    )
    assert matching_scenarios_list_2.matching_scenarios_list == [None]
    var_0.append_scenario(matching_scenarios_list_1)
