# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_376 as module_0
import builtins as module_1


def test_case_0():
    none_type_0 = None
    str_0 = "yhB2(cUR"
    str_1 = "Lhf=K%z2"
    edge_0 = module_0.Edge(none_type_0, str_1, str_1)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn == "Lhf=K%z2"
    assert edge_0.association_type == "Lhf=K%z2"
    var_0 = edge_0.__eq__(edge_0)
    assert var_0 is True
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn == "Lhf=K%z2"
    assert edge_0.association_type == "Lhf=K%z2"
    var_1 = str_0.__eq__(str_1)
    assert var_1 is False
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn == "Lhf=K%z2"
    assert edge_0.association_type == "Lhf=K%z2"
    var_2 = edge_0.__repr__()
    assert (
        var_2
        == "\n\t{'source_arn': None, 'destination_arn': 'Lhf=K%z2', 'association_type': 'Lhf=K%z2'}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn == "Lhf=K%z2"
    assert edge_0.association_type == "Lhf=K%z2"


def test_case_1():
    str_0 = "T&c"
    set_0 = {str_0, str_0, str_0}
    edge_0 = module_0.Edge(str_0, str_0, set_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "T&c"
    assert edge_0.destination_arn == "T&c"
    assert edge_0.association_type == {"T&c"}
    str_1 = "TUf;sj"
    str_2 = '!Qr59eIcN~"|N,x'
    edge_1 = module_0.Edge(str_1, str_2, str_2)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "T&c"
    assert edge_0.destination_arn == "T&c"
    assert edge_0.association_type == {"T&c"}
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == "TUf;sj"
    assert edge_1.destination_arn == '!Qr59eIcN~"|N,x'
    assert edge_1.association_type == '!Qr59eIcN~"|N,x'
    var_0 = edge_1.__eq__(edge_0)
    assert var_0 is False
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "T&c"
    assert edge_0.destination_arn == "T&c"
    assert edge_0.association_type == {"T&c"}
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == "TUf;sj"
    assert edge_1.destination_arn == '!Qr59eIcN~"|N,x'
    assert edge_1.association_type == '!Qr59eIcN~"|N,x'


def test_case_2():
    str_0 = "_,%B?zT?q(/){)F\n"
    none_type_0 = None
    edge_0 = module_0.Edge(str_0, none_type_0, str_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "_,%B?zT?q(/){)F\n"
    assert edge_0.destination_arn is None
    assert edge_0.association_type == "_,%B?zT?q(/){)F\n"


def test_case_3():
    none_type_0 = None
    str_0 = "QZ-JXrP8U+kDh)"
    edge_0 = module_0.Edge(str_0, str_0, str_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_0 = edge_0.__hash__()
    assert var_0 == -7443120729902446468
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_1 = var_0.__hash__()
    assert var_1 == -525591702261364615
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_2 = var_1.__str__()
    assert var_2 == "-525591702261364615"
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_3 = var_2.__str__()
    assert var_3 == "-525591702261364615"
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_4 = var_3.__eq__(none_type_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"
    var_5 = var_4.__repr__()
    assert var_5 == "NotImplemented"
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.destination_arn == "QZ-JXrP8U+kDh)"
    assert edge_0.association_type == "QZ-JXrP8U+kDh)"


def test_case_4():
    int_0 = 1775
    str_0 = ""
    str_1 = "$F]_Zp<:O^fA"
    edge_0 = module_0.Edge(int_0, str_0, str_1)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == 1775
    assert edge_0.destination_arn == ""
    assert edge_0.association_type == "$F]_Zp<:O^fA"
    var_0 = edge_0.__str__()
    assert (
        var_0
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == 1775
    assert edge_0.destination_arn == ""
    assert edge_0.association_type == "$F]_Zp<:O^fA"
    edge_1 = module_0.Edge(var_0, var_0, str_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == 1775
    assert edge_0.destination_arn == ""
    assert edge_0.association_type == "$F]_Zp<:O^fA"
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert (
        edge_1.source_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert (
        edge_1.destination_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert edge_1.association_type == ""
    var_1 = edge_1.__str__()
    assert (
        var_1
        == "{'source_arn': \"{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}\", 'destination_arn': \"{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}\", 'association_type': ''}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == 1775
    assert edge_0.destination_arn == ""
    assert edge_0.association_type == "$F]_Zp<:O^fA"
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert (
        edge_1.source_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert (
        edge_1.destination_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert edge_1.association_type == ""
    var_2 = var_1.__hash__()
    assert var_2 == 2967842945485182615
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn == 1775
    assert edge_0.destination_arn == ""
    assert edge_0.association_type == "$F]_Zp<:O^fA"
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert (
        edge_1.source_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert (
        edge_1.destination_arn
        == "{'source_arn': 1775, 'destination_arn': '', 'association_type': '$F]_Zp<:O^fA'}"
    )
    assert edge_1.association_type == ""


def test_case_5():
    object_0 = module_1.object()
    dict_0 = {object_0: object_0, object_0: object_0}
    edge_0 = module_0.Edge(dict_0, dict_0, object_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert (
        f"{type(edge_0.source_arn).__module__}.{type(edge_0.source_arn).__qualname__}"
        == "builtins.dict"
    )
    assert len(edge_0.source_arn) == 1
    assert (
        f"{type(edge_0.destination_arn).__module__}.{type(edge_0.destination_arn).__qualname__}"
        == "builtins.dict"
    )
    assert len(edge_0.destination_arn) == 1
    assert (
        f"{type(edge_0.association_type).__module__}.{type(edge_0.association_type).__qualname__}"
        == "builtins.object"
    )
    var_0 = edge_0.__repr__()
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert (
        f"{type(edge_0.source_arn).__module__}.{type(edge_0.source_arn).__qualname__}"
        == "builtins.dict"
    )
    assert len(edge_0.source_arn) == 1
    assert (
        f"{type(edge_0.destination_arn).__module__}.{type(edge_0.destination_arn).__qualname__}"
        == "builtins.dict"
    )
    assert len(edge_0.destination_arn) == 1
    assert (
        f"{type(edge_0.association_type).__module__}.{type(edge_0.association_type).__qualname__}"
        == "builtins.object"
    )


def test_case_6():
    none_type_0 = None
    edge_0 = module_0.Edge(none_type_0, none_type_0, none_type_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_0 = edge_0.__repr__()
    assert (
        var_0
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_1 = var_0.__str__()
    assert (
        var_1
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_2 = var_0.__hash__()
    assert var_2 == -8565051644631309537
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_3 = edge_0.__hash__()
    assert var_3 == -5349028566278499182
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_4 = var_0.__str__()
    assert (
        var_4
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_5 = var_0.__repr__()
    assert (
        var_5
        == "\"\\n\\t{'source_arn': None, 'destination_arn': None, 'association_type': None}\""
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_6 = edge_0.__eq__(edge_0)
    assert var_6 is True
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_7 = var_1.__repr__()
    assert (
        var_7
        == "\"\\n\\t{'source_arn': None, 'destination_arn': None, 'association_type': None}\""
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_8 = var_0.__eq__(edge_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_9 = var_0.__str__()
    assert (
        var_9
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_10 = var_0.__str__()
    assert (
        var_10
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_11 = var_10.__repr__()
    assert (
        var_11
        == "\"\\n\\t{'source_arn': None, 'destination_arn': None, 'association_type': None}\""
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_12 = edge_0.__hash__()
    assert var_12 == -5349028566278499182
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    var_13 = edge_0.__hash__()
    assert var_13 == -5349028566278499182
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    edge_1 = module_0.Edge(var_13, var_10, none_type_0)
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
    var_14 = var_3.__repr__()
    assert var_14 == "-5349028566278499182"
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
    var_15 = var_10.__str__()
    assert (
        var_15
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
    var_16 = edge_1.__str__()
    assert (
        var_16
        == "{'source_arn': -5349028566278499182, 'destination_arn': \"\\n\\t{'source_arn': None, 'destination_arn': None, 'association_type': None}\", 'association_type': None}"
    )
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
    var_17 = edge_1.__eq__(edge_0)
    assert var_17 is False
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
    var_18 = var_17.__str__()
    assert var_18 == "False"
    assert (
        f"{type(edge_0).__module__}.{type(edge_0).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_0.source_arn is None
    assert edge_0.destination_arn is None
    assert edge_0.association_type is None
    assert (
        f"{type(edge_1).__module__}.{type(edge_1).__qualname__}" == "snippet_376.Edge"
    )
    assert edge_1.source_arn == -5349028566278499182
    assert (
        edge_1.destination_arn
        == "\n\t{'source_arn': None, 'destination_arn': None, 'association_type': None}"
    )
    assert edge_1.association_type is None
