# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_20 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.AlignakObject()


def test_case_1():
    none_type_0 = None
    alignak_object_0 = module_0.AlignakObject(none_type_0, none_type_0)
    assert (
        f"{type(alignak_object_0).__module__}.{type(alignak_object_0).__qualname__}"
        == "snippet_20.AlignakObject"
    )
    assert module_0.AlignakObject.properties == {}
    assert module_0.AlignakObject.macros == {}


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    str_0 = "a@\\0jmy>\\k"
    module_0.AlignakObject(str_0, bool_0)
