# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_463 as module_0


def test_case_0():
    str_0 = 'T*(GH"'
    node_finder_0 = module_0.NodeFinder(str_0)
    assert (
        f"{type(node_finder_0).__module__}.{type(node_finder_0).__qualname__}"
        == "snippet_463.NodeFinder"
    )
    assert node_finder_0.matcher == 'T*(GH"'
    assert node_finder_0.limit == 0
