# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_713 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x9f\x93\x1f\xf3V"
    set_0 = {bytes_0, bytes_0, bytes_0}
    sentry_middleware_0 = module_0.SentryMiddleware(client=set_0)
    assert (
        f"{type(sentry_middleware_0).__module__}.{type(sentry_middleware_0).__qualname__}"
        == "snippet_713.SentryMiddleware"
    )
    sentry_middleware_0.server_inspect_exception(
        bytes_0, set_0, sentry_middleware_0, bytes_0
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    module_0.SentryMiddleware()


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0}
    module_0.SentryMiddleware(**set_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\xea\xb4/\xe3\xcd\x948.\x1e\xa8\xe5<\xa0.\x96\xa1S\x93"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0}
    none_type_0 = None
    sentry_middleware_0 = module_0.SentryMiddleware(none_type_0, bytes_0)
    assert (
        f"{type(sentry_middleware_0).__module__}.{type(sentry_middleware_0).__qualname__}"
        == "snippet_713.SentryMiddleware"
    )
    sentry_middleware_0.server_inspect_exception(dict_0, none_type_0, bytes_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = -263
    set_0 = {int_0, int_0, int_0}
    sentry_middleware_0 = module_0.SentryMiddleware(client=set_0)
    assert (
        f"{type(sentry_middleware_0).__module__}.{type(sentry_middleware_0).__qualname__}"
        == "snippet_713.SentryMiddleware"
    )
    none_type_0 = None
    list_0 = [sentry_middleware_0, sentry_middleware_0, none_type_0, set_0, set_0]
    sentry_middleware_0.server_inspect_exception(
        none_type_0, none_type_0, int_0, list_0
    )
