class DynamoMappings(object):
    '''Attribute mapping class.

    DynamoDB has some opinions about what you can store or query in an
    attribute. We're going to use mappings to fix that.
    '''

    @staticmethod
    def map_index_val(index_val):
        '''Xform index_val so that it can be stored/queried.'''
        if index_val is None:
            return None
        # pickle and base64-encode to get a storable string
        data = pickle.dumps(index_val, protocol=pickle.HIGHEST_PROTOCOL)
        return base64.b64encode(data).decode('ascii')

    @staticmethod
    def unmap_stored_val(stored_val):
        '''Inverse of index_val_mapping.

        Note that we currently don't use it because we don't actually read back
        index values (since they are generated by Python functions).
        '''
        if stored_val is None:
            return None
        # decode from base64 and unpickle
        data = base64.b64decode(stored_val.encode('ascii'))
        return pickle.loads(data)