# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_757 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    cpc_set_auto_start_list_handler_0 = module_0.CpcSetAutoStartListHandler()
    assert (
        f"{type(cpc_set_auto_start_list_handler_0).__module__}.{type(cpc_set_auto_start_list_handler_0).__qualname__}"
        == "snippet_757.CpcSetAutoStartListHandler"
    )
    bool_0 = True
    str_0 = "o\r"
    cpc_set_auto_start_list_handler_0.post(
        bool_0, bool_0, bool_0, str_0, cpc_set_auto_start_list_handler_0, bool_0, bool_0
    )


def test_case_1():
    cpc_set_auto_start_list_handler_0 = module_0.CpcSetAutoStartListHandler()
    assert (
        f"{type(cpc_set_auto_start_list_handler_0).__module__}.{type(cpc_set_auto_start_list_handler_0).__qualname__}"
        == "snippet_757.CpcSetAutoStartListHandler"
    )
    with pytest.raises(AssertionError):
        cpc_set_auto_start_list_handler_0.post(
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
            cpc_set_auto_start_list_handler_0,
        )


def test_case_2():
    cpc_set_auto_start_list_handler_0 = module_0.CpcSetAutoStartListHandler()
    assert (
        f"{type(cpc_set_auto_start_list_handler_0).__module__}.{type(cpc_set_auto_start_list_handler_0).__qualname__}"
        == "snippet_757.CpcSetAutoStartListHandler"
    )
