# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_295 as module_0


def test_case_0():
    none_type_0 = None
    pushover_0 = module_0.Pushover(none_type_0, none_type_0)
    assert (
        f"{type(pushover_0).__module__}.{type(pushover_0).__qualname__}"
        == "snippet_295.Pushover"
    )
    assert pushover_0.api_token is None
    assert pushover_0.user is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    pushover_0 = module_0.Pushover(none_type_0, none_type_0)
    assert (
        f"{type(pushover_0).__module__}.{type(pushover_0).__qualname__}"
        == "snippet_295.Pushover"
    )
    assert pushover_0.api_token is None
    assert pushover_0.user is None
    pushover_0.validate()


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "@3E"
    bool_0 = True
    pushover_0 = module_0.Pushover(bool_0, bool_0)
    assert (
        f"{type(pushover_0).__module__}.{type(pushover_0).__qualname__}"
        == "snippet_295.Pushover"
    )
    assert pushover_0.api_token is True
    assert pushover_0.user is True
    pushover_0.push(str_0, url=str_0)
