# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_594 as module_0


def test_case_0():
    complex_0 = -1939.70426 + 1467.189j
    user_0 = module_0.User(complex_0)
    assert (
        f"{type(user_0).__module__}.{type(user_0).__qualname__}" == "snippet_594.User"
    )
    assert user_0.client == (-1939.70426 + 1467.189j)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "!p3<CXiPOXn"
    user_0 = module_0.User(str_0)
    assert (
        f"{type(user_0).__module__}.{type(user_0).__qualname__}" == "snippet_594.User"
    )
    assert user_0.client == "!p3<CXiPOXn"
    user_0.info()
