# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_589 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -308
    bool_0 = True
    tuple_0 = (int_0, int_0, bool_0)
    scheme_0 = module_0.Scheme(*tuple_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == (-308, -308, True)
    scheme_0.build_defaults()


def test_case_1():
    scheme_0 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_0 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0]
    scheme_0 = module_0.Scheme(*list_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == (False, False, False)
    scheme_0.flatten()


def test_case_3():
    scheme_0 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    scheme_1 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_0 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_1 = scheme_0.validate(var_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_2 = scheme_0.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    scheme_2 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    var_3 = scheme_2.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    scheme_3 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()
    var_4 = scheme_0.validate(var_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()
    var_5 = scheme_1.validate(var_3)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()
    var_6 = scheme_0.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()


def test_case_4():
    scheme_0 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    scheme_1 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_0 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_1 = scheme_0.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    var_2 = scheme_1.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    scheme_2 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    var_3 = scheme_2.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    scheme_3 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()
    var_4 = scheme_1.validate(var_3)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_1.args == ()
    assert (
        f"{type(scheme_2).__module__}.{type(scheme_2).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_2.args == ()
    assert (
        f"{type(scheme_3).__module__}.{type(scheme_3).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_3.args == ()


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = ""
    list_0 = []
    scheme_0 = module_0.Scheme(*list_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    scheme_0.validate(str_0)


def test_case_6():
    scheme_0 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_0 = scheme_0.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_1 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_2 = module_1.object()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()


@pytest.mark.xfail(strict=True)
def test_case_7():
    scheme_0 = module_0.Scheme()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_0 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_1 = scheme_0.validate(var_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_2 = scheme_0.flatten()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    var_3 = scheme_0.build_defaults()
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    list_0 = [scheme_0, scheme_0, scheme_0, var_3]
    scheme_1 = module_0.Scheme(*list_0)
    assert (
        f"{type(scheme_0).__module__}.{type(scheme_0).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert scheme_0.args == ()
    assert (
        f"{type(scheme_1).__module__}.{type(scheme_1).__qualname__}"
        == "snippet_589.Scheme"
    )
    assert (
        f"{type(scheme_1.args).__module__}.{type(scheme_1.args).__qualname__}"
        == "builtins.tuple"
    )
    assert len(scheme_1.args) == 4
    scheme_1.validate(var_0)
