# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_323 as module_0


def test_case_0():
    str_0 = "eb2UgYC.ZtLn>uA"
    domain_check_interval_0 = module_0._DomainCheckInterval(str_0, str_0)
    assert (
        f"{type(domain_check_interval_0).__module__}.{type(domain_check_interval_0).__qualname__}"
        == "snippet_323._DomainCheckInterval"
    )
    assert domain_check_interval_0.a == "eb2UgYC.ZtLn>uA"
    assert domain_check_interval_0.b == "eb2UgYC.ZtLn>uA"


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -1848
    domain_check_interval_0 = module_0._DomainCheckInterval(int_0, int_0)
    assert (
        f"{type(domain_check_interval_0).__module__}.{type(domain_check_interval_0).__qualname__}"
        == "snippet_323._DomainCheckInterval"
    )
    assert domain_check_interval_0.a == -1848
    assert domain_check_interval_0.b == -1848
    int_1 = -2145
    domain_check_interval_0.__call__(int_1)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "eb2UgYC.ZtLn>uA"
    int_0 = 1633
    bool_0 = True
    domain_check_interval_0 = module_0._DomainCheckInterval(int_0, bool_0)
    assert (
        f"{type(domain_check_interval_0).__module__}.{type(domain_check_interval_0).__qualname__}"
        == "snippet_323._DomainCheckInterval"
    )
    assert domain_check_interval_0.a is True
    assert domain_check_interval_0.b == 1633
    domain_check_interval_0.__call__(str_0)
