# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_662 as module_0
import builtins as module_1


def test_case_0():
    module_0 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    module_0 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    module_0.save_parameters(module_0, module_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    module_0 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    bool_0 = True
    var_0 = module_0.get_modules(bool_0)
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    module_1.object(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "X_Dq8Wf&\t8\\wT<("
    module_0 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    set_0 = {str_0, str_0, str_0, module_0}
    var_0 = module_0.get_modules(set_0)
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    object_0 = module_1.object(*var_0)
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    module_0.load_parameters(var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    module_0 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    module_1 = module_0.Module()
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    assert (
        f"{type(module_1).__module__}.{type(module_1).__qualname__}"
        == "snippet_662.Module"
    )
    none_type_0 = None
    var_0 = module_0.get_modules(none_type_0)
    assert (
        f"{type(module_0).__module__}.{type(module_0).__qualname__}"
        == "snippet_662.Module"
    )
    assert (
        f"{type(module_1).__module__}.{type(module_1).__qualname__}"
        == "snippet_662.Module"
    )
    module_1.object(*var_0)
