# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_484 as module_0


def test_case_0():
    float_0 = -4057.1539
    bucket_0 = module_0.Bucket(float_0)
    assert (
        f"{type(bucket_0).__module__}.{type(bucket_0).__qualname__}"
        == "snippet_484.Bucket"
    )
    assert bucket_0.name == pytest.approx(-4057.1539, abs=0.01, rel=0.01)
    assert bucket_0.service is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 4424
    float_0 = -985.59
    none_type_0 = None
    bucket_0 = module_0.Bucket(float_0, none_type_0)
    assert (
        f"{type(bucket_0).__module__}.{type(bucket_0).__qualname__}"
        == "snippet_484.Bucket"
    )
    assert bucket_0.name == pytest.approx(-985.59, abs=0.01, rel=0.01)
    assert bucket_0.service is None
    bucket_0.list(int_0, int_0)
