# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_419 as module_0
import builtins as module_1


def test_case_0():
    i_py_autocall_0 = module_0.IPyAutocall()
    assert (
        f"{type(i_py_autocall_0).__module__}.{type(i_py_autocall_0).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert module_0.IPyAutocall.rewrite is True
    i_py_autocall_1 = module_0.IPyAutocall(i_py_autocall_0)
    assert (
        f"{type(i_py_autocall_0).__module__}.{type(i_py_autocall_0).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert (
        f"{type(i_py_autocall_1).__module__}.{type(i_py_autocall_1).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert module_0.IPyAutocall.rewrite is True


def test_case_1():
    object_0 = module_1.object()
    list_0 = [object_0, object_0, object_0]
    i_py_autocall_0 = module_0.IPyAutocall()
    assert (
        f"{type(i_py_autocall_0).__module__}.{type(i_py_autocall_0).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert module_0.IPyAutocall.rewrite is True
    var_0 = i_py_autocall_0.set_ip(list_0)
    assert (
        f"{type(i_py_autocall_0).__module__}.{type(i_py_autocall_0).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert module_0.IPyAutocall.rewrite is True
    i_py_autocall_1 = module_0.IPyAutocall()
    assert (
        f"{type(i_py_autocall_0).__module__}.{type(i_py_autocall_0).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert (
        f"{type(i_py_autocall_1).__module__}.{type(i_py_autocall_1).__qualname__}"
        == "snippet_419.IPyAutocall"
    )
    assert module_0.IPyAutocall.rewrite is True
