# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_189 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    dict_0 = {}
    module_0.DevNull(*bool_0, **dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dev_null_0 = module_0.DevNull()
    assert (
        f"{type(dev_null_0).__module__}.{type(dev_null_0).__qualname__}"
        == "snippet_189.DevNull"
    )
    var_0 = dev_null_0.flush()
    assert (
        f"{type(dev_null_0).__module__}.{type(dev_null_0).__qualname__}"
        == "snippet_189.DevNull"
    )
    var_1 = dev_null_0.write()
    assert (
        f"{type(dev_null_0).__module__}.{type(dev_null_0).__qualname__}"
        == "snippet_189.DevNull"
    )
    var_1.flush()
