# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_742 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    material_0 = module_0.Material()
    assert (
        f"{type(material_0).__module__}.{type(material_0).__qualname__}"
        == "snippet_742.Material"
    )
    assert material_0.label == "Material"
    material_0.write_inp()
