class Ui_DialogModulation(object):
    def setupUi(self, DialogModulation):
        DialogModulation.setObjectName("DialogModulation")
        DialogModulation.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogModulation)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(DialogModulation)
        self.comboBox.setGeometry(QtCore.QRect(150, 50, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(DialogModulation)
        self.label.setGeometry(QtCore.QRect(30, 50, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogModulation)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 111, 21))
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(DialogModulation)
        self.spinBox.setGeometry(QtCore.QRect(150, 90, 201, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(DialogModulation)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 111, 21))
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(DialogModulation)
        self.doubleSpinBox.setGeometry(QtCore.QRect(150, 130, 201, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        
        self.retranslateUi(DialogModulation)
        self.buttonBox.accepted.connect(DialogModulation.accept)
        self.buttonBox.rejected.connect(DialogModulation.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogModulation)

    def retranslateUi(self, DialogModulation):
        _translate = QtCore.QCoreApplication.translate
        DialogModulation.setWindowTitle(_translate("DialogModulation", "Modulation Settings"))
        self.label.setText(_translate("DialogModulation", "Modulation Type:"))
        self.label_2.setText(_translate("DialogModulation", "Frequency (Hz):"))
        self.label_3.setText(_translate("DialogModulation", "Amplitude:"))