# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_492 as module_0


def test_case_0():
    vaex_task_result_encoding_0 = module_0.vaex_task_result_encoding()
    assert (
        f"{type(vaex_task_result_encoding_0).__module__}.{type(vaex_task_result_encoding_0).__qualname__}"
        == "snippet_492.vaex_task_result_encoding"
    )
    assert (
        f"{type(module_0.vaex_task_result_encoding.encode).__module__}.{type(module_0.vaex_task_result_encoding.encode).__qualname__}"
        == "builtins.method"
    )
    assert (
        f"{type(module_0.vaex_task_result_encoding.decode).__module__}.{type(module_0.vaex_task_result_encoding.decode).__qualname__}"
        == "builtins.method"
    )
