# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_37 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    none_type_0.getInvolvedTables()


def test_case_1():
    bool_0 = False
    two_attribute_comparison_0 = module_0.TwoAttributeComparison(bool_0, bool_0, bool_0)
    assert (
        f"{type(two_attribute_comparison_0).__module__}.{type(two_attribute_comparison_0).__qualname__}"
        == "snippet_37.TwoAttributeComparison"
    )
    assert two_attribute_comparison_0.leftAttribute is False
    assert two_attribute_comparison_0.operationString is False
    assert two_attribute_comparison_0.rightAttribute is False


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    none_type_0 = None
    two_attribute_comparison_0 = module_0.TwoAttributeComparison(bool_0, bool_0, bool_0)
    assert (
        f"{type(two_attribute_comparison_0).__module__}.{type(two_attribute_comparison_0).__qualname__}"
        == "snippet_37.TwoAttributeComparison"
    )
    assert two_attribute_comparison_0.leftAttribute is True
    assert two_attribute_comparison_0.operationString is True
    assert two_attribute_comparison_0.rightAttribute is True
    two_attribute_comparison_0.getQuery(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    int_0 = -1750
    str_0 = "[>0Iom#%=|8,{'"
    list_0 = [str_0]
    two_attribute_comparison_0 = module_0.TwoAttributeComparison(str_0, list_0, str_0)
    assert (
        f"{type(two_attribute_comparison_0).__module__}.{type(two_attribute_comparison_0).__qualname__}"
        == "snippet_37.TwoAttributeComparison"
    )
    assert two_attribute_comparison_0.leftAttribute == "[>0Iom#%=|8,{'"
    assert two_attribute_comparison_0.operationString == ["[>0Iom#%=|8,{'"]
    assert two_attribute_comparison_0.rightAttribute == "[>0Iom#%=|8,{'"
    var_0 = two_attribute_comparison_0.getArgs(int_0)
    assert (
        f"{type(two_attribute_comparison_0).__module__}.{type(two_attribute_comparison_0).__qualname__}"
        == "snippet_37.TwoAttributeComparison"
    )
    assert two_attribute_comparison_0.leftAttribute == "[>0Iom#%=|8,{'"
    assert two_attribute_comparison_0.operationString == ["[>0Iom#%=|8,{'"]
    assert two_attribute_comparison_0.rightAttribute == "[>0Iom#%=|8,{'"
    var_0.getArgs(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    float_0 = 83.35
    two_attribute_comparison_0 = module_0.TwoAttributeComparison(
        float_0, float_0, float_0
    )
    assert (
        f"{type(two_attribute_comparison_0).__module__}.{type(two_attribute_comparison_0).__qualname__}"
        == "snippet_37.TwoAttributeComparison"
    )
    assert two_attribute_comparison_0.leftAttribute == pytest.approx(
        83.35, abs=0.01, rel=0.01
    )
    assert two_attribute_comparison_0.operationString == pytest.approx(
        83.35, abs=0.01, rel=0.01
    )
    assert two_attribute_comparison_0.rightAttribute == pytest.approx(
        83.35, abs=0.01, rel=0.01
    )
    two_attribute_comparison_0.__repr__()
