# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_563 as module_0


def test_case_0():
    wrapper_0 = module_0.Wrapper()
    assert (
        f"{type(wrapper_0).__module__}.{type(wrapper_0).__qualname__}"
        == "snippet_563.Wrapper"
    )
    wrapper_1 = module_0.Wrapper()
    assert (
        f"{type(wrapper_0).__module__}.{type(wrapper_0).__qualname__}"
        == "snippet_563.Wrapper"
    )
    assert (
        f"{type(wrapper_1).__module__}.{type(wrapper_1).__qualname__}"
        == "snippet_563.Wrapper"
    )


def test_case_1():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0]
    wrapper_0 = module_0.Wrapper(*list_0)
    assert (
        f"{type(wrapper_0).__module__}.{type(wrapper_0).__qualname__}"
        == "snippet_563.Wrapper"
    )
    var_0 = wrapper_0.__call__()
    assert (
        f"{type(wrapper_0).__module__}.{type(wrapper_0).__qualname__}"
        == "snippet_563.Wrapper"
    )
