# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_706 as module_0


def test_case_0():
    none_type_0 = None
    database_0 = module_0.Database(none_type_0)
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )


def test_case_1():
    none_type_0 = None
    database_0 = module_0.Database(none_type_0)
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = database_0.create_statement()
    assert var_0 == "CREATE DATABASE None;"
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )


def test_case_2():
    int_0 = 1015
    database_0 = module_0.Database(int_0)
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = database_0.drop_statement()
    assert var_0 == "DROP DATABASE IF EXISTS 1015;"
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 2287
    database_0 = module_0.Database(int_0)
    assert (
        f"{type(database_0).__module__}.{type(database_0).__qualname__}"
        == "snippet_706.Database"
    )
    assert (
        f"{type(module_0.Database.name).__module__}.{type(module_0.Database.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    database_0.__repr__()
