# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_685 as module_0


def test_case_0():
    extension_p_c_t_s14_0 = module_0.ExtensionPCTS14()
    assert (
        f"{type(extension_p_c_t_s14_0).__module__}.{type(extension_p_c_t_s14_0).__qualname__}"
        == "snippet_685.ExtensionPCTS14"
    )
