# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_186 as module_0


def test_case_0():
    bytes_0 = b"\xe6"
    new_initializer_0 = module_0._new_initializer(bytes_0)
    assert (
        f"{type(new_initializer_0).__module__}.{type(new_initializer_0).__qualname__}"
        == "snippet_186._new_initializer"
    )
    var_0 = new_initializer_0.__repr__()
    assert var_0 == "<new b'\\xe6'>"
    assert (
        f"{type(new_initializer_0).__module__}.{type(new_initializer_0).__qualname__}"
        == "snippet_186._new_initializer"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "r[?\nZRCw/@yn:</MU~B7"
    new_initializer_0 = module_0._new_initializer(str_0)
    assert (
        f"{type(new_initializer_0).__module__}.{type(new_initializer_0).__qualname__}"
        == "snippet_186._new_initializer"
    )
    new_initializer_0.__call__()
