# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_196 as module_0


def test_case_0():
    tornado_manager_0 = module_0.TornadoManager()
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {}
    assert tornado_manager_0.status == {}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1


def test_case_1():
    none_type_0 = None
    tornado_manager_0 = module_0.TornadoManager()
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {}
    assert tornado_manager_0.status == {}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1
    var_0 = tornado_manager_0.add_ioloop(none_type_0, none_type_0)
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {None: None}
    assert tornado_manager_0.status == {None: 0}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1
    var_1 = tornado_manager_0.stop(none_type_0)
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {None: None}
    assert tornado_manager_0.status == {None: 0}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    tornado_manager_0 = module_0.TornadoManager()
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {}
    assert tornado_manager_0.status == {}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1
    var_0 = tornado_manager_0.add_ioloop(none_type_0, none_type_0)
    assert (
        f"{type(tornado_manager_0).__module__}.{type(tornado_manager_0).__qualname__}"
        == "snippet_196.TornadoManager"
    )
    assert tornado_manager_0.ioloops == {None: None}
    assert tornado_manager_0.status == {None: 0}
    assert module_0.TornadoManager.STOPPED == 0
    assert module_0.TornadoManager.STARTED == 1
    tornado_manager_0.start(none_type_0)
