# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_181 as module_0


def test_case_0():
    base_list_operations_0 = module_0._BaseListOperations()
    assert (
        f"{type(base_list_operations_0).__module__}.{type(base_list_operations_0).__qualname__}"
        == "snippet_181._BaseListOperations"
    )


def test_case_1():
    base_list_operations_0 = module_0._BaseListOperations()
    assert (
        f"{type(base_list_operations_0).__module__}.{type(base_list_operations_0).__qualname__}"
        == "snippet_181._BaseListOperations"
    )
    var_0 = base_list_operations_0.__hash__()
    assert (
        f"{type(base_list_operations_0).__module__}.{type(base_list_operations_0).__qualname__}"
        == "snippet_181._BaseListOperations"
    )
