# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_343 as module_0


def test_case_0():
    algorithm_0 = module_0.Algorithm()
    assert (
        f"{type(algorithm_0).__module__}.{type(algorithm_0).__qualname__}"
        == "snippet_343.Algorithm"
    )
    assert algorithm_0.hash_type == "sha1"
    assert algorithm_0.description == "This module generates sha1 hashes"


@pytest.mark.xfail(strict=True)
def test_case_1():
    algorithm_0 = module_0.Algorithm()
    assert (
        f"{type(algorithm_0).__module__}.{type(algorithm_0).__qualname__}"
        == "snippet_343.Algorithm"
    )
    assert algorithm_0.hash_type == "sha1"
    assert algorithm_0.description == "This module generates sha1 hashes"
    algorithm_0.generate(algorithm_0)
