# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_111 as module_0


def test_case_0():
    bytes_0 = b"k\x93\xe6\xd7\xb2\x8c\xb4H"
    tuple_0 = (bytes_0,)
    dict_0 = {tuple_0: bytes_0, tuple_0: tuple_0}
    storage_strategy_base_0 = module_0.StorageStrategyBase()
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    var_0 = storage_strategy_base_0.get(dict_0)
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    none_type_0 = None
    storage_strategy_base_0 = module_0.StorageStrategyBase()
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    var_0 = storage_strategy_base_0.store(bool_0, none_type_0)
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    bool_1 = False
    storage_strategy_base_1 = module_0.StorageStrategyBase()
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    assert (
        f"{type(storage_strategy_base_1).__module__}.{type(storage_strategy_base_1).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    var_1 = storage_strategy_base_1.get(bool_1)
    assert (
        f"{type(storage_strategy_base_0).__module__}.{type(storage_strategy_base_0).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    assert (
        f"{type(storage_strategy_base_1).__module__}.{type(storage_strategy_base_1).__qualname__}"
        == "snippet_111.StorageStrategyBase"
    )
    var_1.get(var_0)
