# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_576 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "u\x0cBtx%?,Il9\nN%I-!"
    module_0.Member(str_0)
