# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_327 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    dict_0 = {bool_0: bool_0}
    module_0.LeaderboardEntry(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    complex_0 = -1939.70426 + 1467.189j
    module_0.LeaderboardEntry(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    dict_0 = {}
    leaderboard_entry_0 = module_0.LeaderboardEntry(dict_0)
    assert (
        f"{type(leaderboard_entry_0).__module__}.{type(leaderboard_entry_0).__qualname__}"
        == "snippet_327.LeaderboardEntry"
    )
    leaderboard_entry_0.__repr__()
