# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_406 as module_0


def test_case_0():
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    none_type_0 = None
    var_0 = aggregate_0.finalize()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    with pytest.raises(ValueError):
        aggregate_0.add_group(none_type_0, var_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_0.add_group(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_0.add(none_type_0, none_type_0, none_type_0)


def test_case_3():
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    var_0 = aggregate_0.json()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    with pytest.raises(ValueError):
        aggregate_0.finalize()


@pytest.mark.xfail(strict=True)
def test_case_4():
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_0.parse(aggregate_0)


def test_case_5():
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    var_0 = aggregate_0.json()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None


def test_case_6():
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    var_0 = aggregate_0.finalize()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_1 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    assert (
        f"{type(aggregate_1).__module__}.{type(aggregate_1).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_1.groups == []
    assert aggregate_1.values == []
    assert aggregate_1.first_group is None
    var_1 = aggregate_0.json()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    assert (
        f"{type(aggregate_1).__module__}.{type(aggregate_1).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_1.groups == []
    assert aggregate_1.values == []
    assert aggregate_1.first_group is None


@pytest.mark.xfail(strict=True)
def test_case_7():
    list_0 = []
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    var_0 = aggregate_0.finalize()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_0.parse(list_0)


def test_case_8():
    bool_0 = False
    aggregate_0 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    aggregate_1 = module_0.Aggregate()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    assert (
        f"{type(aggregate_1).__module__}.{type(aggregate_1).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_1.groups == []
    assert aggregate_1.values == []
    assert aggregate_1.first_group is None
    var_0 = aggregate_0.json()
    assert (
        f"{type(aggregate_0).__module__}.{type(aggregate_0).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_0.groups == []
    assert aggregate_0.values == []
    assert aggregate_0.first_group is None
    assert (
        f"{type(aggregate_1).__module__}.{type(aggregate_1).__qualname__}"
        == "snippet_406.Aggregate"
    )
    assert aggregate_1.groups == []
    assert aggregate_1.values == []
    assert aggregate_1.first_group is None
    with pytest.raises(ValueError):
        aggregate_0.add(aggregate_0, bool_0, bool_0)
