# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_242 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    animation_clip_0 = module_0.AnimationClip()
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_0.set_property(bool_0, bool_0, bool_0, bool_0)


def test_case_1():
    int_0 = 3968
    animation_clip_0 = module_0.AnimationClip(int_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    animation_clip_0 = module_0.AnimationClip()
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = animation_clip_0.lower()
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0.lower()


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b""
    none_type_0 = None
    animation_clip_0 = module_0.AnimationClip(fps=bytes_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_1 = module_0.AnimationClip(bytes_0, none_type_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    dict_1 = {}
    animation_clip_2 = module_0.AnimationClip(dict_0, bytes_0, dict_1)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_3 = module_0.AnimationClip(none_type_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_3).__module__}.{type(animation_clip_3).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    var_0 = animation_clip_2.lower()
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_3).__module__}.{type(animation_clip_3).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_4 = module_0.AnimationClip(bytes_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_3).__module__}.{type(animation_clip_3).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_4).__module__}.{type(animation_clip_4).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_0.set_property(
        animation_clip_2, dict_1, animation_clip_4, animation_clip_1
    )


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b""
    none_type_0 = None
    animation_clip_0 = module_0.AnimationClip(fps=bytes_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    none_type_1 = None
    animation_clip_1 = module_0.AnimationClip(bytes_0, none_type_1, none_type_1)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    dict_1 = {}
    animation_clip_2 = module_0.AnimationClip(dict_0, bytes_0, dict_1)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_3 = module_0.AnimationClip(none_type_0)
    assert (
        f"{type(animation_clip_0).__module__}.{type(animation_clip_0).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_1).__module__}.{type(animation_clip_1).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_2).__module__}.{type(animation_clip_2).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(animation_clip_3).__module__}.{type(animation_clip_3).__qualname__}"
        == "snippet_242.AnimationClip"
    )
    assert (
        f"{type(module_0.AnimationClip.fps).__module__}.{type(module_0.AnimationClip.fps).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.name).__module__}.{type(module_0.AnimationClip.name).__qualname__}"
        == "builtins.member_descriptor"
    )
    assert (
        f"{type(module_0.AnimationClip.tracks).__module__}.{type(module_0.AnimationClip.tracks).__qualname__}"
        == "builtins.member_descriptor"
    )
    animation_clip_2.set_property(bytes_0, bytes_0, bytes_0, dict_0)
