# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_702 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = -2947.8
    module_0.PDFHtml(float_0, float_0, float_0, context=float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    none_type_0 = None
    module_0.PDFHtml(dict_0, dict_0, dict_0, none_type_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = 'q<9,`\x0b>Z#;8"@"*&VUXH'
    dict_0 = {str_0: str_0, str_0: str_0}
    dict_1 = {}
    module_0.PDFHtml(dict_0, str_0, dict_1, dict_1)
