# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_28 as module_0


def test_case_0():
    edge_ngram_indexer_0 = module_0.EdgeNgramIndexer()
    assert (
        f"{type(edge_ngram_indexer_0).__module__}.{type(edge_ngram_indexer_0).__qualname__}"
        == "snippet_28.EdgeNgramIndexer"
    )
