# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_460 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    int_0 = -2631
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    requirekwargs_0 = module_0.requirekwargs(*list_0)
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == (None, None, None, None)
    var_0 = requirekwargs_0.__call__(int_0)
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == (None, None, None, None)
    var_0.__call__(none_type_0)


def test_case_1():
    requirekwargs_0 = module_0.requirekwargs()
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == ()
    requirekwargs_1 = module_0.requirekwargs()
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == ()
    assert (
        f"{type(requirekwargs_1).__module__}.{type(requirekwargs_1).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_1.required == ()
    list_0 = []
    requirekwargs_2 = module_0.requirekwargs(*list_0)
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == ()
    assert (
        f"{type(requirekwargs_1).__module__}.{type(requirekwargs_1).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_1.required == ()
    assert (
        f"{type(requirekwargs_2).__module__}.{type(requirekwargs_2).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_2.required == ()


def test_case_2():
    str_0 = "t!j`jb^(tGcx4"
    complex_0 = -2473.328075 - 1859.55349j
    set_0 = {complex_0}
    list_0 = [set_0, complex_0, complex_0]
    requirekwargs_0 = module_0.requirekwargs(*list_0)
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == (
        {(-2473.328075 - 1859.55349j)},
        (-2473.328075 - 1859.55349j),
        (-2473.328075 - 1859.55349j),
    )
    var_0 = requirekwargs_0.__call__(str_0)
    assert (
        f"{type(requirekwargs_0).__module__}.{type(requirekwargs_0).__qualname__}"
        == "snippet_460.requirekwargs"
    )
    assert requirekwargs_0.required == (
        {(-2473.328075 - 1859.55349j)},
        (-2473.328075 - 1859.55349j),
        (-2473.328075 - 1859.55349j),
    )
