# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_491 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x15"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    buffer_0 = module_0.Buffer(dict_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == {b"\x15": b"\x15"}
    assert buffer_0.n is None
    assert buffer_0.items == [[]]
    buffer_0.is_writable(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = 'zhEe"9E5nt\r[J'
    str_1 = "&:-u@k <~KMi\x0b$~t&Ge"
    buffer_0 = module_0.Buffer(str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_0 = buffer_0.is_readable()
    assert var_0 is False
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1 = buffer_0.write(str_0, str_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1.__contains__(var_1)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    buffer_0 = module_0.Buffer(list_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == []
    assert buffer_0.n is None
    assert buffer_0.items == []
    var_0 = buffer_0.is_readable()
    assert var_0 is True
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == []
    assert buffer_0.n is None
    assert buffer_0.items == []
    none_type_0 = None
    module_0.Buffer(none_type_0, none_type_0)


def test_case_3():
    bytes_0 = b"\x15"
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    buffer_0 = module_0.Buffer(dict_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == {False: False}
    assert buffer_0.n is None
    assert buffer_0.items == [[]]
    with pytest.raises(ValueError):
        buffer_0.is_writable(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = 'zhEe"9E5nt\r[J'
    str_1 = "&:-u@2k <~KMi\x0b$~t&Ge"
    buffer_0 = module_0.Buffer(str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_0 = buffer_0.write(str_0, str_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    bool_0 = True
    module_0.Buffer(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    module_0.Buffer(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = 'zhEe"9E5nt\r[J'
    str_1 = "&:-u@2k <~KMi\x0b$~t&Ge"
    buffer_0 = module_0.Buffer(str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_0 = buffer_0.write(str_0, str_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1 = buffer_0.__contains__(str_0)
    assert var_1 is False
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    bool_0 = True
    module_0.Buffer(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = 'zhEe"9E5nt\r[J'
    str_1 = "&:-u@2k <~KMi\x0b$~t&Ge"
    buffer_0 = module_0.Buffer(str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_0 = buffer_0.write(str_0, str_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1 = buffer_0.read()
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&Ge"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_0.__contains__(var_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = " "
    str_1 = "&:-u@2k <~KMi\x0b$~t&G"
    buffer_0 = module_0.Buffer(str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&G"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    none_type_0 = None
    var_0 = buffer_0.write(none_type_0, str_1)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&G"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1 = buffer_0.write(str_0, str_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&G"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [" "],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_2 = buffer_0.write(none_type_0, none_type_0)
    assert (
        f"{type(buffer_0).__module__}.{type(buffer_0).__qualname__}"
        == "snippet_491.Buffer"
    )
    assert buffer_0.keys == "&:-u@2k <~KMi\x0b$~t&G"
    assert buffer_0.n is None
    assert buffer_0.items == [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [" "],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ]
    var_1.is_readable()
