# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_115 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "xRvLd*u(i\x0bdwC{T)tT"
    module_0.Movie(str_0, str_0, str_0)


def test_case_1():
    str_0 = "%\x0c\x0b0X\r}"
    int_0 = 2382
    movie_0 = module_0.Movie(str_0, int_0, str_0)
    assert (
        f"{type(movie_0).__module__}.{type(movie_0).__qualname__}"
        == "snippet_115.Movie"
    )
    assert movie_0.title == "%\x0c\x0b0X\r}"
    assert movie_0.year == 2382
    assert movie_0.director == "%\x0c\x0b0X\r}"
    var_0 = movie_0.__repr__()
    assert (
        var_0
        == "Movie(title='%\\x0c\\x0b0X\\r}', year=2382, director='%\\x0c\\x0b0X\\r}')"
    )
    assert (
        f"{type(movie_0).__module__}.{type(movie_0).__qualname__}"
        == "snippet_115.Movie"
    )
    assert movie_0.title == "%\x0c\x0b0X\r}"
    assert movie_0.year == 2382
    assert movie_0.director == "%\x0c\x0b0X\r}"
    var_1 = movie_0.__repr__()
    assert (
        var_1
        == "Movie(title='%\\x0c\\x0b0X\\r}', year=2382, director='%\\x0c\\x0b0X\\r}')"
    )
    assert (
        f"{type(movie_0).__module__}.{type(movie_0).__qualname__}"
        == "snippet_115.Movie"
    )
    assert movie_0.title == "%\x0c\x0b0X\r}"
    assert movie_0.year == 2382
    assert movie_0.director == "%\x0c\x0b0X\r}"
    bool_0 = True
    movie_1 = module_0.Movie(str_0, bool_0, var_1)
    assert (
        f"{type(movie_0).__module__}.{type(movie_0).__qualname__}"
        == "snippet_115.Movie"
    )
    assert movie_0.title == "%\x0c\x0b0X\r}"
    assert movie_0.year == 2382
    assert movie_0.director == "%\x0c\x0b0X\r}"
    assert (
        f"{type(movie_1).__module__}.{type(movie_1).__qualname__}"
        == "snippet_115.Movie"
    )
    assert movie_1.title == "%\x0c\x0b0X\r}"
    assert movie_1.year == 1
    assert (
        movie_1.director
        == "Movie(title='%\\x0c\\x0b0X\\r}', year=2382, director='%\\x0c\\x0b0X\\r}')"
    )
