class Ui_DialogModulationParameters(object):
    def setupUi(self, DialogModulationParameters):
        DialogModulationParameters.setObjectName("DialogModulationParameters")
        DialogModulationParameters.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogModulationParameters)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(DialogModulationParameters)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 351, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelModulationType = QtWidgets.QLabel(self.layoutWidget)
        self.labelModulationType.setObjectName("labelModulationType")
        self.gridLayout.addWidget(self.labelModulationType, 0, 0, 1, 1)
        self.comboBoxModulationType = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxModulationType.setObjectName("comboBoxModulationType")
        self.comboBoxModulationType.addItem("")
        self.comboBoxModulationType.addItem("")
        self.comboBoxModulationType.addItem("")
        self.gridLayout.addWidget(self.comboBoxModulationType, 0, 1, 1, 1)
        self.labelFrequency = QtWidgets.QLabel(self.layoutWidget)
        self.labelFrequency.setObjectName("labelFrequency")
        self.gridLayout.addWidget(self.labelFrequency, 1, 0, 1, 1)
        self.spinBoxFrequency = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxFrequency.setMinimum(1)
        self.spinBoxFrequency.setMaximum(1000000)
        self.spinBoxFrequency.setObjectName("spinBoxFrequency")
        self.gridLayout.addWidget(self.spinBoxFrequency, 1, 1, 1, 1)
        self.labelAmplitude = QtWidgets.QLabel(self.layoutWidget)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.gridLayout.addWidget(self.labelAmplitude, 2, 0, 1, 1)
        self.doubleSpinBoxAmplitude = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxAmplitude.setMinimum(0.1)
        self.doubleSpinBoxAmplitude.setMaximum(100.0)
        self.doubleSpinBoxAmplitude.setObjectName("doubleSpinBoxAmplitude")
        self.gridLayout.addWidget(self.doubleSpinBoxAmplitude, 2, 1, 1, 1)
        self.labelPhase = QtWidgets.QLabel(self.layoutWidget)
        self.labelPhase.setObjectName("labelPhase")
        self.gridLayout.addWidget(self.labelPhase, 3, 0, 1, 1)
        self.spinBoxPhase = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxPhase.setMaximum(360)
        self.spinBoxPhase.setObjectName("spinBoxPhase")
        self.gridLayout.addWidget(self.spinBoxPhase, 3, 1, 1, 1)

        self.retranslateUi(DialogModulationParameters)
        self.buttonBox.accepted.connect(DialogModulationParameters.accept)
        self.buttonBox.rejected.connect(DialogModulationParameters.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogModulationParameters)

    def retranslateUi(self, DialogModulationParameters):
        _translate = QtCore.QCoreApplication.translate
        DialogModulationParameters.setWindowTitle(_translate("DialogModulationParameters", "Modulation Parameters"))
        self.labelModulationType.setText(_translate("DialogModulationParameters", "Modulation Type:"))
        self.comboBoxModulationType.setItemText(0, _translate("DialogModulationParameters", "Amplitude Modulation"))
        self.comboBoxModulationType.setItemText(1, _translate("DialogModulationParameters", "Frequency Modulation"))
        self.comboBoxModulationType.setItemText(2, _translate("DialogModulationParameters", "Phase Modulation"))
        self.labelFrequency.setText(_translate("DialogModulationParameters", "Carrier Frequency (Hz):"))
        self.labelAmplitude.setText(_translate("DialogModulationParameters", "Amplitude:"))
        self.labelPhase.setText(_translate("DialogModulationParameters", "Phase (degrees):"))