# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_706 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "A}"
    w_c_s_capabilities_reader_0 = module_0.WCSCapabilitiesReader(
        str_0, auth=str_0, headers=str_0
    )
    assert (
        f"{type(w_c_s_capabilities_reader_0).__module__}.{type(w_c_s_capabilities_reader_0).__qualname__}"
        == "snippet_706.WCSCapabilitiesReader"
    )
    assert w_c_s_capabilities_reader_0.version == "A}"
    assert w_c_s_capabilities_reader_0.cookies is None
    assert w_c_s_capabilities_reader_0.headers == "A}"
    assert w_c_s_capabilities_reader_0.timeout == 30
    assert w_c_s_capabilities_reader_0.auth == "A}"
    w_c_s_capabilities_reader_0.read(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.WCSCapabilitiesReader(bool_0, headers=bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -1437
    w_c_s_capabilities_reader_0 = module_0.WCSCapabilitiesReader(
        auth=int_0, headers=int_0
    )
    assert (
        f"{type(w_c_s_capabilities_reader_0).__module__}.{type(w_c_s_capabilities_reader_0).__qualname__}"
        == "snippet_706.WCSCapabilitiesReader"
    )
    assert w_c_s_capabilities_reader_0.version is None
    assert w_c_s_capabilities_reader_0.cookies is None
    assert w_c_s_capabilities_reader_0.headers == -1437
    assert w_c_s_capabilities_reader_0.timeout == 30
    assert w_c_s_capabilities_reader_0.auth == -1437
    int_1 = -24
    w_c_s_capabilities_reader_0.readString(int_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "sG;"
    w_c_s_capabilities_reader_0 = module_0.WCSCapabilitiesReader(
        cookies=str_0, auth=str_0, headers=str_0
    )
    assert (
        f"{type(w_c_s_capabilities_reader_0).__module__}.{type(w_c_s_capabilities_reader_0).__qualname__}"
        == "snippet_706.WCSCapabilitiesReader"
    )
    assert w_c_s_capabilities_reader_0.version is None
    assert w_c_s_capabilities_reader_0.cookies == "sG;"
    assert w_c_s_capabilities_reader_0.headers == "sG;"
    assert w_c_s_capabilities_reader_0.timeout == 30
    assert w_c_s_capabilities_reader_0.auth == "sG;"
    w_c_s_capabilities_reader_0.capabilities_url(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "E41?z-ysswFJ%G+sOF"
    w_c_s_capabilities_reader_0 = module_0.WCSCapabilitiesReader(auth=str_0)
    assert (
        f"{type(w_c_s_capabilities_reader_0).__module__}.{type(w_c_s_capabilities_reader_0).__qualname__}"
        == "snippet_706.WCSCapabilitiesReader"
    )
    assert w_c_s_capabilities_reader_0.version is None
    assert w_c_s_capabilities_reader_0.cookies is None
    assert w_c_s_capabilities_reader_0.headers is None
    assert w_c_s_capabilities_reader_0.timeout == 30
    assert w_c_s_capabilities_reader_0.auth == "E41?z-ysswFJ%G+sOF"
    w_c_s_capabilities_reader_0.capabilities_url(str_0)
