# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_717 as module_0


def test_case_0():
    none_type_0 = None
    maven_repository_0 = module_0.MavenRepository(none_type_0)
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )


def test_case_1():
    bool_0 = False
    maven_repository_0 = module_0.MavenRepository(bool_0)
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )
    var_0 = maven_repository_0.getRootPath()
    assert var_0 is False
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"@"
    bool_0 = True
    maven_repository_0 = module_0.MavenRepository(bool_0)
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )
    maven_repository_1 = module_0.MavenRepository(maven_repository_0)
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )
    assert (
        f"{type(maven_repository_1).__module__}.{type(maven_repository_1).__qualname__}"
        == "snippet_717.MavenRepository"
    )
    maven_repository_1.getArtifactPath(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    int_0 = -2469
    maven_repository_0 = module_0.MavenRepository(int_0)
    assert (
        f"{type(maven_repository_0).__module__}.{type(maven_repository_0).__qualname__}"
        == "snippet_717.MavenRepository"
    )
    maven_repository_0.getLatestArtifactVersion(none_type_0, none_type_0)
