# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_227 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.Right(**bool_0)


def test_case_1():
    dict_0 = {}
    right_0 = module_0.Right()
    assert (
        f"{type(right_0).__module__}.{type(right_0).__qualname__}"
        == "snippet_227.Right"
    )
    result1_0 = right_0.work()
    assert result1_0 == 0
    assert (
        f"{type(right_0).__module__}.{type(right_0).__qualname__}"
        == "snippet_227.Right"
    )
    right_1 = module_0.Right(**dict_0)
    assert (
        f"{type(right_0).__module__}.{type(right_0).__qualname__}"
        == "snippet_227.Right"
    )
    assert (
        f"{type(right_1).__module__}.{type(right_1).__qualname__}"
        == "snippet_227.Right"
    )
    result1_1 = right_1.work()
    assert result1_1 == 0
    assert (
        f"{type(right_0).__module__}.{type(right_0).__qualname__}"
        == "snippet_227.Right"
    )
    assert (
        f"{type(right_1).__module__}.{type(right_1).__qualname__}"
        == "snippet_227.Right"
    )
