# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_32 as module_0


def test_case_0():
    bool_0 = False
    checkpoint_0 = module_0.Checkpoint(bool_0)
    assert (
        f"{type(checkpoint_0).__module__}.{type(checkpoint_0).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_0.partition_id is False
    assert checkpoint_0.offset == "-1"
    assert checkpoint_0.sequence_number == "0"
    checkpoint_1 = module_0.Checkpoint(checkpoint_0)
    assert (
        f"{type(checkpoint_0).__module__}.{type(checkpoint_0).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_0.partition_id is False
    assert checkpoint_0.offset == "-1"
    assert checkpoint_0.sequence_number == "0"
    assert (
        f"{type(checkpoint_1).__module__}.{type(checkpoint_1).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert (
        f"{type(checkpoint_1.partition_id).__module__}.{type(checkpoint_1.partition_id).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_1.offset == "-1"
    assert checkpoint_1.sequence_number == "0"
    checkpoint_2 = module_0.Checkpoint(checkpoint_0)
    assert (
        f"{type(checkpoint_0).__module__}.{type(checkpoint_0).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_0.partition_id is False
    assert checkpoint_0.offset == "-1"
    assert checkpoint_0.sequence_number == "0"
    assert (
        f"{type(checkpoint_1).__module__}.{type(checkpoint_1).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert (
        f"{type(checkpoint_1.partition_id).__module__}.{type(checkpoint_1.partition_id).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_1.offset == "-1"
    assert checkpoint_1.sequence_number == "0"
    assert (
        f"{type(checkpoint_2).__module__}.{type(checkpoint_2).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert (
        f"{type(checkpoint_2.partition_id).__module__}.{type(checkpoint_2.partition_id).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_2.offset == "-1"
    assert checkpoint_2.sequence_number == "0"


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    dict_0 = {}
    checkpoint_0 = module_0.Checkpoint(dict_0, sequence_number=dict_0)
    assert (
        f"{type(checkpoint_0).__module__}.{type(checkpoint_0).__qualname__}"
        == "snippet_32.Checkpoint"
    )
    assert checkpoint_0.partition_id == {}
    assert checkpoint_0.offset == "-1"
    assert checkpoint_0.sequence_number == {}
    checkpoint_0.from_source(none_type_0)
