# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_163 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xdb`hz\xceG\x0c\x84\xcb\x1b\xf1\xb8^"
    module_0.Sonar(bytes_0, bytes_0)
