# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_65 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "]"
    module_0.PhenoModelHandler(**str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    pheno_model_handler_0 = module_0.PhenoModelHandler()
    assert (
        f"{type(pheno_model_handler_0).__module__}.{type(pheno_model_handler_0).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    int_0 = 619
    pheno_model_handler_1 = module_0.PhenoModelHandler()
    assert (
        f"{type(pheno_model_handler_0).__module__}.{type(pheno_model_handler_0).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    assert (
        f"{type(pheno_model_handler_1).__module__}.{type(pheno_model_handler_1).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    pheno_model_handler_1.phenomodels(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "2"
    dict_0 = {str_0: str_0, str_0: str_0}
    pheno_model_handler_0 = module_0.PhenoModelHandler()
    assert (
        f"{type(pheno_model_handler_0).__module__}.{type(pheno_model_handler_0).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    pheno_model_handler_0.create_phenomodel(str_0, str_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    bool_0 = False
    pheno_model_handler_0 = module_0.PhenoModelHandler()
    assert (
        f"{type(pheno_model_handler_0).__module__}.{type(pheno_model_handler_0).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    pheno_model_handler_0.update_phenomodel(list_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    pheno_model_handler_0 = module_0.PhenoModelHandler()
    assert (
        f"{type(pheno_model_handler_0).__module__}.{type(pheno_model_handler_0).__qualname__}"
        == "snippet_65.PhenoModelHandler"
    )
    pheno_model_handler_0.phenomodel(none_type_0)
