# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_341 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    module_0.NullFernet(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    none_type_1 = None
    null_fernet_0 = module_0.NullFernet()
    assert (
        f"{type(null_fernet_0).__module__}.{type(null_fernet_0).__qualname__}"
        == "snippet_341.NullFernet"
    )
    assert module_0.NullFernet.is_encrypted is False
    var_0 = null_fernet_0.decrypt(none_type_1)
    assert (
        f"{type(null_fernet_0).__module__}.{type(null_fernet_0).__qualname__}"
        == "snippet_341.NullFernet"
    )
    assert module_0.NullFernet.is_encrypted is False
    var_0.encrypt(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "AF^\n+Lo,ac)1M"
    bool_0 = True
    dict_0 = {str_0: bool_0}
    null_fernet_0 = module_0.NullFernet()
    assert (
        f"{type(null_fernet_0).__module__}.{type(null_fernet_0).__qualname__}"
        == "snippet_341.NullFernet"
    )
    assert module_0.NullFernet.is_encrypted is False
    var_0 = null_fernet_0.encrypt(str_0)
    assert var_0 == "AF^\n+Lo,ac)1M"
    assert (
        f"{type(null_fernet_0).__module__}.{type(null_fernet_0).__qualname__}"
        == "snippet_341.NullFernet"
    )
    assert module_0.NullFernet.is_encrypted is False
    module_0.NullFernet(**dict_0)
