# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_21 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.HTTPDaemon(
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
        bool_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.HTTPDaemon(
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
    )
