# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_636 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -1186
    list_0 = [int_0, int_0, int_0]
    module_0.Node(*list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "f-,rjbP\x0b\x0c'vv^:+UCk]8"
    node_0 = module_0.Node()
    assert (
        f"{type(node_0).__module__}.{type(node_0).__qualname__}" == "snippet_636.Node"
    )
    node_0.__and__(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    node_0 = module_0.Node()
    assert (
        f"{type(node_0).__module__}.{type(node_0).__qualname__}" == "snippet_636.Node"
    )
    bytes_0 = b"\xe7\xa9\x8f\xba"
    node_0.__or__(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -412
    node_0 = module_0.Node()
    assert (
        f"{type(node_0).__module__}.{type(node_0).__qualname__}" == "snippet_636.Node"
    )
    node_0.eval(int_0)
