# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_492 as module_0


def test_case_0():
    set_0 = set()
    with pytest.raises(TypeError):
        module_0.BetaDist(set_0, set_0)


def test_case_1():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )


def test_case_2():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_0.expected_value()
    assert var_1 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    beta_dist_1 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    bool_0 = True
    var_2 = beta_dist_1.observe(bool_0, bool_0)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(TypeError):
        beta_dist_1.observe(var_1, beta_dist_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    int_0 = 1876
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.observe(int_0, int_0)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0.observe(bool_0, bool_0)


def test_case_4():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    float_0 = 3644.41082
    beta_dist_1 = module_0.BetaDist(bool_0, float_0)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_1.variance()
    assert var_0 == pytest.approx(0.9999999247499065, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_1.expected_value()
    assert var_1 == pytest.approx(0.0002743175047689138, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1.likelihood()


def test_case_6():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    none_type_0 = None
    with pytest.raises(TypeError):
        beta_dist_0.observe(beta_dist_0, none_type_0)


def test_case_7():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.variance()
    assert var_0 == pytest.approx(0.75, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_0.expected_value()
    assert var_1 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    beta_dist_1 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_2 = beta_dist_1.observe(var_1, var_1)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(TypeError):
        module_0.BetaDist(default_beta=var_2)


def test_case_8():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_0.expected_value()
    assert var_1 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    beta_dist_1 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_2 = beta_dist_1.observe(var_1, var_1)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    bool_0 = True
    var_3 = beta_dist_1.observe(bool_0, bool_0)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(TypeError):
        beta_dist_1.observe(var_1, var_2)


def test_case_9():
    bool_0 = False
    with pytest.raises(ValueError):
        module_0.BetaDist(default_beta=bool_0)


def test_case_10():
    bool_0 = False
    with pytest.raises(ValueError):
        module_0.BetaDist(bool_0)


def test_case_11():
    bool_0 = False
    int_0 = 1847
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(ValueError):
        beta_dist_0.observe(bool_0, int_0)


def test_case_12():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_0.expected_value()
    assert var_1 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(TypeError):
        module_0.BetaDist(var_0, beta_dist_0)


def test_case_13():
    beta_dist_0 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_0 = beta_dist_0.likelihood()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_1 = beta_dist_0.expected_value()
    assert var_1 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    beta_dist_1 = module_0.BetaDist()
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    var_2 = beta_dist_0.expected_value()
    assert var_2 == pytest.approx(0.5, abs=0.01, rel=0.01)
    assert (
        f"{type(beta_dist_0).__module__}.{type(beta_dist_0).__qualname__}"
        == "snippet_492.BetaDist"
    )
    assert (
        f"{type(beta_dist_1).__module__}.{type(beta_dist_1).__qualname__}"
        == "snippet_492.BetaDist"
    )
    with pytest.raises(ValueError):
        beta_dist_1.observe(var_1, var_0)
