# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_184 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    log_errors_0 = module_0.LogErrors(bool_0, bool_0)
    assert (
        f"{type(log_errors_0).__module__}.{type(log_errors_0).__qualname__}"
        == "snippet_184.LogErrors"
    )
    assert log_errors_0.function is False
    assert log_errors_0.errors is False
    assert log_errors_0.error_count == 0
    log_errors_0.__call__()


def test_case_1():
    complex_0 = -330.99993 + 1632.260059j
    list_0 = [complex_0]
    with pytest.raises(AssertionError):
        module_0.LogErrors(list_0, list_0)


def test_case_2():
    str_0 = "ignore"
    log_errors_0 = module_0.LogErrors(str_0, str_0)
    assert (
        f"{type(log_errors_0).__module__}.{type(log_errors_0).__qualname__}"
        == "snippet_184.LogErrors"
    )
    assert log_errors_0.function == "ignore"
    assert log_errors_0.errors == "ignore"
    assert log_errors_0.error_count == 0
    var_0 = log_errors_0.__call__()
    assert (
        f"{type(log_errors_0).__module__}.{type(log_errors_0).__qualname__}"
        == "snippet_184.LogErrors"
    )
    assert log_errors_0.function == "ignore"
    assert log_errors_0.errors == "ignore"
    assert log_errors_0.error_count == 1


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -3728
    list_0 = [int_0, int_0, int_0]
    str_0 = "raise"
    none_type_0 = None
    log_errors_0 = module_0.LogErrors(none_type_0, str_0)
    assert (
        f"{type(log_errors_0).__module__}.{type(log_errors_0).__qualname__}"
        == "snippet_184.LogErrors"
    )
    assert log_errors_0.function is None
    assert log_errors_0.errors == "raise"
    assert log_errors_0.error_count == 0
    log_errors_0.__call__(*list_0)
