# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import snippet_653 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    fitness_transformation_0 = module_0.FitnessTransformation(bool_0)
    assert (
        f"{type(fitness_transformation_0).__module__}.{type(fitness_transformation_0).__qualname__}"
        == "snippet_653.FitnessTransformation"
    )
    assert fitness_transformation_0.inner_fitness is False
    fitness_transformation_0.__call__(bool_0)


def test_case_1():
    bool_0 = False
    fitness_transformation_0 = module_0.FitnessTransformation(bool_0)
    assert (
        f"{type(fitness_transformation_0).__module__}.{type(fitness_transformation_0).__qualname__}"
        == "snippet_653.FitnessTransformation"
    )
    assert fitness_transformation_0.inner_fitness is False
