# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import snippet_572 as module_0


def test_case_0():
    complex_0 = -1939.70426 + 1467.189j
    uri_param_0 = module_0.UriParam(complex_0)
    assert (
        f"{type(uri_param_0).__module__}.{type(uri_param_0).__qualname__}"
        == "snippet_572.UriParam"
    )


def test_case_1():
    str_0 = "!p3<CXiPOXn"
    uri_param_0 = module_0.UriParam(str_0)
    assert (
        f"{type(uri_param_0).__module__}.{type(uri_param_0).__qualname__}"
        == "snippet_572.UriParam"
    )
    var_0 = uri_param_0.__repr__()
    assert var_0 == "!p3<CXiPOXn"
    assert (
        f"{type(uri_param_0).__module__}.{type(uri_param_0).__qualname__}"
        == "snippet_572.UriParam"
    )
